---
output:
  pdf_document: default
  html_document: default
---
# 2011 elections -Quick thoughts!^[https://www.facebook.com/profile.php?id=620617398]

Saturday, February 19, 2011 at 8:35pm 

David is right. 

May I add some quick notes. Analysing this is going to take days to months and is going to be very interesting! 

While my sympathies lie with the opposition, none of them particularly tickles my fancy. My comments should therefore be viewed as constructive criticism^[https://www.facebook.com/note.php?note_id=10150094332242681]! 

The 'massacre' at presidential level maybe a reflection of the real and perceived weaknesses of the presidential candidates themselves. There is no doubt though that the power of incumbency particularly the resources at the disposal of Museveni thrown at this election may also have their own story to tell. Obviously other pragmatic things like __"twebaka ku tulo"__ may have played their role too^[https://www.facebook.com/note.php?note_id=488948312680]!. At the end of the day, out history remains relevant and continues to be manipulated quite deftly I must admit by the incumbent^[https://www.facebook.com/note.php?note_id=10150094334267681]. We are going to have to find out where we went wrong^[https://www.facebook.com/note.php?note_id=483879117680]! 

Underestimating the son of Kaguta has always been the downfall of his opposition! The over reliance on 'agende' and he has been in power too long rather than articulating what makes them better qualified to take over has always been their weakness^[https://www.facebook.com/note.php?note_id=500786022680]! Paying the LC's was a coup that they couldn't have foreseen! LC's are the doorway to each village and its inhabitants. They know everyone and are indispensable in doing a house to house 'kakuyege'! I wrote this about Museveni's grassroots campaign machine in 2004 using the LC's^[https://www.facebook.com/note.php?note_id=499939492680]

The 'massacre' of Museveni's cabinet that appears to be emerging itself tells another story. I doubt that that could have been an accident! clearly Ugandans believe that their politicians are like diapers -and need to be changed regularly. Why they don't believe in changing their president needs further study. Could it be that the campaign of "the president is a good man surrounded by bad people" actually worked? At least we are closer to getting away from the Kenyan disease.^[https://www.facebook.com/note.php?note_id=486232492680] The real question though is going to be whether there is enough change in parliament to act as an effective check and balance on Museveni! Of course Museveni will resort to his best tool -just buy all of them! With oil, he is armed and dangerous! One would hope that we have not exchanged one bunch of peasants in suits for another bunch of peasants in suits who will be busy making deals for themselves with the devil instead of advocating for their voters! 

The leader of the opposition has been a casualty of this election. Personally i think he was not very effective and needs to find another job too! I wouldn't be surprised if Kaguta offered him one too! His involvement in the death of a young lady also left too many unanswered questions!^[https://www.facebook.com/note.php?note_id=488954117680] I would love to believe that his electorate are punishing him for this! 

Buganda is also going to be interesting. I have seen some claiming that its a referendum on Kabaka versus Museveni which I doubt. I suspect this is an example of voter sophistication. Certainly the fact that the Kabaka remains probably the biggest crowd puller in Uganda without spending any money and can beat any of the presidential candidates who have to spend massive amounts of money is interesting. 

The sources of Museveni's funding will need to become subject to debate. Am not sure what Uganda's laws regarding disclosure of funding sources for political parties is but if they exist, am hoping that someone will visit the constitutional court and demand that they all declare their funding sources! Certainly in these days of oil, it is imperative that the public know which candidate was owned by which oil company! 

The recent constitutional ruling on independents will be the second level. this is not yet over until all of the injunctions are dealt with! this is going to be lawyer season for the next few months!!! 

There is no doubt that the field is not level at the level of presidential elections. Certainly none of the opposition can match the use of state resources that Kaguta has access to. I suspect that a return trip to the supreme court claiming rigged will have the same outcome as in 2006.^[https://www.facebook.com/note.php?note_id=486600427680]. 

As I have said before, there is incompetence and there is rigging! How much of this election is rigging and how much is incompetence is unclear! What is clear is that the best that the opposition could ever hope for was a run off and even that was a long stretch^[https://www.facebook.com/note.php?note_id=293997787680] ^[https://www.facebook.com/note.php?note_id=381085707680]! I wrote some predictions in the past that remain relevant even though they were written before the 2006 election!^[https://www.facebook.com/note.php?note_id=433787272680] 

I think that after a decent time has elapsed, and the dust has settled down, Kiggundu needs to get sacked for this EC is incompetent!^[https://www.facebook.com/note.php?note_id=10150095148497681] An electoral commission that people have confidence in needs to be created and resourced! 

Elections and the talk of war makes Ugandans very nervous. There has been a significant amount of talk about war. I have written about this before and why it could backfire. Certainly it works for the incumbent to talk about the prospect of war and drum up sentiments but it does the opposite for his opposition! ^[https://www.facebook.com/note.php?note_id=293571052680]

The Otunnu factor fizzed out very early! He underestimate the 'collective memory' factor with which he came face to face when he visited Kasubi! He too is going to have to look for another UN job unless he comes down to earth and goes back to basics -or find himself a wife^[https://www.facebook.com/note.php?note_id=280423437680]. Time will tell if he has got the staying power! The messianic complex he brought into the fray did not materialise and he soon realised that while many would like to get rid of Museveni, they do not view him as their messiah.He thought he could just waltz in, kiss the ground and leadership would be his even if he hadn't worked for it for a single day! this time around Kaguta's security idiots unlike in the past when they arrested Besigye had enough brains not to do his job for him by arresting him! 

I can predict here and now that his 5 million man march is going to be a non starter! At the end he even failed to vote for himself while showing contempt for his followers! I wouldn't be surprised if UPC disbanded and individuals found new homes -NRM perhaps! Otunnu learnt nothing from the past and brought a naivety to this election that was surprising given his experience!!^[https://www.facebook.com/note.php?note_id=389531617680] 

He has now given a press conference to 'explain' why he did not vote -mbu he did not want to waste his time since it was not free and fair! I consider this to be contempt of his followers. Why did he waste their time and vote? Is he going to refund taxpayer money given to him for campaigns? 

As for Besigye, am afraid he will have to find another job! like many ministers he is going to have to go and look after his goats and ducks! I am waiting to see whether he will graciously turn up in kololo for the hand over or whether he will shun it. I can bet that otunu will not go while Mao and Betty Kamya will^[https://www.facebook.com/note.php?note_id=488899497680].

Kamya needs to find a vehicle to hitch her carriage too. On her own, she is just going to be another Bidandi! Saying that bidandi really needs to hang his boots up! Bwanika also needs to find a new vehicle. Mao will have to decide whether DP on its own is an adequate vehicle. The rest need to retire. 

If Mao ever mentions the Nile Republic again, I will delete him from my list of potential future presidential aspirants to watch! I have been watching Mao for many years and have several notes on him. However i did not believe that he was ready for this election. I think that 2016 is his year -kind of make or break!On the other hand his ambition makes him vulnerable to doing a 'Kagimu' or an 'Atubo' if he sees time running out increasing his risk of becoming a ssemogerere! Museveni is quite good at killing off his opposition by keeping their mouths full! 

A year ago I wondered whether Mao was a fresh breath on Uganda's politics -I am still not too sure!^[https://www.facebook.com/note.php?note_id=342439367680]. In making his declarations on the Mao republic, expressing his "solidarity" with kony during the peace jokes, his handling of DP dissenters and his handling of Suubi, I am not sure that he has really learnt much from his own past!^[https://www.facebook.com/note.php?note_id=340019517680] 

The return of Museveni leaves us with the same problems we had before -corruption, prolonged incumbency^[https://www.facebook.com/note.php?note_id=281916497680], the lack of a succession plan and the risk of his rule becoming a dynastic one, Somalia^[https://www.facebook.com/note.php?note_id=438045762680], the problems of the oil curse, potholes, poor infrastructure and mismanagement^[https://www.facebook.com/note.php?note_id=414346822680], increased tribalism to fill the gap left by Museveni undermining all institutions^[https://www.facebook.com/note.php?note_id=499182852680], a personal army that cannot be called a national army, and lies, lies and broken promises^[https://www.facebook.com/note.php?note_id=280601647680]! 

The question has been asked as to whether Uganda is ripe for the Jasmine revolution. I personally don't believe it is yet but I have no doubt that it will be! Uganda has all of the hallmarks but at the moment does not have equipoise! these elections are unlikely to be the trigger!^[https://www.facebook.com/note.php?note_id=10150092832897681]. Something else say Somalia spilling over into Uganda, another attack on the Kabaka or Omukama, a misjudged heavy handed treatment of a peaceful demonstration or just about anything could trigger one. Certainly Otunnu cannot trigger one even though am sure he would love to! Only Museveni can prevent a Jasmine revolution by learning from Egypt and Tunisia and pre emptying it by making clear and activating his retirement plan! 

In the meantime we will continue to ask whether Uganda really is a democracy!^[https://www.facebook.com/note.php?note_id=433811377680]. We shall have to ask ourselves how to best empower Ugandans to advocate for their own interests rather than be swayed by brown envelopes and salt and sugar!^[https://www.Facebook.com/note.php?note_id=490312807680]. We shall continue to look at others such as the Chinese and Singapore and how they did it^[https://www.facebook.com/note.php?note_id=489380857680]. And we shall need to ponder how to best develop our country^[https://www.facebook.com/note.php?note_id=489384952680]. 

Most of all we shall have to think about how to prevent Museveni from passing on his power to his son in hereditary rulership!

[1]: https://www.facebook.com/note.php?note_id=499894547680 
