# Defending my sweetheart!^[https://www.facebook.com/notes/drew-ddembe/defending-my-sweetheart/10150278625752681]

Wednesday, August 24, 2011 at 9:54pm ·


A4C does not cease to amaze!

A few weeks ago there was an attack on the 3 admins of A4C in what appeared to be a coordinated "decapitation attack" that ould only have been meant to paralyse A4C!

Interestingly it came from what at first sight would appear to be friendly quarters! the author of that attack has since lost credibility and his allegiance in this fight is now questionable!

I periodically write pieces that make a point at Nina's expense. Those pieces have become very popular! By mixing fact and satire, a message can be conveyed. it is now common knowledge that Nina is my sweetheart! So today I will do what seethearts do -defend their loved ones!

This late attack on my sweetheart is what can be called below the belt. it relies on speculation, rumour and innuendo and possibly falsehood packaged and presented as "news"! Truthful news at that! It was published on a blog that passes itself off as a news blog http://256news.com/?p=1701 Interestingly the style is in the "scoop" style associated with the author of the recent attacks on A4C!

Unfortunately while the style of this story would do a tabloid proud, it is not particularly useful on A4C and neither is it really informative! I personally do not believe that I come away with any knowledge as to why Nina "attacks", I would say criticises the government her father serves!

Quite frankly, I do not consider it newsworthy that Nina has got marital problems as alleged. To say the truth, it is to put it mildly insulting to expect readers to believe that Nina criticises the government of which her father is the leader of government business because she is unhappy with her marriage!!! As for the attempts at using the first lady to explain all sorts of intrigue, puhlease, with all due respect, the woman has never been that influential!

This attack is based on the fallacy of "Abusive ad hominem" (also called personal abuse or personal attacks). According to Wikipedia, this "usually involves insulting or belittling one's opponent in order to attack his claim or invalidate his argument, but can also involve pointing out factual but apparent character flaws or actions that are irrelevant to the opponent's argument. This tactic is logically fallacious because insults and negative facts about the opponent's personal character have nothing to do with the logical merits of the opponent's arguments or assertions."

The author of this piece of trash would have us believe that certain failings in Nina's personal life are relevant to understanding why she criticises the government without in anyway informing us whether Nina's arguments are factual or logical!

By reducing Nina's motivation to a personal attack on the government for personal revenge, the author is implying that Nina Mbabazi, does not have a good or logical arguments against this government! He does not invite us to examine Nina's arguments or criticism! Instead he invites us to examine her bedroom and look under her bed like that is relevant!

This post should be deleted from A4C. If A4C is happy to host such posts, then they should have no problem with posts about Anne Mugisha 's, Charles Makmots or Mary Kelly's private life which quite frankly are not relevant to their crriticism of the NRM! Just like the intrusion into Charles life was resisted by A4C members, this intrusion in Nina's offline life using the A4C wall should be resisted!

We all grew up under the NRM and many of us have conflicted relationships with it. Many come from homes where the parents may have supported or still support the NRM. It is even harder for the children of core insiders to come out and criticise the system their parents created and serve. I would however like to believe that they too find the dust, the chaos, the corruption, the darkness of Kampala as irksome as I do even though their dads and mums may preside over it! Actually it may explain why many children of NRM bigwigs do not reside in Uganda and are residents of other nations!

It takes a very brave person to criticise the system under which they grew up particularly when they happen to be insiders of and direct beneficiaries of that system like Nina is! Of course Nina could be playing a game, but the author of this article really has not proven that! In the meantime, let Nina's words be allowed to stand for themselves. Of course if she is being cynical, she will ultimately pay the price!

P.S: Facebook needs a dislike button!
