# For how long are we supposed to be beholden to those who fought?


Amos,

For how long are we supposed to be beholden to those who fought?

I have two uncles who fought. One died -in Ugandan parlance, he sat on a bomb after the take over of Kampala. He was one of th young boys who joined up early but wont be mentioned in the 27! He took his younger brother with him who must have been around 16 or 17. He left as soon as the war ended. they were never soldiers. They took up arms to fight for a cause and went back to their lives when the war ended. They had intimate stories of all of the high command! An uncle who did not go to the bush was witch hunted for most of Obote II and lost most of his wealth, his family while spending most of his time in and out of jail. While he was Museveni's comrade, and stood on a UPM ticket, Museveni did not know him when he returned even though he was one of the casualties of his war. He died in poverty while his children got scattered among various relatives and friends.

Many people died in the cross fire and lost their livelihoods and homes as well as their lives. They are not war heroes -not even post humous.

This war was fought and won by many people who never made it to Kampala or requested voluntary demobilisation as soon as the war ended. They were not interested in Museveni's rhetoric.

Museveni came to power wih pseudomarxist rhetoric that gave a traumatised population the hope that he was going to be different. That his was a fundamental change from the demagogues and illiterate killers who had preceded him. he of course gave traction to the rumour that he was a reluctant leader. He cobbled together a union of people including former opponents save for the most rabid and extreme. After one termof the inclusive democracy of the CA under Whapakabulo, he received an extension as people thought that it was required for stability in order to build institutions and rebuild infrastructure.

He subsequently unmasked himself when he demanded and got a third term (now called his first term in a semantic coup), followed by a second term. At this point he came up against the road block of term limits that had been though to be necessary in the first parliament after an all inclusive nationwide constitution building process. The "people representatives" in parliament voted to remove term limits!

Museveni promised that this was going to be his last term. He claimed that he still had a job to finish -to create a truly national army.

There are however signs that Museveni has instead been constructing a personal institution constructed around his own person. He has systematically undermined parliament and the judiciary. Instead of training police officers, he has infiltrated its highest ranks with military men. His son graduated from his uncles businesses to the army and has seen a meteoric rise through the ranks punctuated by stints at both fort leavenworth and Sandhurst -a significant achievement for one career officer! As a cadet officer, he embarrassed senior army officers by commissioning a review of the army by his as yet un commissioned son! He went on to put him in charge of his own bodyguard in a ove reminiscent of Mobutu. His brother has continued to enjoy a priviledged life despite his checkered lifestyle and flirtation with scandal and corruption. Yet he has never ever been charged and even went on to become a minister and is now a presidential adviser. His wife has since joined the parliament. His sons in law have been involved in business deals with government worth millions of dollars which smirks of nepotism. His in law Kuteesa has been named in other seriously flawed corruption scandals. his biggest NRM bush war comrades such a Mbabazi, Muhwezi have been mentioned some more than once in corruption scandals involving millions in public funds. His daughter works in his office while other relatives can be demonstrated to be employed withing high levels of government as well as doing business with government.

By lining up his family and cronies, Museveni defeats democracy. By actively undermining the growth of independent institutions and promoting the culture where all ideas and decisions are made by one man, he has built a government where everything is centred around his person. By maintaining a stranglehold over all resources and prolonged incubency, he effectively limits the democratic space. By using the police to actively prevent public discourse against his government instead of them being non partisan providers of security, he again controls nd retards our democratic organisation. His argument was that Ugandans were politically not mature enough to handle democracy so there was a need to suspend political activities and spend more time on national unity. After 24 years in power, we are exactly were we were with a despot albeit one with more control over his army whom a significant part of the population are increasingly hoping to get rid of.

With prolonged incubency and a narrowing of political space, there are signs of an increasing adicalisation of Ugandans. That cannot be good. Those who are watching the situation and watched the almost spontaneous conflagration that followed his stupid decision to curtail the movements of the kabaka within his own kingdom should expect problems in the next election. Museveni of course blamed the opposition but the truth be said, Uganda's opposition does not have that much power within Uganda and Buganda! While they got regions that were desperate to dislodge Museveni to vote against him in the last election, there is little evidence that the opposition parties themselves actually control those votes! Thats why a "spoiler" like Otunu entering the fray on a UPC ticket has potential to take votes away from the FDC after splitting UPC giving the vistory again to Museveni!

Ours is a brittle "democracy". One that can break down overnight just lke happened in Kenya. am afraid that an election is going to be the required catalyst. A look at recent elections that ended in widespread civil unrest suggests that there maybe a link between close elections and civil unrest in countries that do not have a mechanism for coalition governments. an increasingly vocal and not insignificant minority of 49% in our country that has a winner take all democracy has potential to break down overnight into street fights.

A look at Museveni's record suggests that he loses about 10 % of the vote at each subsequent election. This suggests that this is the year when his votes may drop close to the critical 50/50% mark. A close win will trigger the usual calls of "rigged" except that with increased numbers in opposition as well as increasing radicalisation, the populace is more likely to end up in the streets. Coupled with the idiotic response of Uganda's security forces who will "break skulls", a demonstration would almost certainly turn into a riot! it is so predictable, one wonders why they always keep making the same mistake. The "bimeeza's" allowed people to vent and gave them the impression of at least being able to voice their opposition. A demonstration has similar effect and the role of the police should be to provide security rather than go in to break it up violently which almost always leads to a riot and deaths such as happened when the forces shot and killed almost 30 people in the Buganda riots.

Surely 30 million people can produce alternate leadership. And surely a party of 8.5 million people should be able to produce an alternate leader in a period of a quarter of a century! the fact that the NRM itself cannot produce new leaders from within itself tells you the magnitude of our problem. the fact that Museveni could not find anyone willing in his own party or even independents and other parties (Atubo came from UPC) and claimed he had to appoin his own wife minister for Karamoja suggests the problem!

Museveni is setting us up for an "Eyadema" where on the death of the incubent, his son bypassed constitutional protocol and became t

![
