# Health -Using figures to tell lies!^[https://www.facebook.com/note.php?note_id=10150092609607681]

Tuesday, February 1, 2011 at 10:35pm


@ Mbabazi,  
 
When brevity is required, i use it. When the subject requires more, my posts which are really notes to myself that i have been writing for years will be longer.  
   
You are right, I am not impressed by Kaganzi! Obviously he does not know much about health services and neither does he know much about Ugandans! He is making up "government policy" on the run to make up for the deficiencies of the NRM!  
   
Official Ugandan government policy is to provide free "health for all"! unfortunately they set the bar so low, but hope that Ugandans are so stupid, they cannopt see when they are being sold air!  
   
IHK, Paragon, Nakasero, Gulu Independent are all purely private hospitals. They each have weaknesses that we shall not go into! All of these facilities are so expensive that their effective coverage of the Ugandan population is in single digits! you cannot base the healthcare system of a whole country of 33 million people on these hospitals.  
   
Ishaka Teaching hospital is a beneficiary of government patronage both because of who the owner is -an NRM party member who is a party donor who receives government patronage and "launders" it before returning it to the NRM as "donations". There are numerous other cases where he has received loans and outright grants from government in exchange for very little back to the taxpayer! During the construction of Ishaka, he received extraordinary tax concessions on building materials ordered by the president in the hundreds of millions of shillings! Lecturers in the teaching hospital, a private facility receive payments and salaries from the government again in special arrangements orderd by state house while this hospital receives government money. It cannot therefore be compared to any of the other hospitals. Paragon which looked very good on paper, practically went broke in less than two years!  
   
God forbid you ever get admitted to one of these "hospitals" some of which are really not fit to carry the name except to Kampala's ignorant glitteratti! the cost per day is in the hundreds of thousands to the millions of shillings per day! More than 90% -I would daresay well over 95% of ugandans would not be able to go anywhere near these facilities!  
   
How then does a government cater for the over 90% of Ugandans who need healthcare but would never be able to pay for care in any of these facilities when it has virtually completely disengaged itself from providing healthcare services to them and left it to an underfunded private sector that quite frankly caters only to the top 2 to 5 %?  
   
Even in developed nations equipment like CT scanners (there is more than CT you know in terms of medical diagnostic technologies), requires government expenditure. Even private facilities receive government capitation grants in order to access new technologies in public-private partnerships!  
   
No country in the world can afford to pass the responsibility for providing medical services to the private sector! In a very poor country like Uganda, only by abdicating its responsibility to provide health services to its citizens can the government sit back and pass the buck to the private sector!  
   
As for Ms Tracy's spirited defence -again one has to ask a simple question! When did you people last ever visit any of these facilities you spout wonderful figures about? Half of the nation is under the age of 15. Real unemployment is virtually unrecordable. even those who claim to be employed can't really be said to be employed -the more correct term being disguised unemployment! Count the number of taxi touts at a Wandegeya stop all calling for passengers to Kampala (there is no other destination for taxis that stop there), add the drivers and the conductors then tell me that those people really all need to be there? Ditto the number of boda bodas at one stage most really just chewing mairungi all day! How many of them are really emplyed and how many are pretending to be employed? Add the retirees and the paesants -who exactly is meant to guarantee that these people get a reasonable healthcare if not the government?  
   
And before you tell me about the health centres, please read my earlier post on healthcentres!
