# Les vainqueurs prennent immédiatement les vices des vaincus^[https://www.facebook.com/note.php?note_id=10150104446707681]  

Wednesday, February 23, 2011 at 8:57pm


[Rachel](https://www.facebook.com/rachel.mbabazi,

Les vainqueurs prennent immédiatement les vices des vaincus

I agree,

Familiarity breeds contempt. though this goes well beyond familiarity.

The truth remains that there are major gaps in service delivery but not only that definite stagnation and manytimes retrogression!

Economic growth that does not translate into meaningful changes that people can identify with is just figures in glossy brochures shared over capucchinos and fancy wines in air conditioned conference rooms in fancy hotels owned by the authors of the same reports!

Term limits need to be returned. Ugandans will trust a president who they know will have to retire in a few years but will not trust one who keeps moving the goal posts every five years.

In 1986, he claimed he did not want to be president -but the political wing had appointed him for five years. Ugandans gave him a blank cheque. After five years, he said, there would be elections.

Five years later, he moved the goal posts -Ugandans needed time to draft a new constitution. Again Ugandans understood -after all we have a very nasty history. No man should be expected to do everything in just one term! So his term was extended to 10 years.

In 1996, under the new constitution, he stood for _"the first of a possible 2 terms"_. The new constitution needed to be test driven and who better to do so than Museveni! And you know there was the small matter of pacifying the north -which of course no one else could do as no one else owned an army and Generals! You see Semogerere was just a civilian!

In 2001, the man 'deserved' a second term -and you know that war still had to be fought. And there were other wars to fight in Congo and such places with Timber, coltan, Gold and diamonds. You see the diamonds needed to be liberated! Plus there was some annoying jumped up colonel who needed to be put in his place! After taking the bosses spare woman, he imagined he could now replace him in state house! The weak doctor who 'never fought' in the bush dared to suggest that the movement had lost its way and the emperor was naked!

In 2006, the constitution that Ugandans had spent so much time drafting and passing was defiled by the same man who had once said that the problem of Africa was leaders who did not want to leave power. He kept reminding Ugandans that he came to fight dictatorship and life presidents! the irony is that the man had become that which he claimed he had spent most of his adult life fighting! For good measure after bribing the 'paesants in suits' that pass for legislators in the talk shop otherwise called parliament to scrap term limits, he even wasted more of our money on a referendum that was so poorly attended its results should be struck off the record. Apparently many Ugandans didn't see the point and I dont either. The limits had already been scrapped anyway and the question of transitioning to multipartioes should never have been asked because Ugandans always assumed and had been promised that the movement system was transitional and no permanent!

A few other things were thrown in in random order -professionalising the army, getting rid of kony, UPE bonna basiluwaale, microfinance -bonna baavuwaale, USE -bonna basiluwaalile ddaala ddaala and 'due to popular demand'. Finally he threw aside all pretence and went for the tired and rather insulting line of 'he being the only one with a vision' and no one else can govern Uganda' and only he can 'look after the newly found oil' read preside over its theft if one were to go by the record of theft of public entreprises in the last 25 years!

Am sure you now get the point -the man doesn't and in retrospect never ever had any intention of stepping down or handing over power! Now he will only hand over to the 'right people' presumably his son! I lose track of the reasons that Museveni now uses to keep himself in power! The cynics even suggest that he staged the 'Al Shabab bombings" in order to keep himself relevant through fear in the locals and vested interests of the US which has no problem supporting dictator if it keeps war away from their shores! I disagreed on the Kampala bombings being the work of Museveni https://www.facebook.com/note.php?note_id=424513927680 just like I do on his troops being in Libya https://www.facebook.com/note.php?note_id=10150103956052681&id=620617398

It is ironical that "Les vainqueurs prennent immédiatement les vices des vaincus. (Victors immediately take on the vices of the vanquished)" Jean Barois. Museveni has taken on the vices of the people he vanquished. From being considered to be part of a 'new breed of rulers in Africa", it is not uncommon for him to be referred to as a dictator, a despot, a tyrant and even a murderer. This last one I always had trouble accepting until the killing of 30 or more Ugandans during the so called Buganda riots last year! if there was ever any doubt in my mind that Museveni had no problem with killing Ugandans in order to keep himself in power if they disagreed with him, they were dispelled. i have no doubt that had Ugandans gone to the streets, we would be making bigger headlines than Libya. Unfortunately the blood of innocents will always be avenged. the more innocents die, the more likely it is that the man who ordered their deaths will himself suffer a similar fate!

Is Uganda ready for another people's revolution -my answer is yes. Is it going to happen now -maybe. Is this election going to be the trigger -no. Is it possible that something else could be the trigger -yes. Is facebook going to be the catalyst -probably though this was already started by FM stations which is why Nambooze and CBS became public enemy number one! With FM stations and so called 'bimeeza' the government did not control the flow of information -the the media centre and the crackdown on CBS and control of the content of FM stations! Of course the official reason is different -mbu inciting genocide! The ubiquity of cheap mobile phones, mobile broadband internet and FB and twitter on phones will be a possible catalyst.

Should what i previously called the 'iphone generation' now called the FB generation https://www.facebook.com/note.php?note_id=433157782680play a role in this debate -the answer is yes. Do they have the power to bring down the government -probably not but they do have a right to participate and many actually have useful opinions and skills honed by exposure!

So if I were in the NRM, I would grow eyes in the back of my head! And I would not trust those hungry soldiers to protect me against the angry masses when they come banging on the door! I would concentrate on fixing the problem before it is too late and whether you like it or not, Museveni is a part of the problem if not the problem!

All members of the NRM should be saying to Museveni "No extension, no resetting the clock, no inheritance" if they want their party to survive into the future! This video of an eight year old Egyptian girl should also be required viewing for all those in the movement. http://www.youtube.com/watch?v=_EnxQ5FJozE
