# We need term limits back

Saturday, May 14, 2011 at 8:22pm


Dear Nina,  
   
I can see that you remain loyal to daddy and his master Museveni and hope that you can prempt their inevitable demise. I must say that you are on to a losing battle. The NRM has for long perfected the art of corrupting dissenters. they didnt always beat them up like they did Uncle Besi owamaaso. The bought them, gave them commissions of inquiry whose results would never be published, sent them overseas on scholarship or posted them to obscure embassies. if you doubt me wait for the cabinet list next week. As you know it is silly season with every politician begging and blackmailing to get onto that list. If you really seek change in the NRM, and are not wobbly, you are going to have to sing from outside. i told you Buddha only got real enlightenment when he left the palace and walked among real people in the city streets.  
   
Its true that many of us from the Museveni generation had great hope in the NRM. You will be surprised to know that most of those on the internet speaking out against Museveni are his children born or brought up in the NRM be it in Kampala or Gulu. Those who saw violence under his watch in the north may express their rage but it is the same rage that abused children express towards an abusive father while those who were supposed to just be happy because daddy is in charge are not happy because they are now adults and can see that daddy was never perfect even if he may have appeared to be so when they were children. That he is slipping, he has lost his touch and is getting senile.  
   
I  formed the opinion a long time ago that it was impossible to change the NRM from within. As an organisation it took on a life of its own. Paranoid. Rejecting anything that did not fit the official narrative. The body whose only role is to serve its head Museveni.  
   
No one has expressed a clear disagreement with the NRM and stayed. And those who have stayed have become choir members. The body is there only to feed the head. If any part of the body takes on a life of its own, like a cancer it is rejected and cut out and thrown away. The only thing that protects Nina is who she is. even then there are petitions.  
   
Until I see a clear challenge within the NRM for the party presidency not the orchestration that we have become accustomed to, I do not see any evidence that the NRM is independent of Museveni. Museveni is the NRM and the NRM is Museveni. In its current form without internal reform, it will die once he dies and in desperation they will have to seek another of his blood in an attempt at keeping it alive.  
   
We have been bashing the opposition but the reality is that the weaknesses within the opposition can themselves be blamed on Museveni and the NRM. On principle I believe that for the country to be governed with accountability, we have got to have a strong opposition.  
   
Museveni cannot claim to believe in democracy when he treats his opposition like dirt. When he allows the lowliest of his minions to bash and humiliate senior members of the opposition just days before his innauguration yet claims they were invited, does he really expect them to attend?  
   
Museveni is a true herdsman. In a kraal there can only be one alpha male. But that form of government is a monarchy. In a democracy there are other power centres. Parliament. The judiciary. The speaker. The chief justice. Civil society. Each independent of the other, all working together towards a common goal.  
   
It is the role of the opposition to critque the government and its policies. To question them. To demand accountability. Museveni constrains that role. He has come to believe that to question him is kamanyiro. Its to cause dissent and riots. He believes in controlling the flow of information. All news is supposed to be president Museveni yagambye. That is so old hat. even when children grow up while they may respect their parents as they should, they no longer believe that their parents are the fountain of all wisdom.  
   
There is little evidence of the much touted collective responsibility of the NRM apart from show for the cameras. What Museveni wants, Museveni gets. And no one will stand in his way.  
   
When term limits were removed, that was the biggest mistake Ugandans made. When idots like Kakooza are allowed to even suggest that term durations will now be tampered with to prolong term limits from five to seven or even ten years, one sees the hand of Museveni. For in 25 years there has been no evidence at all that Museveni wishes to relinquish power. I am very sure that short of pressure on Museveni, come 2016, Ugandans will be going through the same problem of one old man who believes that the country is forever beholden to him and his band of 27 trouble causers.For this alone Besigye deserves to be declared a national hero but I will not hold my breath. In a way his brutal treatment has served to temporarily gloss over the big problems with our opposition that i will not go into today. But if they can avoid tripping over their ego's its possible that we could finally have an opposition worthy of the name. Museveni has no intention of giving power to ugandans so it will have to be taken from him, just like it was this week.  
   
NRM members with a conscience owe it to Ugandans to reinstate term limits. It should be the first duty of the 9th parliament to discuss imposing term limits and if necessary going to a referendum. We cannot rely on an unprincipled parliament such as the one that passed the Kabaka muzzling bill or accepted 20 million shillings with unclear TOR's to make this decision for Ugandans.  
   
It is no coincidence that in South Africa Nelson Mandela set the pace by stepping down after his first term. With his history, and the ANC dominance of South African politics, he could have easily have stayed on till he was completely senile.  
   
In America George Washington set the tenor by refusing to stand for a thrid term. He even had to be persuaded to stand for a second. The confederate states set their term limits at 6 years. President Roosevelt served for 4 terms dying shortly after his election for a 4th term. This led to an amendment formalising the term limits to two terms.  
   
Museveni and the NRM were given virtual carte blanche in Uganda. The constitution making exercise restored confidence in government. Until Museveni and his colleagues raped Ugandans of their rights by amending a limit imposed by the whole country by horse trading among themselves for a mere 2000 coins of silver.  
   
The events of the last few weeks demonstrate more the weakness of Museveni and his government than the strength of the opposition. It also demonstrates the strength and resilience of Ugandans. The willingness of Besigye to be a lightning rod for Museveni's anger at being defied and humiliated despite his military strength and monopoly on instruments of pain and death has brought Ugandans together.  
   
It has for so long been believed that power in Uganda lies in the gun. Despite evidence to the contrary in the many displays of the traditional leaders like Kabaka Mutebi whose ability to command a crowd is unrivalled, or the child king of Toro who had adults trecking miles to bow obeissance to a baby in nappies or those who go to the Omukama of Bunyoro's palace. This power coalesced unbid into the so called Buganda riots when at the command of President Museveni his troops rioted killing 30 people and injuring scores more. Further defiance at Kasubi caused the further death of 3 people but even then, Baganda defied him to stage a day of mourning that ground budiness down to halt declaring an unofficial public holiday. All of these are the events that have led to where we are now. from here on Museveni will have to force his will by shooting people. And shooting people will bring him closer and closer to the ignominous end of his predecessors and he will forever be a hunted man.  
   
The only recourse is to hand power back to the people. this is the only exit plan that makes sense. Museveni may try to go back to his old tricks of buying out enemies. He will offer minsitries to members of the opposition. Maleable people who are for sale to the highest bidder like Nasser. But this will only result in a bloated innefficient government that will be a further burden on Ugandan taxpayers.  
   
Ugandans are already fed up with the wastage of their money on fools errands they were not consulted upon. Granted security is important but so is health. Baganda say that he who does not have teeth does not buy boned meat. Why did we have to buy fighter jets with capabilities that make them expensive toys? Capabilities we are not likely to need in the near future unless we anticipate going to war and getting anihilated by South Africa or Egypt?  
   
Do we need a man who has made his lifes work war since his students days in the 60′s to continue send our children into senseless wars we do not believe in nor benefit from? the attempt to link the purchase of fighter jets to oil is even more alarming. Is this how our oil money is going to be managed? By spending it on modern baubles and glass beads before we even get any oil out of the ground let alone sell it?  
   
The NRM has got to stand up and be counted. Those who joined the NRM because they wanted Uganda to be a better place need to show their hands. Those within the NRM have got to show their dissent. The debate on museveni's future is a national issue that will determine whether hand over of power to a future leader will be peaceful or will involve war. This is not something to be left to Museveni alone for he has shown himself incapable of being objective in his quest for power. Hiding behind collective responsibility will not hide the fact that thosein the NRM are cowards who have sold our country. They have got to understand that we are on the brink of war and their actions will bring it upon us.  
   
The events of the next few weeks will be interesting. People will continue to walk to work without permits. The best way of dealing with the problem ironically is to let them walk. To call the dogs of war back to the barracks. To recall the IGP back to the barracks and send him off to some obscure staff college where hopefully they teach about crowd psychology and crowd control as well as community policing. That is of course if he really fancies himself a policeman. And please do not send him to Somalia as that will only attract more bombs to Kampala if he deals with somali dissent the same way he deals with Ugandan protestors.  
   
Since you insist on staying inside the kintu, convey the message to the eaters within that people want term limits back and will judge them if they cannot stand up to Museveni.
