# Never kick a man already on the ground!!!

Monday, August 15, 2011 at 11:20pm


Nina dearest,

Today I feel great love for you and I do not care who is listening! Whether its your computer whizz kids and script kiddies from the NRM "election monitoring" centre, daddy's boys from his security minster days or Uncle Kags half brained intelligence goons, I do not care! Didnt you use to run that electronic election monitoring group? I remember Uncle Kags giving you recognition for a job well done! I hear that your bu boys had mastered the art of "monitoring" and playing with everything to do with elections! Mbu they understood Kiggundu's electoral commission computers and software better than he himself did!!! Are you sure they didnt tamper with the data? Ye what did you do with them? Did you disband them or are they deployed elsewhere?

I predicted that your NRM guys were going to have a pyrrhic victory as they were dead set on winning but there victory would be very short lived! Having watched the last few months, I can say for sure that I am a seer, and the NRM are suckers!!! If thi were not my country, I would be laughing but the situation in Uganda is not a laughing matter!To watch your people staggering from one crisis to another like a drunkard in a drunken haze is sad and demoralising! One feels obliged to put you guys out of your misery! You know I always pitied obama for winning the American presidency when he did for he walked into a time bomb set to detonate! Can you imagine taking over after ten years of George Bush bumbling around the white house? Me if i were him, I would have givent their presidency back to them! Now the guy copes the blame for all of the blunders made by his predecessor! And the Republicans in their short sighted tea wasted brains take it out on him each day!

The beauty about Uganda though is that the guys who made the mess we are in now are still there for target practice!!! With each day, as the pile of cards over which they have presided for a quarter century begins to unravel, one gets a sense of mob justice! Please do not be shocked -like you do not live in Uganda! Mob justice is the order of the day!!! Certainly if chicken thieves are beaten to death everyday how about the political thieves in parliament, cabinet and t all levels of local government!

The economy is collapsing! But what did you guys expect when you were spending money like it was going out of fashion! President Kaguta with the connivance of those dishonourable MP's was handing out brown envelopes to all and sundry in exchange for a vote for the man in the hat! In your economic classes at Nottngham, am sure they taught about the effects of dumping cash into the economy! They then went on a spending spree like there was no tomorrow! Bright new fancy toys the modern equivalent of the beads and mirrors the olden chiefs sold their people for were soon bought at the expense of our national reserves!!!

NAye ekuba omunaku tekya! That shortsighted stop gap thermal electricity generation scheme also fell apart. I received a scoop in my inbox of the confidential Saleh report on UMEME that makes some very interesting reading! I intend to share some of the details with you in a short while after I have digested them!!! Kale absajja babye ssente! Naye as my grandmother used to say, God bless her soul, zijja balakira!!!

This was on the back of that incompetent police force that decided to riot and destroy property and peoples lives! They were at it again a few days ago in Masaka! I wonder what the IQ cut off is for recruitment into the police! Dont they learn from their mistakes? If you confront a peaceful demonstration with force and violence, you create a riot! Do you think you can ask daddy to call that Kayihura fellow and drum it into his head?

Naye banange, mubonyabonya banUganda naye the policemen! Hah! Those one you treat like subhumans! Have you ever seen where the policemen and their broods live? Even if it were me! i would come out of those mama ingia pole very angry with the world and take it out on everyone who appears to be enjoying better than me! And trust me at 160,000 Ushs that you py them to catch the flies with their tongues or be eaten by mosquitoes while you guys are warming yourselves up inside, its a wonder they do not turn their guns on you! Talking about security officers, I hear mbu you guys steal from those other poor men in uniform dying in Somalia in a war they do not understand fighting for people who hate them and for a government without universal appeal! Its actually said that the TFG controls only a few blocks of Mogadishu. I hear, your guys mistook a tactical withdrawal for a victory! Maye obusajja mubuwe ssente zabwo!

Then there are those others in Kampala trying to make money off a bad situation! Mbu they briefed minister Muruli Mukasa that there were Ugandan terrorists on FB masquerading as activists!

The word terrorist is so devalued, any self respecting terrorist would feel insulted if he was referred to as a terrorist by a Ugandan government functionary! Quite frankly, am sure none of the members of this government from the president downwards has any idea what it really means!!!

Then they produced a nonsensical report about a poo demonstration! Quite frankly where do you guys recruit these bu guys from! i hope you do not take their intelligence reports seriously!!! But apparently you do as today significant resources have been deployed to prevent Besigye from pooing at City square!!! Mbu he woke up today surrounded and has been followed around all day! Banange ssente yomusiru!!!

Then everyone wanted to demonstrate what Museveni and his men call rioting! Do your guys have dictionaries? Could they use them to differentiate between a riot and a demonstration! Rioting is what those little spoilt brats in the UK were doing last week! Demonstrating is what Ugandans try to do until your police goons start to riot!

Naye kakati twogere ku sukali! Who exactly advises Uncle Kaguta? IS this really the best time to bring up Mabira or are they looking for more excuses to kill more Ugandans? Mabira was the first issue that Ugandans stood upto Museveni's bullying on! Those Mehta guys are looking for something too! Am sure they will get what it is they are looking for if they continue to pursue this! The ridiculousness of trying to blame the rise in sugar prices on a lack of adequate acreage is appaling! Who do they think they are fooling?

For months its obvious this government is floundering like a fish pulled out of water! They are totally confused and in disarray! Did you see that interesting uncoordinated troop movement on sugar as well as the traders (KACITA) strike? The trade minster has no idea what is going on! Talking about communication, that woman Kabakumba, who couldnt manage one ka little ministry of information now has several more 'fortpolios' given to her! Talk about rewarding incompetence!

I told you daddy dear was set up! But please tell him to watch his back! If he doubts me, he should watch what is happening to his former rival and boss Bukenya! The other day those unkind journalists snapped poor Bukenya bending over and kissing daddy's hand! Not only were they content with sacking the poor guy, but they are proceeding to destroy him and any future political prospects he may have! With a criminal conviction spent or pardoned, he will be ineligible to stand for president come 2016 even if he could marshal the numbers!!! That to me appears to be the main strategy behind this ongoing prosecution! It appears that the man was right when he alluded to a mafia out to get him! Imagine all of his brothers in crime have been declared innocent before trial and are not even being charged!

My grandmother told me that "bwomega toluma" -when you throw your opponent, its bad sportsmanship to bite them as well! Not only are they kicking poor Bukenya while he is on the ground, but they are kicking him in the nuts too!!!

As you lay your bed, so shall you sleep in it! You guys need to learn to treat others as you would have others treat you! After that humiliation and brutality against Besigye and the vindictive selective prosecution against Balibaseka, I fear for you! You should feather your nests overseas!!!
