# Learning to share the loot!^[https://www.facebook.com/note.php?note_id=10150093030667681]

https://www.facebook.com/profile.php?id=620617398)

Wednesday, February 2, 2011 at 8:54pm


Dear Nina,

I am not sure what motivated your posts today but I believe that we are well on the way to speaking the same language!

This is not about Museveni! My main problem with Uganda's immature opposition is their focus on Museveni alone as ...an individual even when they have no alternate plans at all on how they will govern Uganda better! Many cannot even produce a statement on government policy such as the budget!

That said, Besigye has as much right to aspire to be president as Museveni. And so does every other member of the opposition! no man has got the right to treat a country like his private property! those who fought have us to thank for their success in their war! my own father who never handled a gun, at great risk to himself bought and sent drugs to the NRM while they were in the bush at the request of his cousins who were both fighters in the NRA. i doubt that this is recorded anywhere in the NRA records. For this he could have died and his family with him. He was only one of many Ugandans who protected Museveni and his men with their own lives even when they themselves did not handle any guns! So this business of monopolising our war and limiting it to some mythical 27 men is fraud! this was our war! We own it. it was not Museveni's war! In many ways it was buganda's war and he was only a mercenary!

When we criticise the government we are specifically pointing out its failures! This is called constructive criticism! It used to be a catchword of the NRM before they became decadent!

I have never called for Museveni to be killed, or even evicted in a war! I have called for him to retire and go look after his birds and goats and hand back our property! this is not his country and it should no be treated like private property for him to rule for life while setting us up for hereditary rule!

I have also cautioned about the Tsunami that is coming Museveni's way should he refuse to step aside. The NRM itself needs to get serious and jump out of one mans dream! Other reasons aside which i will not go into today, why can't your father lead the NRM? Why can't Joanita's? Or any of the other members of the NRM?

the Jasmine train has unmasked a basic human yearning for some control in their own political destiny. It has demonstrated that it is not natural for people in this modern world to continue to be ruled by the same man till his death while clearing the way for his own offspring to take over. It has demonstrated that given the option, people want tired old autocrats enlightened or not out of office and they will risk bullets if necessary to see them go!

Your people keep telling us about elections and how Museveni will win this election! Well North Africa has demonstrated that this means nothing! In some professions there is such a thing as informed consent! informed consent implies that the person making a decision has got the capacity to make that decision! its a central principle of ethics.

You and I can debate just how informed the masses in Uganda are. We could also debate the merits and demerits of people deciding who to vote on the basis of information available to them. We have demonstrated here time and time again that information provided to ugandans by this government is flawed and many times doctored and fraudulent. that the fats if explained clearly to the paesant would so enrage them that Museveni would be out tomorrow! Case in point -our Mulago debate or that on health centres the figures for which keep getting trotted out even by the president himself yet his own minister for health admitted only 38% were staffed and most didnt even have the basic drugs required!

If you keep smoking whatever it is you smoked today, we are going to get on like a house on fire! I wish you could share some of it with Alice Rubindi for she is so out of touch with the common man in Uganda its painful to read her posts!

PS -this is as close as you are going to get to a compliment!See More
 

[http://www.facebook.com/note.php?created&&note_id=10150093024492681](http://www.facebook.com/note.php?created&&note_id=10150093024492681)
