# Museveni's rioting soldiers and policemen

Tuesday, May 3, 2011 at 3:27pm  


Nina, 

Writing you letters is becoming a habit! At this rate am about to claim that am a seer like Pastor Kayanja or that other guy (or is it a woman) that Timothy Kalyegira talks to! I need to talk about that man of God (or is he?) another day. At least my predictions do come true unlike his! Kayanja is MIA! I wonder whether he would like to give us some new fake predictions! I know that the pentecostals would like to be recognised up there side by side with the Catholics, Protestants, Orthodox and Muslims in Uganda but do they have to be ensconced so far up uncle Kags bottom just so they can be recognised? What happened to separation of the church and the state?  
   
Now they are the recruiting agency for the government through Pastor Natasha and her mother or is it the other daughter! i hear Kayikura and Arinaitwe were recruited by the pastors and vetted by the first lady to confirm they were saved. But judging by Arinaitwe's recent performance as well as the circumstances in which Kayihura's saved boys with guns brigade the SRPS was wound down for torture nad humnan rights abuses including deatsh in custody as murders by security services are euphemistically called, the saved formula doesnt work. And this is before we go into those allegations of pederasty against the man of God or those of smuggling truckloads of wine!  
   
But I digress. My prediction in my last letter to you was that it wouldn't take very long before the lawyers and journos linked up against Uncle Kags bully boy tactics. within hours of my saying so, a magistrate decided she wasn't going to be used any longer in the rape of the courts. Another threw out the case against Mao, and you now have the lawyers on a 3 days strike ironically in support of the people you chose to call criminals! Didnt I say that the lawyers and journalists wouldnt take long before joining the fray collectively? Now the newspapers report that they have joined the fray. See what your village idiots have done! They have united the lawyers and the journalists against your government. Am starting to suspect that your people in the police and army are working for the opposition and trying to make you guys look bad!  
   
I wonder when those lazy workers MP's like Lyomoki and his friends are going to come out and walk with the people they claim to represent. For twenty years they have been sitting in the rubberstamp parliament collecting allowances and getting fat! i think its time they now came out and spoke on behalf of the people they are paid to represent! At this rate I can see teachers walking in solidarity with those other teachers you tear gassed and their pupils. Taxi drivers are about to walk in protest too since you guys are now interfereing with their livelihoods. People no longer want to travel and stay in their homes. I can see all sorts of other professions joining the fray. You know my mother chose to retire from the civil service during Idi Amin because she could not stand having to go through an army check everytime she went to work. She worked in one of those sensitive government offices. I can therefore understand why Ugandans may chose to stay at home and hate you for having unleashed the dogs of war onto the streets. You know the police and army had started to shed the name "basirukaale" but the last 2 or 3 weeks are quite rapidly undoing that!  
   
This is going to make for a very interesting swearing in! Uncle Kags or is it Sevo these days may end up getting sworn in like Kibaki -like a thief in the night! I wonder how your people will be able to account for the billions they stole from our taxes if all of those 32 heads of state stay away! You know thats a very distinct possibility! My intuition tells me that those videos of your goons in action compounded by the village idiots you chose to speak for the government are right now causing problems in many state houses around the world. For sure Uncle Bob maybe able to come. He doesnt get to get out much these days to inspect a guard of honour and stretch his very old bones. As you are aware he is very arthritic including in his extra bone -you know the one that women don't have. I hear his missus when she is not shopping in Singapore, has been examining the funny bones of other men younger than Uncle Bob! For many other heads of state whose governments are accountable to the people and sensitive to criticism and negative publicity, those images are going to keep them away!  
   
I gather now you guys have a new tactic -if the people wont walk2work without a permit so that your goons can exercise their neanderthal reflexes to crack some heads, they are now lobbing tear gas into their homes so that they can be forced outside and frogmatched to town! That kid of reminds me of all of those villagers your guys rounded up from their gardens in northern Uganda and frog matched them into camps for the next 20 years! I wonder where you will build the camps this time. The protests are everywhere. Gulu, Mbale, Masaka, every surburb of Kampala, Jinja, Mbarara and rukungiri. The strange thing is that you guys have always claimed to win with 90% majorities in these last two towns. Who was that guy who rounded people up in the north? Tinye? I hear he rounded up some balaalo in Buliisa as well who thought they could squat over some few million barrels of oil and claim royalties! is he also involved in this operation?  
   
If ever there was evidence that your people are tired and don't have any new ideas, it is this crisis. All that your goons understand is kill, beat, crush, eat like a samosa! What violence? Did your mama's deny you breasts or what? Why can't your people think of anything else other than fight and kill. I hear your uncle Kaguta wears his ability to kill like a badge of honour. When told he has been fighting for 25 years he gets insulted and reminds all that he has actually been killing for 45 years! I wonder what makes him think that people have got to keep dying for him so that he can continue remaining in power indefinitely.  
   
Yesterday I had a brain wave. Must have been the excitement of writing to you -are you married? It suddenly occurred to me that Museveni is now a "life president by stealth". Am not sure what it was that I was smoking but I sure need to try it again. Am getting confused -couldn't have been smoking anything as I dont smoke at all. Couldn't have been drinking anything either as the strongest drink I take is coffee just like Uncle Kags! must have been someone walking past and blowing smoke my way! boy tha was some pretty good stuff if it suddenly made me creative! You see am not creative -I remember you trying to tell me exactly how I was a nobody! this stuff could change that as I may even copyright that statement as I surely haven't seen it before in print. Wouldn't you agree?  
   
That Museveni who lost an election miserably in 1980 level field or not is the one who felt aggrieved enough to wand to start a destructive war? I hear that even in his own constituency, he lost miserably! That he successfully wrestled the animal from the swine and then "reluctantly" as was his claim in 1986 agreed to be president for 5 years but has since then repeatedly kept shifting the goal posts just so that he can remain in power suggests that he has stealthily become a life president! But don't take my word for it. I looked it up and apparently anthropologists allot a duration of 25 years to ancient an ancient kings reign or era. As a matter of fact one can roughly estimate how old Buganda is by multiplying the number of kabaka's by 25 in this case 36 kings each ruling for 25 years makes Buganda approximately 900 years. So Museveni is a king -one who has already ruled for an era! But he wants to go on! Is that greed or what? He even thinks its worthwhile for people to get killed so he can continue to rule!    
   
If ever one needed evidence that your NRM people are unsuited to leading our country into a modern world, it is their failure to do battle in a modern world with modern tools like keyboards, social media, and boots on the ground chanting keep walking! They have exercised all of the wrong reflexes since this started a couple of weeks ago. Mistake after mistake!  
   
You know I have a soft spot for you even though you hate my guts! So I will give you some free advice to pass on to the strong men of the NRA. This here thing is going to end badly if they continue posturing and bullying. They are going to either have to get rid of the tired old man in a hat or to prevail on him to sit down and talk. And when I say talk, I dont mean talk in the condenscending manner he is used to. Talk with respect looking for a mutual solution to this problem and most of all looking for a way of healing our communities.  But I can guarantee that the stickler is going to be term limits. And some people are going to have to commit seppuku -like kivedhinda. its time he retired anyway. And that soldier masquerading as a policeman, he will have to go back to the barracks and get redeployed. You are also going to need some people with real conflict resolution credentials and am not talking about that thug in NAirobi who was previously the spokesman for the LRA. I know that he is attractive to you guys as you love people you can buy!  
   
You can of course ignore me but you know by now that am a seer -there I just said it! How long do you think it will take before the traders in Kampala decide they are tired of having police and soldiers rioting in the city and messing up their business.  
   
You am sure notice that i have deliberately used the term rioters to describe the so called government security agents in the city. They have been rioting since before the 18th, making people uncomfortable in the city and disrupting business. I wonder how much money has been lost since they were released from their mama ingia pole's in the barracks! These guys are going to bring the economy down! I wonder how you trust people who are so poor to guard you and your healthy looking wives and children. Me, I wouldn't trust them at all!I was starting to think that I was the only one who had noticed that Museveni's soldiers and the police were rioting and destroying the peace and people's property in Kampala.I almost even thought of copyrighting that too -you know "Museveni's soldiers on a riot"! But I found that Dr Ian Clark beat me to that. "Although it is the duty of the Police to keep civil order and prevent, or control rioting, one wonders, as they watch television and read newspapers, if these are anti-riot Police or rioting Police." -- Dr. Ian Clarke (Mayor-Elect, Makindye division). Prof Jjuuko also thinks that your soldiers are on riot. "What we have experienced since the start of the Walk-to-Work campaign are police riots. It's like the police are telling the people 'if you cannot riot then we will riot'," says Prof. Jjuuko.  
   
The old man in the hat is tired! I wonder how he will be when his MP's join the walkers like some have already started doing at least in their comments, his cabinet starts splitting as you know its now blackmail season. Those he was planning to drop have suddenly received a shot of viagra and will be blackmailing him while the army may have to do a Mubarak on him.  
   
Its time to make exit plans!
