# Patriotism and national guidance preached by dishonourble women!^[https://www.facebook.com/profile.php?id=620617398]

Thursday, June 16, 2011 at 12:16am


Dear Nina,

Akabulilililo!

I can understand why you have decided to hide from me but you know you can run but you cannot hide. I will still get you particularly given your people are making it so easy!!!

There are times when a man does not know whether to laugh or cry! The NRM government has brought us to one of those times! At times like these I wonder what makes you guys in the NRM believe that you are better than Ssebagala. Or the lumpens, the dregs of society that your praise singer Nagenda was talking about!

Talking about praise singers, today we have got to talk about that other praise singer Mary Karoro Okurut and her friend in crime Margaret Muhanga! Who said that women are to be outdone when it comes to misusing thei offices to steal public resources to enrich themselves? I have heard some say that the appointment of women to this cabinet would be a blessing as coruption maybe less! These two women have proven that that simplistic argument simply will not get ri of corruption!

This word coruption is so misused as to become useless. I am starting to believe that it must have been coined by a paid wordsmith like Karoro! Surely isn't thief a better word? For that one has no ambiguity at all! If one takes what does not belong to them under false pretences, thief is one of a few choice words that come to mind!

Mbu I hear Margaret Muhanga told people on the airwaves that the land they stole from UBC under false pretences was aquired "legally"!! Surely the very fact that the same land was put on themarket 4day after it was acquired has got to be a false pretence that should invalidate the whole transaction! The fact that the purchase fee of over 900 million was not paid as well should have invalidated the deal as it was meant to be paid upfront! I wonder what her brother Mwenda is going to say!!! Me I would stay out of that one if I were him!

I do remember another similar scandal many years ago where public land has been stolen through false pretences with some middle man who obtained it free walking out with millions. it is the latest NRM scam! Actually many scandals ome to mind. Did you know about Shimoni? The school was "allocated" free to "build a CHOGM hotel that never ever happened. The recipient went off laughing to the bank -with millions in the bank! UBC too lost land again to another CHOGM hotel that never happened. In that scam a firm contracted to move the archives also got freemoney with valuable archives destroyed. In yet another land scam, Butabika hospital lost acres of its land -for "industrialisation"! But this land ended up in the portfolios of individual NRM politicians and members of the first family instead! Please do tell me you never got a piece of that scam too! You would be the only one it appears who did not partake of that daylight robbery!

More recently that NRM bigwig Basajabalaba, who has turned scandalous controversy into an art has also been caught for the umpteenth time with his hand in the till -again land! The fact that he is a chairman of one of the NRM party organs and a major donor to the NRM party does raise issues of money laundering. Could it perchance be that you guys siphon off state funds to collaborators in these shady deals who then return the "gratitude" in donations to the party? This is one of those times when I despair at those men and women of the opposition! That something as obvious as the source of the NRM party and election funding is not the subject of court action to reveal its source is a surprise! But then again they have failed to react to the budget!

Speaking about the budget, Emmanuel tumusiime-Mutebile finally rediscovered his Kiga roots and grew some cojonnes. He had some home truths to say to his boss through the Financial Times. Methinks he should have stood up to be counted a long time ago! I was starting to believe that he was not a mukiga!!! Quite frankly I was not surprised for it has always been obvious that this government does not have a clue what they are doing! Can you imagine that after going to the UK begging hat in hand and receiving 0 million pounds, Museveni went on a shopping spree? He spent 30 million on a new state of the art plane that same year! Didnt help poor Mayombo though even though he was offered its services as an ambulance to airlift him to Israel! this year we are hoping to see some oil come out of the ground. But before weeven see a cent, this government spent our money on planes we cannot afford for reasons that are too vague! Earlier in the year, the presidents re election campaign was funded with state funds to the point of driving inflation up a few points and causing a crisis! While Mutebile is still talking I would like to hear him tell us that Basajabalaba paid back all of the free money that was gifted to him!

I ont get this government! For 25 years they have presided over a dark nation without electricity yet they sing industrialisation! One wonders how they are going to deliver! What exactly do they think powers factories? I am yet to go through the budget with a fine tooth comb but save for a mention of a mega dam which Mutebile objects to, I se no strategy for power generation that is sustainable and environmentally friendly! there is no strategy for energy saving, none for alternative energy sources and little education of the public on energy saving devices and strategies. There is litle involvement of local communities in using new technologies at small scale and community level!

I know that Ugandan men love to have schools of children but what is this obsession with a large, poor, and unemployed population with no skills and no education! What passes for an education in UPE schools is quite frankly pathetic! President Museveni keeps telling people that a big population is good as they will create markets! I know you went to Nottingham and studied Economics! Could you please whisper to him that a poor people cannot create a market as they do not have purchasing power! While you are on the subject, please tell him too that factories need people with skills not glorified degrees from amngo tree university not worth the paper they are printed on! Have you ever built a house in Uganda? Quite frankly the idiots who pass themselves off as tradesmen should be shot. Most are hustlers who cannot recognise a straight line if it were right in front of them! No wonder all those monstrocities built with stolen money look crooked! How many vocational schools and technical colleges have been built in this government? When the EA free market opens up, Kenyans will be best placed to take advantage of the larger markets. Ditto for industrialisation. Not only is their work ethic different but they also have the requiste certificates and diplomas while Ugandans have degrees not matched by commensurate skills! 

A young man reminded me today in his Letter to Drew, that many of our well poken and qualified leaders are no better than Sebagala. He was not impressed by the condemnation of Sebagala for his pidgin English! He believes that his skills at "eating on behalf" of Nagenda's lumpens, rats and cockroaches and dregs of society should have been the criteria and not his English! [http://weeklytouch.webnode.com/news/letter-to-drew/](http://weeklytouch.webnode.com/news/letter-to-drew/)

Personally I wouldnt give a a stuffing if he did not speak a word of English but was a fine gentleman of good morals and standing! Furthermore his non performance if one could even use that word performance in the same sentence as Sebagala to describe his wasted years as mayor of Kampala, should disqualify him from ever having the word leader and Sebagala in the same sentence! Even the seya's gave up on him and he had to sell his tired behind to the highest and most desperate bidder! Bottomline is Sebagala is not fit to be a minster een if his English were impeccable. But Karoro the word smith with the impeccable English is not fit either following this recent scandal and should resign or get pushed! Am not holding my breath though!

Could you explain to me what a poltical statement is? Your people went to a lot of trouble using our money of course bribing the MP's to pass the fault ridden kabaka muzzling bill! Mbu cultural leaders should not make political statements at the risk of imprisonment and being derobed! But in thelast few months we have had the Queen mothe of Toro go around openly making political statements in favour of the king of kings Ghadafi! This week he was joined by the Omukama of Bunyoro! That Makubuya fellow will have to come back and tell us more about this political statement thing!

When one is starting to forget those chaps in the opposition, you guy conpire to raise their profile again! The guyshad slowed down an started to fight among themselves. Now lightning rod Besigye is back and waving the red flag and your are responding so predictably! Mbu he cannot walk back from the court to his home!!! I was going to use the word retard to describe your people in government and the police, then I remembered its not so politically correct! No wonder after 25 years, it obvious that it is too hard to teach people with learning disabilities anything! These guys simply do not get it -that they have failed and a few more years can only prove just how incompetent they are! Why can't people retire when they are ahead?

Can anyone in the NRM recgnise a conflict of interest if it fell on their heads? Now this Karoro woman of the "mbwa zirime" fame! You know my grandmothr used to say that small lies became big lies and soon one became a 'kondo', robbing people before ending up in jail or killed by a mob!

But Karoro and Muhanga will not end up in jail! Having lost out in the election, I wouldnt be surprised if Margaret was proposed by this government for an ambassadorship. Irent those reserved for political rejects after they have ost elections? As for Karoro, me am still waiting for her to apologise for that lie she told about Mbwa zirume which was meant to incite sectarianism and hatred. You see while this government sings sectarianism, some people are allowed to get away with it. And while it preaches a war against corruption, for 25 years that has remained invisible!

For Karoro and Muhanga to receive government land for investment but then pass it on for a profit without paying the government is fraudulent. Other words come to mind -influence peddling being one! Impunity being another! The ladies did not receive tha land "legally"! They breached the terms within 4 days of reciving it when they put it on the marked and failed to pay for it as per thir contract!

Now who is going to collect our money? And will Museveni disown these two women and sack the second one from the "national guidance ministry"? You can imagine the irony with which I say national guidance!!! I assume "patriotism" falls under that ministry too -LOL!

[https://www.facebook.com/note.php?saved&&note_id=10150219911037681](https://www.facebook.com/note.php?saved&&note_id=10150219911037681)
