# The lunatics are in charge of the asylum.

Saturday, April 30, 2011 at 1:50pm

   
Dear Nina,

When people are appointed to offices because of technical know who and blind loyalty to put their behind behind the president, you get incompetents who walk into traps and react with predictable consequences.

   
   
The evolution of this whole thing was very predictable. I predicted the way it would unfold and the idiots who make decisions in government exercised their neanderthal reflexes in exactly the way I predicted to produce the [outcome I predicted](http://www.facebook.com/note.php?note_id=10150150846997681).    
   
   
Image is everything. One photo can make or break you and you guys have given your opponents so many you should shoot yourselves in the head. The difference between Mugabe and Museveni is simply marketing. One day can make a difference. Look at the buffoons that speak for this government on FB and in state house.   
   
   
One day, Ghadafi's sons were dining and wining the glitteratti of Europe, the next day, they were hunted men with each having a tomahawk missile with their name engraved on it.  
   
   
The days when Museveni could control the flow of information by imposing a media blackout while panda gari was going on are over. If he is not ready to take the step of becoming a Gbabo or a Ghadafi, its in his best interest to start sorting out an exit strategy both for himself as well as his son and daughters. He really had better be ready to kill lots of people something he should have thought about before he released the dogs of war onto the street.  
   
   
The world has changed. The masters of the business world are teenage and young people in jeans and laptops. Museveni would not recognise them. He is stuck in an old world where brute force is king. Where the threat of violence or actual violence decides conflicts. Where the most violent man wins. He does not have the reflexes to fight this new war. And neither does his son. You were all caught flat footed because you believed that a 68 percent majority insured you against challenge and life would go on as normal. Because you won a big victory, you guys felt invincible. Feel you could get away with anything. You will notice that I say you because you are still a card carrying and active member of the NRM as is your father and many of your family. There is no way that you are going to be able to distance yourself from this short of cutting up your party card and standing with the people.  
   
   
I did say that this was going to be a pyrrhic victory, didnt I? And a pyrrhic victory it is. Yet I have a feeling we are yet to see a lot more.  
   
   
I said before that Besigye and the opposition did not have the power to ignite the masses. I still remain correct. But I also said that there was an increasing radicalisation, an increasing discontent with corruption and prolonged incubence. All that the masses needed to unleash mayhem was a spark and you willfully provided that spark when you so publicly humiliated and beat up Besigye while demonstrating that you were no different to the goons you replaced. This is the sign to the populace to once again clean house.   
   
   
The absolute control that Museveni and the NRM have on the state of patronage that is Uganda whose resources they use to enrich themselves or buy support enrages people who can only watch this greed and impunity.  
   
   
When Besigye started these walks, he cut a lonely figure with a backpack on his back. He would have fizzled out within a week. Do you see all of those substantial ladies walking to work for any period of time Musumba, Mugisha, Maama Mabira? Or their male counterparts in their suits and paunches? I doubt that he would have been able to walk to Najjanankumbi twice a week.   
   
   
But you guys had to send your goons out to rough him up like a common criminal, beat him up, humiliate him, stuff him under the seats of a pickup. You would not even accord him the respect of a political leader, one who had attracted more than 2 million votes and one who was the face of the opposition. You demonstrated absolute contempt of the significant minority that did not vote for you.  
   
   
Democracy that your party president and his lackeys and footmen parrot all of the time, means that while the majority rule, they also undertake to respect and protect the rights of the minority who lost. A government rules with a shadow government from the opposition.  
   
   
The opposition has a role as a critic of government to keep it on the straight and narrow. It is the role of the opposition to highlight the neglect that is leading to high food prices. It is their job to highlight the wastage of public resources as has happened in the lat few months -650 billion to finance Museveni's re election which essentially comprised of handing out brown envelopes using state funds, 6.5 billion to bribe LC's who have never been voted for more than ten years but guarantee the grassroot campaigns, another 6.5 billion to finance the re election of a rubber stamp parliament under the insulting " supervising government programs", 1.7 trillion to buy fancy new and utterly useless fighter jets unless your people are planning to start new wars -I hear one useful idiot on your board who sets himself up as a spokesman for the NRM suggested they be used to fight Al Shabaab.   
   
   
There used to be an idiot in Ethiopia who presided over an arms race in the horn while his people starved and ended up needing emergency Aid from the rest of the world. WHO estimates that less than 2 percent of Ugandan farmers received seeds from the government despite parts of eastern and northern Uganda being at risk of famine. There is abundant evidence that despite warnings, this government has done nothing to cushion its citizens against the risk of starvation and high commodity prices. And then out comes a government idiot stating the obvious -that Uganda is not a welfare state. There is a story from the bible of Joseph in Egypt who having predicted a famine was put in charge of planning for and mitigating the effects of the famine on the population. Thats what governments do. They dont just decide that its not their problem and everyone should fend for themselves while continuing to tax and abuse taxpayers money. A government for the people and by the people empathises with the people. But this government is like aliens just came in from space with no kinship to the people or empathy for their cuffering.  
   
   
Thats is why Walking2Work is so brilliant in its simplicity. Think about it, this was a perfect moment for the middle classes of this country to bond with and show solidarity with the people who have to tighten their belts and walk to work everyday even when their meagre pay is stretching less and less everyday. You am sure watched that stupid video of Musumba walking to work with one lone young man, past people bustling along their day to day lives and then being stopped by a police officer and literally being arrested for walking to work. she had no crowd behind her. Few were paying her any attention -until the police stopped her. Lukyamuzi played hide and seek and walked to work and the world did not end. Otunnu walked to work thanks to the quick thinking of a professional police officer -and the world did not come to an end. Contrast that with the response of the hired goons in police uniforms following orders from above and one sees clearly where to place the blame for the chaos and bloodshed -on the incompetent police and government response. The very confusion with which Kayihura dealt with Mutabazi tells its own story. First he praised him, then he suspended him, then he reinstated him but then transferred him all in the space of less than a week.  
   
   
If this was not so deadly and affecting my country, I would have said pull out the popcorn and dim the lights and lets enjoy some circus baboons perform. But this is not funny. it is sad. those people who died are real people. Am sure rubber bullets cost less than mambas. Do you guys realise just how bad those photos and videos look? Of smoke on the horizon and battle ready troops arayed against an unarmed population? Am sure you would love for them to come with guns so that you could shoot them all. But tehre again is the brilliance of W2W. Guns aren't needed except by fools. And when those fools exercise their trigger happy fingers, they create martyrs. Nothing recruits more for a cause than martyrs and brutality and bullies. All those nasty photos will be in every boardroom  of every country that has business in Uganda who will have to evaluate the cost of their association with thugs. And they have already hit every news outlet. And they are being queried in the white house and int he commonwealth. And Museveni is going to have to answer questions  in Perth whenhe goes to CHOGM and be compared with Mugabe and Ghadafi and Gbabo and Ben ali and Mubarak. Not exactly great company right now.   
   
   
Museveni was meant to be different from the others -the ones he called swine. Unfortunately he is now one of those swine. Ghadafi deployed irregular troops to kill protesters. See how quickly that morphed into a real resistance army complete with a sopisticated airforce that destroyed his fancy hardware before it even left the ground.  
   
   
You guys have already lost the battle for hearts and minds. In the very public beatings and humiliation that was meted out on Besigye, you showed yourselves for what you are. It is obvious that all of the fancy suits and fancy words such as democracy and constitution really just hide plain old thugs. The ones who believe that if they are challenged, the dissent can be settled by cracking some heads.  
   
   
And the worst part is that you are losing moderate opponents as well as undecided voters. Remember of 14 million eligible voters only about 5 million voted for the NRM despite it boasting of having almost 9 million card holding party members. Essentially your own party members chose not to vote. The radical opponents will not change their views. these images have just increased their resolve and offered them even more or better ammunition than the lies and distortions some of them used to peddle before. Nothing sells like a picture of injustice meted out by a bully. Uganda is run by bullies.  
   
   
The NRM just crossed aline invisible as it may seem -just like Ghadafi crossed one. The next few weeks will show us just how much damage has been done. We may even know sooner when the cancellations of Kaguta's inauguration start to come in. Didnt you guys expect 32 heads of state.. LOL  
   
   
The blood of innocents will never go unpunished. As people who came to power on the back of the blood of innocents one would have thought that you understood this very well. If your guys really have any sense, they need to call the dogs of war off and send them back to the barracks. You will never win a battle where your opponent is civilian and unarmed with guns armoured cars and live bullets. And get rid of dead wood like Kivedhinda, Kabakumba and Mirundi. They just cause you more damage. And Kayihura -send him to staff college in Siberia, he needs to hide from the public eye for a while. As for that Gilbert guy who effected Besigye's most recent assault by state goons, you are going to have to find him another identity and another country to go to. Even Luzira maybe too dangerous for him.  
   
Those who the Gods mean to destroy, they first run mad ....
