# If the Museveni of 1986 met the Museveni of 2011, he would have him shot on sight.

Wednesday, May 18, 2011 at 9:57pm


Dear Nina,  
   
Its becoming apparent that your family do not like me writing to you. They are getting in the way of our blossoming love for which I have had to put up a [spirited defence](https://www.facebook.com/permalink.php?story_fbid=226141904066595&id=712431258) as you can see below.   
   
Patrick, I believe we have already discussed Ssuubi. You have distracted me from writing to your sister in law Nina today. Am sure Nina will be happy for the reprieve.  
   
Am not quite sure what your obsession with Ssuubi is as you keep bringing it up. I see no evidence that it is a national player nor has pretensions at being so. As far as am concerned it is just a lobbying group. Lobbying groups are acceptable ways of applying political pressure to achieve the goals of single interest groups and minorities. Museveni's government pys lobbyists in Washington for that purpose. As such Ssuubi can deal with any political group that is willing to offer a quid pro quo.  
   
I have not seen its presence in these W2W protests and neither have I seen any recent prominent headlines or comments attributed to it.  
   
The fact that you keep trying to associate my stance with Ssuubi is interesting as the only link between Ssuubi and me is the fact that they are Baganda. I have never read their manifesto nor really followed their activities. And during the time that you knew me, I never even attended any Ganda activities including Nkoba zambogo.  
   
But your obsession with them does tell me more about you. It suggests to me that you may have changed and no more be the Patrick that I knew and grew up with. That you are now wont to view everything with tribal lenses and are even willing to overlook the fact that in well over 1000 notes that I have written on FB, none deals with or mentions Ssuubi and that I only discussed it when you kept repeatedly bringing it up. In many ways it detracts from whatever point you may have been trying to make.  
   
I have several times in my posts credited Museveni with being ahead of his opposition and chided the opposition for underestimating him. However this time things are different. All evidence suggests that Museveni has underestimated the current of dissatisfaction with his leadership. He has become predictable, even petulant. Say his recent pronouncements, lecturing foreign diplomats, declaring foreign journalists enemies, bashing up his opponents in front of cameras, bribing his rented parliament to pass laws against anyone and everyone who pisses him off etc.  
   
The more things change, the more things remain the same. As one Frenchman said, "les vainqueurs prennent les vices des vaincus"! Museveni is day by day taking on the vices of those he opposed and fought. Quite frankly if the Museveni of 1986 met the Museveni of 2011, he would have him shot on sight. Shot because the Museveni of today isa traitor to the revolution that he purportedly ushered in.  
   
The words "fundamental change" mean nothing today. When Museveni came into power, he suggested that driving a pregnant lady on Obotes Kampala roads could cause a miscarriage. But looking at Kampala today, its no wonder the miscarriage rate is so high. Mosquitoes should go on strike against him for they are blamed for nothing for all of those miscarriages they did not cause. He also stated that he disagreed with obote on his handling of Kasubi. "there is no need to kill people because they disagree with the government", he declared! Today he is killing people for the same crime -disagreeing with him. Things like Grace ibingira's "detention without trial" were declared by him as signs of a bad government. Today we have him trying to remove the presumption of innocence and the right to bail. He has previously attacked these same principles including the right to habeas corpus through his safe houses, the misuses of JATT forces to attack the high court house, as well as the misuse of the military court tribunal in order to bypass the traditional court system which does not play by his rules. In an address to African leaders during his innaugural address to that now defunct body, he dclared that the problem of Africa were leaders who overstayed in power (beyond 10 years). He presided over the country during a constitution making exercise that imposed a two term limit yet despite him sneakily resetting the clock and later when it suited him again bribing a heavily biased parliement into lifting terms. Now we talk about a third term whereas he has already served the equivalent of five terms and is now serving the sixth for which he just got sworn in.  
   
Museveni has proven time and time again that he cannot let go of power. Interestingly a mans weakness tells one a lot about that man. In examining power we come to learn who or what Museveni is. A man enslaved by power, blinded by it to the point of failing to see that what is happening in Kampala now is a repeat of what has happened elsewhwre on the continent from Egypt to Libya. He fails to see that this is one battle he is not going to win. This is a problem of when ...! He has a choice of either managing his own retirement while he can still manage that or waiting for those angry kids on the street to come and drag him out of a bunker.  
   
Uganda has a large population of young unemployed youth dissatisfied with the status quo. They are unimpressed with development in which they do not share. while you Patrick and your children are enjoying the "progress" in this country, there are many who do not see their lot changing in the next few generations. Unemployment is virtually unrecordable and unmeasurable by any standardised means. even those who may report themselves as employed are really in disguised unemployment for surely the 20 or more tax touts at Wandegeya taxi stop couldn't possibly be employed. Nor the 40 boda bodas at each stage. We wont even talk about the hundredes of thousands of graduates walking the street looking for an opening.  
   
Many years ago I was a private student at Makerere. I will not bother you with the details but one day I talked to the late Dr Kisekka who was the then prime minister about how much university fees were. They have actually since come down significantly even though many Ugandans believe they have gone up -I was probably the first Ugandan private student and played a role in getting the senate and government to approve the scheme. Dr Kisekka told me about his younger days as a student and how he worked in a coffee factory to get his school fees. He suggested that i too should work in a cofee factory for wages to pay my fees. Of course the guy was so out of touch he couldnt even understand that what he proposed was impractical and completely unrealistic. But Ugandan politicians are so out of touch with the people they lead, they seem to believe that we view every word that drops of their lips as wisdom.  
   
In many ways he reminds me of you guys who are so deep in the kintu that your repsonse to ordinary Ugandans plight is to ask them to eat cake aka Marie Antoinette! But we all know what happened to Marie Antoinette. But trust me, I would never wish what happened to Marie Antoinette on you or your family and thats why am willing to be the voice of warniing -you guys are sitting on a time bomb. And its ticking ... tick, tock! And one day it will go kaboom and you will be wondering why no one wrned you! Anyway I went on and did my thing -without Kisekka.  
   
A few years later, I sat in an office with a big Health ministry official in his classy well cut suits and perfect boots (I still remember his dress for I have an eye for nice cloths especially nice expensive boots), as he ordered the minstry accountant to locate money from any account including project accounts as his children had to go back to university in India. Ironically, he was in Mulago that day because internes were on strike for their backpay and an increase on their salary of under 200,000. He arrogantly told me that Uganda had more than enough doctors and did not need the interns whom he proceeded to evict from the hospital. Recruitment of doctors was subsequently frozen for 3 years. Clearly this person despite his position had no idea what he was doing. He hadn't the slightest clue about the manpower requirements of his minstry yet he has since even been seconded to Geneva by this government. Talk about rewarding incompetence and mediocrity. Years later it dawned on the NRM that they really didnt have enough doctors but many of that group had voted with their feet and moved on to climes where they are better valued and not subject to the whims of incompetents.  
   
You talk about corruption. True we should talk about corruption but we should start by cleaning house. this bunch is so corrupted by impunity, they dont even know what the word means. In 2006, Salim Saleh stated exactly that -that he did not understand the meaning of the word corruption and needed someone to explain it to him. Your own father in law was embroiled in a scandal that should remain on the records and the text books on what not to do when you are in a leadership position. Temangalo was so full of conflicts of interest, it wasn't funny. He would have been much better off selling his land on the open market but of course would have had trouble getting a suitably loaded buyer offering him a reasonable price in the time schedule in which he needed the funds.  
   
Of course we all know that the main culprits in the major scandals that this country has seen remain free -all because they are friends of Museveni in the kintu. Museveni has either pardoned them himself or condoned their behaviour or excused it. You would be very hard pressed to identify any single successful prosecution for corruption. How could this government claim to be tough on corruption? Are they deluded or do they take all of us for fools? As for nepotism, if the sheer number of family members from the Museveni and Janet clans in this government is any measure, God save us all.  
   
You talk about winning elections. I have no personal knowledge of ballot stuffing but one can extrapolate from the Kampala mayoral race saga in which Sematimba a full pastor involved in vote stuffing but went on to be allowed to stand again instead of getting disqualified. If it happened in Kampala, it could have happened elsewhere. Museveni's own polling station was disqualified as apparently the number of voters there were twice the registered number of voters. One place in Gulu had more Banyakitara names than you could find in Kabale! And we are not talking about metropolitan Gulu!  
   
But more serious is the obvious abuse of office specifically the misuse of government funds to fund the ruling party and the incumbents re election. Surely you did not fail to notice that the president awarded himself 650 billion during campaigns thanks to a corrupted actually bribed parliament (20 million a piece). Surely you dont think the bills stuffed in those brown envelopes he was handing out came from selling cows at Rwakitura! Furthermore a further 6.5 billion was spent on buying LC's in the form of an ex -gratia payment timed perfectly just before an election. Now given you say you have been involved in many elections, you would be aware that the LC's are the gateway to the villages and anyone wishing to do "kakuyege" has to first knock on the door of the village headman and his councillors and in turn they will knock on the doors of the residents. In some cases, some of the residents will simply vote for whoever the "chayimani" suggested in this case the man in the hat!  
   
Regarding numbers, Uganda has over 13 million eligible voters of whom about half voted. Of the 13 million, the NRM claims to have 9 million registered as NRM members. These numbers suggest that even among NRM voters, about half did not even bother to vote, while almost half of all eligible voters did not bother to vote at all. this of course suggests that that often repeated 68% tells a more complex story than you would have us believe.  
   
We need to be serious. A government that has presided over such incompetence and corruption for 25 years surely cannot be expected to do better in five! We could all think like paesants and vote for whoever gave us some sugar and soap or some waragi or we can discuss these issues and justify all of that money that our parents spent on our fancy education. To do less would be to dishonour our parents sacrifices!  
   
P.S:Disclosure my parents voted NRM as they always have and went to Kololo while the rest of my siblings went to Entebbe road. Do the maths.
