# Nina, Ssegawa is so off point and is selfish, arrogant, lacks empathy and sensitivity to teachers!!!^[https://www.facebook.com/notes/drew-ddembe/nina-ssegawa-is-so-off-point-and-is-selfish-arrogant-lacks-empathy-and-sensitivi/10150290978127681]

Thursday, September 8, 2011 at 11:05am ·


> _Nina Mbabazi says,
> 
> ["And Mike Ssegawa is so on point. Enjoyed reading this"](http://www.monitor.co.ug/OpEd/Commentary/-/689364/1231620/-/12rijfnz/-/index.html)
 

PM Mbabazi went out on a limb when he started ordering teachers around. Nina is protecting her father. This row with teachers can easily expand into a countrywide workers rebellion and general strike! We know how those end up. In tear gas and water cannons and even tomahawks and dictators arses being hauled out of holes in the ground! And bottomline is the economy will get worse rather than better!

The attitude of this government to workers and their grievances is that because government has no choice, then they should just shut up and put out!

But the government has not done anything about all of its other problems that have contributed to this crisis. Like the boated government. The bloated parliament. The huge number of useless districts that cannot deliver services but are just a vehicle for delivering government patronage to cronies as are the presidential advisors which according to the government spokesman is just a vehicle for welfare payments to the presidents cronies!

The government needs to put its mouth where its money is and demonstrate to workers that its taking steps to rein in government expenditure and practicing fiscal responsibility!

All of these problems have been caused by this government. Teachers and other workers have been waiting for a living wage while NRM cronies continue living in largesse and running the economy into the ground!

Just imagine what effect 1.7 trillion would have made on the local economy if the government had its priorities right and used it to stimulate the domestic economy instead of buying useless baubles aka fighter jets!

So why should they listen to Mbabazi now when he has nothing tangible to offer demonstrating that the government is going to tighten government expenditure and reallocate government expenditure to responsible areas while trimming on wastage? Sack all RDC's and duplicate structures at all levels of adminstration, Trim districts and parliament to a quarter their current size, reallocate money for health and agriculture from workshops and perdiems to service delivery, improve service delivery efficiency, reduce taxpayer paid politician travel including the presidents, freeze the purchase of new gas guzzlers to all manner of political hangers on etc etc!!!

Our donors and development partners are also spooked by our governments irresponsibility as well as corruption. it would send out the right signals to all of them if the government could make the above areas a priority. As it is we have an incompetent government that takes workers for granted and is now in a panic hoping that threats and guns and teargas will help them instead of applying their brains and getting the confidence of workers and our development partners!!! This government has dug itself in a hole by ignoring the workers of this country and now the chooks are coming home to roost! time to pack those bags for exile and concede it has been a visionless soujourn!!!

God save Uganda!

P.S: I know this was about [Ssegawa's smartarse article](http://www.monitor.co.ug/OpEd/Commentary/-/689364/1231620/-/12rijfnz/-/index.html) but am afraid its all BS and he is talking out of his backside! He is selfish, arrogant, lacks empathy and is insensitive to teachers and other workers of this country!

The first and only question to be answered is whether teachers earn a living wage. And if the answer is no, then the rest of the arguments which are insulting are moot!
