# Katayimbwa murders and the elusive NRM peace and security!^[https://www.facebook.com/notes/drew-ddembe/letter-to-nina-katayimbwa-murders-and-the-elusive-nrm-peace-and-security/10150950794742681]

Tuesday, July 31, 2012 at 2:02am ·


Nina dear,

Obulamu.

These days you have gone quiet! Must be those naughty Chinese people who wanted to jail you! Kale obuChina bumanyiira! mbu you stole their motorbikes and refused to pay even after receiving the goods and disposing of them! naye kale mwana wabayisaawo! Am surprised uncle Kaguta has not as yet reprimanded you for mistreating investors!

Tomorrow am having an operation to fix the effects of your regimes little boys 3 weeks ago! Kale mwaali mumazzewo! Am sure you are going to feign ignorance of what am talking about but you would have to be the only person in the Ugandan blogosphere who does not know what am talking about! you may deny that there are your little boys but given they phenomenon of katayimbwa is one that has been nurtured and grown under the NRM, you cannot deny ownership! Your bu boys must have figured that I needed some re education about the "peace and security" ushered in by the NRM! And they did really re educate me and trust me, I can see the irony even more clearly than i ever did before!

Naye kale mwana gwe oli musezi olya n'abafu, as my grandmother would have said! Kale nali simanyi nti olina akatima akabi bwekatyo! If I ever doubted it before, now I know that among those who wish me dead, you have got a front seat. But knowledge is power!

You see in her village in Masaka, Rakai as in all civilised Buganda, if someone fell gravely ill or died, everyone on the village was expected to drop what they were doing and commiserate with the bereaved or the sick. Failure to do so would mark one as being a person of ill will and if there was a question as to whether there was witchcraft or poison involved or other mercenary motive, would identify them as the culprit! In my grandmothers village, your behavior would qualify you and identify you as the museezi or mulogo and you would be very lucky to escape with your life! Bandi pisse gwe emizingonyo ...I shudder to state where they would shove them! But as you know i have a soft spot for you so i will tell them to "beat you gently"!!!

You know I have always thought that if you guys were stupid enough to want to bump me off you would have to try and make it look like a random attack! People keep telling me i should not go to Uganda but I have always rubbished them! I did not believe that your regime are stupid enough to bump people off for disagreeing with the way you run the country -like village bumpkins!On a serious note I still do not believe that you are stupid enough to try to bump me off nevermind I shouldn't be so sure given the actions of your fathers regime! The reality remains that someone did seriously try to bump me off! I still have the bump on my head and a fracture to prove it!

Which does raise the issue of security in Uganda! You know security is the one thing that you guys have always claimed you brought! Its the opium by which you continue to drug the masses! Mbu 'twebaka ku tullo!"

Assuming this was a random act of violence which I prefer to believe it was despite what everyone else appears to believe, my immediate interest of course was how common was it! Imagine my surprise to find that this kind of assault is a very common occurence in virtually all surburbs of Kampala! there is even a name for it -katayimbwa. Some random comments I can quote include that of a neurosurgeon who testified that katayimbwa is the most common cause of head injuries on his unit in Mulago!

A pathologist in Mulago cites it as the most common cause of violent death in the morgue! At least two people showed me their injuries while two others told me their brothers had been attacked in similar circumstances and barely escaped with their lives following prolonged hospitalisation. Several people testified to knowing people killed with katayimbwa to the head within the last few days from places as diverse as Mukono, a surburb on Entebbe road, Kawempe etc!

A radio programme debated the phenomenon of katayimbwa and several newspaper reports on deaths appeared in the two weeks I was in Kampala! Several businessmen were shot and killed or butchered with many of these murders remaining unsolved. An article quoted a murder report that suggested at least 10 people were killed in Kampala each night in such similar incidents!

You know I was attacked very early in the evening at 8:30 right next to a police barracks in a spot that. It also happened to be on a night that commemorated the first anniversary of the 7/11 Rugby club bombings. Kayihura's men had a show of power out that day -enough for everyone to feel safe if they really had any faith in the police! But Ugandans have learnt not to have any faith in a politicised police! The role of Kayihura's police is to keep the government in power not to protect the community! Thats why despite the heavy presence of policemen and women everywhere, people continue to be murdered everyday! Thats why places the community considers to be red spots are not monitored by the police! Do you know that many people are convinced that the police themselves are a part of these attacks on innocent people?

In the two weeks i spent in kampala, i got to get an intimate knowledge of at least 5 hospitals in kampala, 3 in one night! my experiences which i will write further about go on to reinforce my previous opinions about the health system in Uganda under the NRM! Am not quite sure that there any words that can really describe the mess that you guys have presided over and produced in the last 26 years and counting! Its no wonder you steal 350 million USD of taxpayer money a year to have yourself treated overseas while the hospitals at home are rotting!

i was amused when a few days ago your father the Prime minister listed on twitter the so called health achievements of the NRM government! Munange daddy wo mugambe he should not embarrass himself again without getting proper briefing! As a matter of fact as a leader of government business and an aspiring president of this country who has been one of the longest serving ministers and architect of the movement, he really needs to acquaint himself with the mess over which he presides!

One does not have to be a specialist to know that the health system in Uganda is a mess! you probably know by now that he was robustly rebutted and retreated never to return after he cited the uganda Heart Institute and the uganda Cancer institute among the 'achievements of the NRM! Quite frankly if you guys do not know what you are doing you really need to step down and go back to rearing ducks and goats!Uganda does not have a functioning emergency care, primary care, critical care as well as many recognised specialties and subspecialties! And this is not because i am being elitist or comparing Ugandan with western countries!

Ugandans die everyday from simple things for which no one should die in this day and age! And for the PM to cite cardiac care and cancer care as "achievements" is at beast ignorant and at the worst mendacious! if he really wishes to become president he needs to start setting himself aside and informing himself rather than parroting what is written in the NRM manifesto which quite frankly is lies! the mortality rate of a Ugandan woman with breast cancer is 200% the international average! that figure lone should give you some idea just how bad the situation is! I wouldnt even wish to hazard a guess what the cardiac mortality rate is compared to international and even regional standards unless you are comparing Uganda with Somalia and Congo!

Kampala is insecure! The myth of the NRM having brought peace and security is just a myth. People are dying everyday in preventable homicides with the police looking on! the people consider the police to be useless and actually the enemy!

Within days of my assault 2 other people reported being assaulted on twitter and one notified your father in a tweet! His very laughable response was -go tell the police! I think you guys must be deluded! The police is useless and to report yet another assault when they have done nothing about the previous ones nor taken any steps to prevent future assaults and homicides is a waste of time! Me I refused to waste my time! The police have got enough statistics and do not need any new ones. they just need to act and to be seen to be acting!

When i arrived in Uganda 2 days earlier, it was as usual to see what new changes there were in Kampala. Among those changes is personal security! As a member of the Ugandan diaspora who also happens to hold a foreign passport, security is important. One assault almost left me dead, almost left my children orphaned and given my head and my dominant hand were involved almost left me unable to work! As it is while i am back to work, my driving is limited and i will need to take off extra time for another operation. So two weeks in Uganda have ended up having lasting impact that of course also determines how i view Uganda!

Can you imagine i had only spent two days in Uganda and my 2 and a half year old daughter was visiting Uganda for the first time! It would be a day she would forever remember as she had just been baptised the day before and for the rest of her life, thats all she would ever remember of Uganda! my sons experience of lawlessness has always been on visits to Uganda with at least three robberies, and this attempted murder! That 2 days before we had paid 200 dollars for visas to Uganda expecting to have a holiday and instead experiencing a nightmare!

It is interesting that your NRM talks about investment, mining and tourism without paying any attention to personal security and primary and acute healthcare services! it makes one wonder whether you guys really understand the fundamentals! That for businessmen and tourists to visit Uganda and spend money as well as invest, they have to be assured of security. And security is not about the vulgarised visible but inneffective security in Kampala that is pervasive but basically run by ignorant people who would miss a bomb if it were right in front of their eyes! Security can be very effective even when invisible and unintimidating!

i found it interesting that your brother in law, Patrick, who i used to consider to be a friend put my assault down to a mere statistic! He even suggested that i made up the whole thing to make your government look bad! Quite frankly one does not need to make up anything to make you look bad -you do a good enough job of that already!

I have been asked to give a talk about health in Uganda in a forum that will include members of the diaspora as well as investors with mining interests and potential tourists!

I remain conflicted! Do I promote my country while covering up incompetence or do i lay out the whole naked and bare truth? Given that i do not like telling lies, you know exactly what i am going to say! It would actually be unethical to cover up the truth -that the NRM has been lying to people about having brought peace and security and that it is common and quite possible for one to be killed in a random event for simple things like pocket change, a watch or a phone! The NRM also needs to know that if it wishes to attract investors and tourists, many of whom are retirees with chronic illnesses, they need to pay attention to the healthcare system! When i called my travel insurance company, I was told verbatim, that i was calling from the middle of nowhere in Africa! As you can see the millions of dollars given the first son to "sell" the country went the way of those wasted on the police!

I wonder what you guys see when you travel to other countries to study, to do business or even to have babies at our tax payer expense! Or are you so blind you cannot see that your so called development falls far short of the mark?

Munange yadde you wished me dead, me i will hide you under my bed when the peasants come for you with pitchforks as they certainly shall! Don't think that those idiots with katayimbwa will not one day come knocking at your gate! for as long as the NRM continues to create these problems, you and your children shall never be safe in Kampala just like the rest of us are not now!

So much for the NRM peace and security! Needless to say while I have no choice and will be visiting Uganda again in future, none of my acquaintances and friends are likely to be visiting Uganda as tourists or investors at any time in the near future!

*******************************

P.S: I wish to make it clear that despite many suggestions that the attack on me was politically motivated i believe it was a random attack reflective of the lack of peace and poor personal security in Uganda under the NRM government! While i am aware that my articles upset some people in the NRM, i have got no evidence that this was a politically motivated attack. I also wish to state that I am not and have never been a politician!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Katayimbwa](http://ddembe.wordpress.com/tag/katayimbwa/), [Letter to Nina](http://ddembe.wordpress.com/tag/letter-to-nina/), [Security](http://ddembe.wordpress.com/tag/security/)
