# How do you put lipstick on a pig?^[https://www.facebook.com/note.php?saved&&note_id=10150554852582681]  

Sunday, February 19, 2012 at 8:23pm ·


Nina dearest,

Nakawere oli otya?

I can see you stepped out yesterday to check out the nightlife. Or was it UMEME that chased you away from home! Munange Ugandans kati basula bweeru as it is the only way of getting some electricity unless you can afford a generator, solar panels and inverters! Considering that only 10% of Ugandans have access to electricity, one runs out of suitable expletives to describe your daddy's government and their partners in crime UMEME! Surely UMEME cannot be doing any better than UEB was! Both provide darkness and bill you for the doubtful priviledge! But worst of all, with UEB, poor Ugandans did not have to pay overated UK expatriates hundreds of millions while exporting our hard earned cash to their shareholders in the UK for their pensions and investment funds! Talk about the rich robbing the poor!

I hear daddy cut the ribbon for an extra 50 MW but UMEME has already made them dissappear without any appreciable effect on the supply of electricity! Darkness still pervades everything! now that other man who run down the AGOA scheme was also seen in your daddy's neighbourhood of Kanungu hobnobbing with a new electricity supplier there! Seriously cant you people just blacklist some of these people?

Saying that what is the story with Basajjabafuna! I hear thats what he is called these days! What with the billions he is forever gifted with for free as they say in Uglish! How could one man be gifted with enough money to renovate Mulago hospital, enough money to run Mulago hospital for many years, enough money to run several districts for many years, enough money to eliminate nodding disease that is the current scourge of children in the north many times over!

While the government can only find 27 million for prostate cancer research in this country and 100 million for the nodding disease, Basajjabalaba always finds billions -nay hundreds of billions thrown his way!

Interestingly despite several scandals -UBC land, BOU land titles, UMSC land titles, diverted tax rebates (illegal by the way since they are not catered for in our tax regime) KCC market scams, Mr Teflon Basajjabafuna has never so much as registered a police file let alone been dragged to court save by URA! Not even once before the corruption court even after he diverted land titles deeds he had already submitted as collateral for a soft loan that he did not pay!

A few weeks ago after his Godfather had to appear before the PACS committee to account for himself, it appeared like Mr Teflons luck like that of another now deceased businessman who built a monstrosity on Entebbe road that received state funds for no work done, had run out! I thought that the ever vigilant Kayihura who has made it a habit to harrass or undress unarmed women like Ingrid Turinawe, or beat up on Besigye whenever he runs out of punching bags would relish the opportunity to finally do some work and grab Basajjabafuna by the trousers and frog march him to CPS for questioning, take off his belt and shoes, steal his valuables as "evidence" and send him off to Nakasongola over the weekend when the courts were in recess but wapi! The ka guy is a paper tiger! Faced with a real big fish, his tongue went dry and he disappeared!

Two days later the sabalwanyi himself turned around and started to backpeddle over his statements in PACS that Basajabafuna should face the music! Oba who owns who? One would have thought that the man who fought adui while men like Basajabafuna were cowering under their beds would very quickly rough him up and sort him out naye waaah! There must be something that this ka guy has over the sabalwanyi! Ye nga tewaali amukwataako? And how comes its the sabalwanyi who has always approved this guys deals and scams?

This Makubuya guy seems to know something about how this thing went down! A week ago, he virtually blackmailed sabalwanyi! He reminded me of those days in school -mbu nkwata kko ondaabe! Nja kwassa enyindo! Ms Syda Buba went down more meekly protesting that she was only doing the sabalwanyi's bidding and he was responsible!

At the end of the day, sabalwanyi stared down Makubuya and Makubuya had to turn tail and flee to the back bench! I wonder how long he will stay there before being dragged out to face the anti corruption court like Bukenya! Not that the government will win anyway! Am sure he knows very well that they can be trusted to mess up their own cases and bungle the evidence! If his Havard brains are working, am sure that like Uncle Jim, he probably salted away some brown envelopes with compromising photos of big people! Don't you see how Uncle Jim continues to thumb his nose at everyone years after he was charged with corruption? Bageze bamukwatte ko!

Now these bu children in the north who want to mess up the glossy figures in the NRM manifesto of the wonderful health that you guys ushered in! Someone suggested today that they should all be drowned -problem solved! No embarrassment to the emperor! How dare they embarrass the almighty! Do you know that in any other country that pretends to be democratic if it ever came out that the government knew about the nodding disease 3 years ago but proceeded to deceive the country with its glossy pre-election manifesto in addition to inaction heads would roll at the very highest level?

But of course we do not expect that in Uganda! which other country can boast of 10 % of the cabinet ministers resigning for corruption within one year and still remain in charge of the country?

Naye you people are so childish! I hear the other day the president was boasting about playing childish pranks on parliament! Mbu the MP's were going to block the signing of the oil agreements at 2 pm so he ordered the Minister to sign them at 10 am!

I hope Minister Muloni is reading the tea leaves! If I were her, I would record all orders or insist on getting them in writing! Anti you see in this thing, the man is always right -and someone else will always take the fall! So when the oil documents come back flawed, you know who is going to have to bend over a barrel and get circumcised, don't you! I do not envy Ms Muloni!

Now these greedy MP's banange! No wonder they are all playing games with each other! pigs all of them! Mbu they need cars "befitting" their status? Are they all blind? Is it not obvious to anyone with eyes that there are no roads in Uganda to drive cars on? And even if you have a car, the congestion! They are better off being given boda bodas! At least then they can weave through the mud tracks that lead to their constituents homes to crash their funerals after their children die from nodding disease or just plain hunger!

Before, I leave, I am tickled by your daddy's new partner, the new Irish company that is supposed to provide PR for the NRM government! LOL! Talk about putting lipstick on a pig! Just assuming this man is even qualified to do the job which is very doubtful, or his company has got the resources and logistics to as well as expertise to deliver, how could you bring an ignorant Irish briefcase company with no experience of working in a similar country to do the job of slapping lipstick on this very huge hog! The hog will pass wind on him and he will suffocate! Seriously I would be surprised if this guy even knew where Uganda was on the world map before you guys gave him a million big ones! And as usual, I can bet my money that here is a Ugandan in that pile! You know previous ones benefitted Rwabwogo, then Kutesa's daughter or was it the father .... one wonders which sharp Ugandan well connected middleman is benefitting from this one! If I were dady, I would start digging now before the hog poo hits the fan! Those enemies who were telling tales about him to try and kick him out of parliament and office will have something more substantial to talk about this time!

Baby munsunile ku taama! You know where to find me when things get tough! As previously promised, me am ready to hide you and the little one under the bed!

Uncle Kaguta mundabire! The latest is that its time to go for the Godfather. Me I don't think so! Am all for death by a thousand cuts -kind of masochist but okitegeera!

The man should have retired when he was still ahead!
