# Sugar is going to topple your regime!^[https://www.facebook.com/notes/drew-ddembe/letter-to-nina-sugar-is-going-to-topple-your-regime/10150266134287681]

Tuesday, August 9, 2011 at 12:01am ·


Nina dear,

Sukali akutte wansi ne wagulu! At this rate it appears that the nemesis of Uncle Kaguta will be sugar!

You know these things bitandika nga ebyokusaaga but then they get serious! In Tunisia, it all started with a pathetic man who couldnt find himself a job. So he in entreprising fashion or was it in deperation tried his hand at selling vegetables on the street. But the police would have none of that. You see in Ben Ali's Tunisia, people like him did not exist! The lived under the radar and the state would rather convince themselves they were just lazy! Poor man in desperation took his own life!

But in that one act of self imolation, he set into movement a great force -the wind of change. Some know it as the Jasmine revolution or the jasmine train. It flowed and wafted and caused seismic waves all over north Africa and the middle east. In an act of powerlessness and desperation, a great power was born! The power Ben ali of Tunisia was brought down by vegetables and had to hop from one country to another looking for asylum!

The catalyst in neighbouring Egypt was not vegetables. It was the price of bread. You see, Egypt is one of the worlds biggest importers of wheat! For as long as people had their daily bread, the Mubaraks could go about their daily stealing with impunity! But once the price of bread was tampered with, Mubarak had to go! Now he is a wizened little octogenarian in a cage -a pitiful sight! Very far from the man who dubbed himself "father of the nation" and presided over a state of emergency for 30 years. Pundits opined that without him Egypt would collapse, in much the same way that they opine about Uncle Kaguta! But you see Egypt has been around for millions of years. Pharaohs come and go but the country and the people remain! The last pharaoh of Egypt is no more -brought down by bread!

For a brief while, it looked like fuel would be the downfall of Kaguta but you know, the price of fuel simply does not have as much power in a country like Uganda where only a handful will ever even dream of owning a car! So to most Ugandan's it is an abstract concept. Few even relate it directly to the price they have to pay for transport!

But sugar, thats another story! Thats something all Ugandans understand. You see Ugandans have a sweet tooth. If you doubt it, look around you at the tummies and generous behinds! Ugandans do not care about the price of fuel and neither do they care for the price of wheat and bread. Most Ugandans do not eat bread anyway save for the wannabee middle classes in the city!

I first found out the power of sugar a long time ago on a visit to the village. My parents never took us much to the village save for this one time -actually the second time they ever allowed us out of their sight for a month! We went to grandma's place in Masaka for the holiday! As part of the gifts, we carried sugar, salt, soap and of course omupunga! Such were the deprivations of Amins Uganda that people had to carry essential foodstuffs hundreds of kilometres to the villages. these days one can buy most of these thigs locally if they have the money -money of course being the key word.

I find it interesting when people wax lyrical about the economy during Amins regime! I was a child but I know for a fact that there was only one "supermarket" at drapers building near the taxi park and that towards the end of his regime, it was empty. I know for a fact that sugar had to be bought from the back of Hajjis shop in Nakasero -you see Hajji was a hoarder who hoarded sugar for economic gain and sold it on the black market then called magendo! A neighbour Peter, whose son I went to high school with was in and out of jail for economic crimes -essentially hoarding petrol and paraffin and selling it under the cover of darkness, while another neighbour was a dealer in "kasse" or blackmarket coffee which was exported at great profit to a neighbouring country. You see the only buyer of farmers coffee produce in those days was the state through the coffee marketing board -daylight robbery if you asked me!

Grandma was a hoarder -of sugar! While it was common knowledge that sugar was scarce in those days, she always managed to have some sugar hoarded away for the visitors from Kampala! Villagers had learnt the art of surviving without sugar. Omupunga was a treat att christmas while salt was a luxury that made one friends on the village!

In came Obote in 1980! And with him came insecurity and runaway inflation. Sugar was once again a rare and valued comodity! Manufacturing broke down completely with the major producers relocating their manufacturing to Kenya. If the Kenyans sneezed, ugandans caught a cold!

Ugandans also got a new disease -chits! There was a whole industry built around the buying a selling of chits from ministers and well connected people. These chits could get you sugar, beer, cement at prices that others would kill for. You paid someone to get you an "allocation" of a scarce commodity. This allocation came in the form of a chit from the minster which you presented to the manager. It even served as an IOU and was tradeable goods against which one could borrow money! Fortunes were built around the business of chits! Even getting your half brained son into an elite school could be achieved using a chit! At a certain time of the year, this was the main business in the Min of Education!

Zimbabweans think they invented runaway inflation! They should have been in Uganda in the early 80′s! If a shopkeeper opened shop in the morning and sold his goods before checking the going rate for the USD on the street, they could very easily go bankrupt! One literally needed a kikapu and millions of shillings to buy bread -and of course the valuable crystals of sugar! Owning USD was an economic crime! The state had this thing they called window one and window two and made it illegal to trade foreign currency outside those two! But entreprising Ugandans traded forex on the street at exchange rates tens to hundreds of times the official rate! And woe betide you if you were caught with "adui" or the enemy which is what Obote's soldiers dubbed forex!

But back to this thing of sugar! In those days only the lucky ones had sugar everyday. My mother became just like her mother an expert hoarder of sugar! The best friends were the local traders. People lined up to buy sugar but my parents made friends with the traders and got theirs delivered at the back door! My mum always had sugar stored awaty somewhere under lock and key!When Museveni came into power, he rubbished the need for people to line up for sugar! In the initial days of 1986, one of the main functions of the LC's was to distribute sugar at a government price. No budget was complete without the price of beans and sugar! Being friends with LC's allowed one to get a bigger allocation of sugar! Every family had to have their name ticked off a list and their allocation given to them!

Ugandans soon moved on from this basic economics. For 25 years, Museveni has presented rosy economic figures demonstrating how Uganda was developing significantly! For most people the economics of sugar and salt were no longer an issue and people had moved on to other things!

For the last few months however, Ugandans are consumed with the price of sugar! Its on the lips of everyone including in the rarefied spaces of the internet and facebook! it is testimony to the air or in Ugaspeak "kiwani" or the smoke and mirrors that Ugandans hae been sold for the last two and a half decades. Following the arrogant speeches prior to and after the last election claiming the fundamentals of the economy were sound, despite evidence to the contrary while spending money on getting re elected like money was going out of fashion, it is interesting to watch the chickens come home to roost! After 25 years, we are right back were we were in 1986 with the price of sugar being the dominant question on everyones lips! One wonders what happened to the funamental change and all of that economic growth!A look at other countries has shown that the spark that saw the demise of the sitting government has been something that most people can identify with!

Ugandans can identify with the price of sugar. Nothing brings home to them the fact that things are bad like the inability to afford sugar! Right now if I were this government I would not be sleeping easy! But see what they managed to think up -Kyambadde wants traders to line up in her office for chits! Chits you say? Isnt that what they used to do in 1980? Exactly! Thats how far back we have gone or did we ever move on from there! Has it all been an illusion? And poor old Kaguta could only think of two things to say -that his father does not eat imported foodstuffs and that traders were economic saboteurs! Banange did this man ever hear of supply and demand?

Kale mwe mbasassidde! Me I learnt how to hoard from my mother and grandmother! the moment I say you guys spending 650 billions on buying votes and another 1.7 trillion you dont own on jets you cannot afford to fly, I knew inflation was coming! You scoffed at me!

He who laughs last, laughs best! Sugar is going to be the nemesis of Kaguta, just like vegetables toppled Ben Ali and bread toppled Mubarak!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Letter to Nina](http://ddembe.wordpress.com/tag/letter-to-nina/)
