# The NRM is corrupt -no amount of spin is going to change that!^[https://www.facebook.com/notes/drew-ddembe/letter-to-kakwenzire-the-nrm-is-corrupt-no-amount-of-spin-is-going-to-change-tha/10150438900417681]

Friday, December 23, 2011 at 1:28pm ·


[Apollo Kakwenzire,](https://www.facebook.com/note.php?saved&¬e_id=10150434193132681)

Normally I write to my sweetheart Nina but today I will respond directly to you as some of the things I say today may distress her!

The NRM has been in power for more than 25 years. The only reason we are at this point is NRM incompetence in fighting corruption primarily because it is the key cadres of the NRM who are corrupt.

That corruption is abetted by the highest office in the land, President Museveni as evidenced by the claims of his ministers and Attorney General as well as the case study of Basajjabalaba. Of course other cases such as the junk helicopter scandal involving his brother Saleh, the collapse of UCB-Greenland due to its fradulent purchase of a state bank through Westmont, the defence of Mbabazi and other cadres even before investigations are out, making sub judice statements that prejudice such investigations and the courts, as well as inactivity and empirical evidence of the lack of successful prosecutions and convictions in part due to executive interference in the judicial process increase the perception that the whole party and leadership are corrupt.

Of course as one would expect, Museveni threw all of his men and women before the advancing crowd. He continues to maintain that he is clean while its the people around him who are not! if I were an NRM politician, I would be wary!

I have more than once stated clearly that i have not seen the evidence for Mbabazi's involvement save for the claims of ambassador Lanier in his leaked cables to the US government. In those cables, he claimed no evidence other than the claims of one of the oil companies that was interested in the outcome of the negotiations with ENI. The claim that ENI a competitor had bribed Ugandan officials specifically Mbabazi was never presented with proof. the request that the US embassy imposes travel bans on Ugandan officials with the capacity to influence oil negotiations was blackmail and coercion by one of the beneficiaries to those oil negotiations.

Such interference by foreign oil companies leaning on and coercing or blackmailing Ugandan government officials should be taken seriously as they are as bad as if not worse than bribery! Either way whether using bribery or blackmail and coercion the goal is for the company to get advantage in oil negotiations. I have therefore personally stated that i have not seen the evidence for Mbabazi's involvement in oil corruption which of course is not the same as saying that he is not corrupt.

As you may already be aware, despite him being "cleared" by the IGG etc, I disagree that Temangalo was above board -it was not! NSSF was robbed of its money by politicians! There was conflict of interest and all sorts of isms in that transaction. W also know that at the time, buying land was not part of the NSSF's investment policy having been burnt in a previous land deal!

Mbabazi would have been a lot better off if he had sold his land on the open market. But we do know that he had a deadline to beat and needed a certain amount of money in a fixed timeframe, an amount no single body or individual could have raised. We know how hard it would have been to do so because Akright which later aborted the purchase of Jim Muhwezi's land in the same area failed to pay even when the payments were stretched out over time. This is relevant because it is this figure offered to Muhwezi by Akwright that was usued to bolster the claim that NSSF received value for money.

That says that the market at the time simply could not pay the figures they claim to have been the market value. For them to get anywhere near the prices they claim, they would have had to parcel the land into plots and sell one by one over months to years! They simply did not have that time so they raided the single largest cache of cash in Uganda -NSSF by coercing and leaning on the boss, an impressionable young man who later ended up in jail on unrelated charges for not shutting his mouth up when the dung hit the fan!!

Remember its the market that determines the price of a property, not the seller. if the property is overpriced, buyers will not buy at that price. Furthermore, the urgency of the sellers need for money and the relative scarcity of finance would mean that a bulk seller would attract a lower price if he does not have time and resources to redevelop their holding into smaller parcels! The method an argument used by Mbabazi and his supporters including Andrew Mwenda was therefore flawed because it did not take into account the fact that they needed large amounts of cash at short notice in a country where there are few people with that kind of cash lying around. If they existed anyway, they would dictate the price and would have paid much less for the land than NSSF did!

There is of course the defence that what they did "was not illegal". Am sure its the very same defence that Karooro Okurut is going to use to dismiss the charges of enriching herself at the states expense when she and Mwenda's sister Muhanga got a multi billion shilling property free from the state on fraudulent grounds -fraudulent because the purpose of the allocation was for them to build a shoe factory but they just transferred their interest in the lease for cash within months! If they were genuine why didnt they return the land if it was unsuitable and demand another more suited to their purpose? If they failed to raise funding for their venture, how does the Ugandan tax payer benefit? As far as one can see UBC, the tax payer and the state lost a multi billion dollar asset which asset could have been sold competitively by auction and the proceeds used for other infrastructure development for UBC or the country! As it is an indiviudal who is connected essentially a crony ends up becoming a billionaire for free!

The request for Mbabazi to step aside can be justified as he is the head of government business in a corrupt government and has been a key minister for a long time. As a matter of fact he is and has always been one of the most powerful minsters in the NRM. If a government fails, someone has got to take responsibility. The head of the government actually happens to be the prime minister, Mbabazi! The use of oil charges without reasonable verifiable evidence instead of stating this simple fact maybe a criticism of the framers of the charges in parliament. of course it should not be forgotten that in Uganda we have an executive president ven though the PM is the leader of government business an ultimately it comes back to Museveni. If the country demands that someones head should be given up to them on a platter and that person happens to be Mbabazi and Museveni dcsides to stand by Mbabazi, depending on the countrys mood, it is then Museveni's head on a platter that will be demanded in recompense!

You oversimplify Mpirirwe's opinion. He essentially stated the steps taken in verifying that documents claimed to be proof or forged are indeed forged. WHat he did was raise questions but not prove that they were forged. He systematically demonstrates that the documents were very close to authentic and could only have originated from true originals or the work of a perfect forgery. He acknowledged that he did not have access to the work of the Malta police and that the presence of the mentioned bank accounts needed to be confirmed by a competent authority. As a matter of fact he as careful to state that his comments were based on the information available in the public domain. If I remember correctly the previous investigations did not actually say that none of those entities existed. All they said was that they could not ascertain the veracity of those claims! This does not close the case.

Neither do the denials of the oil companies close the case. The proof of bribery payments to government officials is now a prosecutable offence in the UK and other parts of the world and would also prejudice their current tax arbitration proceedings in London as well as future dealings with the government and people of Uganda. It will subject them to a lot of future scrutiny in addition to ensuring that they have a hostile PM in Kampala who they will have to deal with not to mention a minster for energy! These companies try to put themselves above the law in Uganda which so far is what they have tried to do at the expense of Ugandans and their resources! This story is as a much a story of the greed and corruption of Ugandan officials as that of oil companies!

Of course there are internal wrangles and political schemes esigned to bring down presidnt Museveni and his most powerful minster Mbabazi. Thast politics and when you refuse to retire, opposition mounts as well as resolve against you. Baganda say that "ensi egula milambo" -nations are built on top of corpses. Museveni and Mababzi have detroyed a lot of people in their rise to and continued hold on power. In addition they block the advance and ambitions of many young politicians. None of the young turks is going to go anywhere while Mbabazi, Museveni and their children are involved in Uganda's politics and security. You are a cattle keeper, so you are well aware what happens to the alpha male when the young bull grows up. It will be a fight until one gives up or dies. Humans are not very different from animals and none of this should surprise you. It will only get worse and the only way for it to end is for the selfish old men who have hogged our politics and positions of power to signal their own retirement. That way they can control the process. The alternative is chaos and will be bloody! this is an irreversible process!

The fact that Uganda and the NRM were just a change of guards as they have proven over the years rather than a revolution means that you will not have the power to stem the tide. You have to adapt with the flow. Make concessions. Negotiate. Or fight it out to death -like Gaddafi!

As for Rugunda, he was at his zenith after the Juba "peace jokes"! True to form, Museveni moved him aside and out of sight to New York guaranteeing that by the time he came home, everyone had forgotten about him! Of course the little known fact that he is one of the major shareholders in the Temangalo bank will be brought out at the right and opportune moment if he dares to raise his head. You of course know what happened to Mahogany polofessa bukenya when he over reached himself! He was taught a lesson he is not going to forget in a hurry!

Mbabazi declared the presence of a queue many years ago. Most Ugandans didn't even know one existed. They thought it was "individual merit" whatever that means until Mbabazi let the cat out of the bag! Baganda say, that when a co wife sees the stick that beat their co wife, they would be stupid to return that stick to the house as it will sooner or later be used to beat them too! Mbabazi is the stick that Museveni has used for many years to bet his opponents inside and outside the movement. Mbabazi too has used his authority to maintain him at the end of the queue!

But again Baganda say that "awakula ennume, tewakula emu". Thats a proverb you as a cattle keeper should understand well. The kraal that raised one alpha bull can not fail to raise another! Sooner or later with the passage of time, the bull is faced with younger bulls ready to take up their mantle whether he wants it or not! Thats the reality facing Museveni and his right hand man Mbabazi -the young bulls are not going to wait for them to die off of old age. Unless they have an old trick up their sleeve to defeat the young bulls both within and without the NRM, they are going down! only a matter of time! Change is coming and neither you, Mbabazi nor Museveni will be able to stop it! All they can do is to ensure that that change is as orderly as it can be!

There are still a lot of unanswered questions about the oil bribery scandal and Jasper Mpirirwe just articulated some of them!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Kakwenzire](http://ddembe.wordpress.com/tag/kakwenzire/), [Nina](http://ddembe.wordpress.com/tag/nina/)
