# A victory all up in a puff of smoke.

Friday, May 13, 2011 at 12:29am


Dear Nina,  
 
   
Am sure you have now left Kololo where our money has just been spent feeding tyrants like Mugabe. I know I shouldn't be reminding you but i just cannot help telling you that i told you so. This is a pyrrhic victory. All of Museveni's joy at winning just went up in a puff of smoke just like the billions spent at Kololo today.  
   
I remember you and your aunt Alice assuring all and sundry that you yellow girls would rub the noses of everyone in it on this day. That all of Museveni's critics would slink off into the sunset and that you would have the party of all parties.  
   
Today, I actually pitied you. Most of all I pitied poor Museveni. How can you be robbed of victory in your moment of triumph. When you are powerful, have mean soldiers, have all sorts of hardware designed to cause pain and humiliation. Yet its you who ends up getting humiliated.  
   
You are a lady so am sure you understand the feeling of a girl who gets humiliated by her fiancees ex turning up to her wedding better dressed than the bride. The enfrontery. The rudeness. The arrogance. Many a bride has jumped across the high table and tackled the offending female. Am sure that today, Museveni felt like starngling someone.But you know the monsters one creates do rise up to bite you. I did warn you that Besigye who was destined for his farm to rear ducks and goats has now been given a big shot of political viagra ironically by President Museveni himself. Thats what you get for putting a boy in charge. You do know that he sent his boy to take care of things but all just backfired. If you are going to assassinate a man do it properly -so dont send a boy who has never made his rocks to kill a man who has been to hell and back. Ugandans have been to hell and back and now they see you taking them back to hell in a basket.  
   
The NRM and Museveni have this simplistic notion that they are the annointed keepers of the constitution. They seem to forget that no one has got a monopoly on protecting the constitution and Museveni will not be the last man to claim that he went to the bush to do so. Of course as we now know that claim hides lots of self seekers whose only goal is power for the sake of power itself. You recognise them from their inability to understand that true powr lies in being able to let it go ... that a man or woman who is unable to give up power voluntarily is a slave and not the master of power.  
   
I really wonder how long it will take those soldiers now whipping people expressing their right to fete and celebrate whoever they want, that they are being used. Used by the very same people to blame for their unfortunate circumstances. Isnt it surprising that the people protesting can actually afford the necessities of life much better than the average soldier. Could you ever contemplate living in a mama ingia pole with all of your brood? And am not talking the two and a half children. The poor who include police officers and army men have lots of children many times from lots of women. Its not unknown for two women to share one man in one mama ingia pole. I dont want to inagine the kind of sexual education their children get ... unless of course their mothers choose to bite their tongues. But you do know nature .. these things sometimes overwhelm one.  
   
Besigye is rejuvenated. Who could say what a few beatings and broken bones could do to a mans fortunes. even Mao has obtained a few kudos points as a result of getting arrested while poor Otunnu is now trying to stand up there with the big boy. He too has a headache apparently from that dye your boys were dishing out. If they can avoid tripping over their ego's this is going to be one hell of a rocky five years for the son of Kaguta -if he last the course. There will be no shortage of politicians offering themselves to be beaten up and arrested. Unfortunately like trained Pavlovian dogs, Kayihura's boys and Muhoozi's boys will have little trouble granting them their wish. I must admit if I were Kaguta I would relieve those two of their duties as their activities in the last three weeks have brought him a lot of "bukyayi". They are virtually sabotaging him.  
   
You know bizibu come in doubles. President Museveni had to lose face in front of his invited tyrants. He showed then that he was not in charge of his household. I wonder what comrade Mugabe was thinking on the way back when stones were raining on his convoy. I understand he was so bored at Kololo he slept trough it all or was it just his age. You know at that age, the flight from Harare is no mean feat. even more worrying is the virus he inadvertently took back to Harare with him. Ugandans have been displaying to the Zimbabweas who were always doppy anyway how to do it. I have never seen people as sleepy. Even Zim robbers are polite. Not like Ugandan ones. Can you imagine Zim security men turn up to the scene of a crime with batons. Which self respecting Ugandan robber would be armed wth anything less than an AK47. Trust me if Uncle robert does not do himself a favour and have a coronary, his people are going to be picking up some cues from Kampala. As for the man in Djibouti  ..talk about dead men walking. I hope your boys are not going to accuse me of sedition. You know that stupid law got struck off our legal statutes.  
   
Am still interested in knowing if the taxpayer will get a refund on their money for that pathetic display at Kololo as less than a thrid of the invited guest actually turned up. You refused to tell me if you got yourself a little contract with good njawulo. Am not allergic to a woman of means you know. Who cares where the money comes from. As for those with nugu, wama where were they when you guys were fighting and they were hiding under the bed.  
   
Unfortunately Ugandans have refused to hide under the bed any longer and leave the show to the guys with guns alone. The sight of those people defying your military goons and thieving police to escort Besigye back home while eclipsing what was supposed to be the biggest party in the land kind of gives one a taste of things to come. Life is not going to be easy and a wise one would start finessing their exit strategy.  
   
Now the second part of the circus is about to begin with the blackmail, intrigue and greed. Am talking about sharing the national cake aka appointing a cabinet. I hear Old man Kaguta in addition to handing over to himself for the umpteenth time wanted to sneak in all of the old codgers without allowing them to sweat before the appointments committee in parliament. I can only imagine the bitchiness and blackmail going on behind close doors. Is daddy dear going to survive? Plus a few more useless ministries were created like that for Kampala, Bunyoro etc to add to that of Ethics and Karamoja. Why cant all of these just be departments in the same ministry if there really is any need to grant them a special status. Of course we know that one for Bunyoro was designed to distract them while their oil is carted away to enrich everybody else but Banyoro.  
   
Poor foreign journalists were confused today. They didnt know whether to go to Entebbe or to attend the boring ceremony at Kololo. The poor local stations were barred from showing anything but the kololo events. But the world has changed. SMS, twitter and FB gave upto date minute by minute accounts together with photo and video footage. The old heads in cabinet don't quite get it. this thing has got a life of its own. Its a medusa. If you cut one head off, it will sprout another five.  
   
As the French would say, a tout a l'heur
