# Why bundibugyo and Kabale should sack their politicians and recruit more doctors instead.

Monday, June 6, 2011 at 12:36am

   
Dear Nina,  
   
Today I feel great love for you! So I promise I will not mention the prime minster or that annoyance Twino! It will be just you and me, with the moon and the stars!  
   
I am glad you went beyond the rhetoric and propaganda in the NRM manifesto and [actually looked at what is happening on the ground](https://www.facebook.com/permalink.php?story_fbid=10150267828406259&id=712431258 ).  Ever since I started debating the issue of health services in Uganda on FB, none of the NRM debaters sent here by the government to "counteract opposition propaganda" has ever taken up the challenge! The challenge has always been that they visit a real hospital or health centre, speak to real patients or medical and nursing personnel and report their experience back here preferably with a comment as to how their findings compare with the official rhetoric! As you can see, things on the ground are not the same as the glossy reports by the government or the presidents rosy speeches! All of those challenged usually disappear and never come back or come back to a different topic while attempting to dismiss the challenge! The fact that it has stood for now almost a year tells one a lot about how un seriosly this government really takes the priorities of ordinary Ugandans!  
   
I still remember that very brusing first round you and I first had when [you challenged my views](http://ddembe.wordpress.com/2011/06/05/random-answers-on-health-in-ug/) on Mulago and Ugandan's health services. That we have now moved to the library and down to the ground is progress.   
   
The NRM has forgotten one thing -all politics is local. Your choice of Kabale demonstrates this. But the very fact that all politics is loval is why the delivery of services is important. Its why it makes very little sense that the NRM 'won' the last election with "a large majority" which in their opinion proves their "popularity"! But we all know that this election was won on money and blackmail but not real issues for the issues that are closest to the hearts of Ugandans are the very issues at which it sucks most!  
   
Your choice of Kabale reminds me of a girl who left Uganda about ten years ago. She has never come back and has no intention of ever doing so. I knew her at university. She was a very hard working student. She came from a middle class family, had grown up in an urban area and went to one of Uganda's elite girls schools. Following her internship (you see she is a doctor), she was posted to Kabale. There she endured hardship for the next 2 or 3 years in virtual servitude and says she did things she never ever thought she would ever have to do to survive. By the time she left, the local rural men who fancied themselves wealthy and sophisticated wanted to marry her as an extra wife or keep her as a mistress! She felt humiliated for the reason that these mocal village idiots thought she was within their reach was because they knew she was broke. That some of them had control over whether she got remunerated or not did not make things easier. For as you know, the MoH divested itself of responsibility for docotors and decentralised recruitment and salaries to districts. At some point her pay was 12 months in arrears. She believed that the local politicians and admininstrators deliberately manipulated her salary to keep her broke and dependent.   
   
Off the top of my head, I can give you a story from Fort Portal invloving a savedee who left after a year without a salary and having been forced to do things heis conscience could not live with, another who told me horror stories of operating in stone age conditions in Hoima -he left. And another who left Gulu after ten years having lived there at a time when most southerners would never ever consider crossing the Karuma. I can introduce you to people on FB who left Ugandan being owed wages for several months to a year or longer or others who were never delployed for months to years -they left and will not come back. They all have horror stories of working in primitive conditions, unpaid and unsupported. And when they hear you politicians trying to blame them for the inadequacies in a health system you do not even use, they just pack their bags and leave while the politicians continue to strut and posture for the cameras while shunning the same dilapidated health structures.  
   
I can see that Apollo has problems with discussing what he prefers to believe is NRM internal business. I have news for him -the emperor is naked. Health services are used by everybody and they are public business. Specifically the failure of the NRM to deliver even basic minimum care for 25 years is in the public domain and has got to be discussed. Refusal of the NRM to discuss these problems is like the proverbial ostrich burying its head in the sand -does not prevent it from getting eaten by predators!  
   
An Alice chimes in with her usual insensitivity! Why should doctors be bonded when no one else is being bonded? If we are going to bond doctors, then everyone else should be bonded to. Why is it OK for Alice to go off to the UK with her state funded degree and not for a doctor? As it is doctors in addition to spending more time on their training, working longer and more unfriendly hours, are one of few professionals who get posted to all sorts of places in Uganda without even relocation costs.  
   
Migration is an individual right for everyone regardless of profession. It is the role of the government to provide reasonable remuneration and employment not the role of doctors to subsidise government incompetence and politician ineptitude. https://www.facebook.com/note.php?note_id=469636102680 The invocation of selective patriotism is just simply blackmail!  
   
We have already demonstrated how the huge political administration at all levels is a drain on public resources while being unproductive. Simply halving the size of political leadership at all levels from the executive, parlaiment to districts through counties and down to the village would free enough resources to employ new medical and nursing staff.  
   
The question has been asked regarding what role RDC's, assistant RDC's, CAO's and the armies of local politicians do to justify their allowances. If you followed Stephen Twinoburyo's page in the last few days you will notice that the topic has been the cost of so called leaders and politicians and the opportunity cost in terms of service delivery. Today Ms Ssuuna posted an article showing that Kampala's politicians cost the rate payers 18 billion a year. Methinks Kampala City could save a lot of money by getting rid of all its local politicians and using that 18 billion to provide services!   
   
But the same could be said of lots of other places. Districts should get rid of the bulk of their semi literate councillors and self important chairmen and dliver services instead CAO's RDC's, assisteant RDC's in addition to LC V district chairmenand councillors, various other politicians at county and subcounty levels as well as villagers should be got rid of. Specificall the village LC's outlived their usefulness for they have no utility in terms of delivering services. All they do is to entrench the NRM in power being vehicles for patronage rather than vehicles for service delivery!  
   
Today someone introduced me to the concept of a captive economy. Essentially Uganda is an economy captive to vested interests including those of politicians and cronies of Museveni. This results in gross distortions, corruption and innefficiency that stunt development. Essentially Ugandans will have to liberate their economy from these vested interests if we wish to develop at all.  
   
Many years ago as a student I spent a lot of my time volunteering with cancer patients. I met a man who was a village teacher in Bundibugyo. His 8 year old son had cancer. Every two weeks this man travelled all the way from Bundibugyo with his son, in buses and taxis. He slept on the hospital floor while his son was in hospital and faithfully returned for the next treatment. He told me about the horrible journey through horrible roads. He told me aboyt the fact that his whole district had no doctors and how he wished that one could go and work there. His son survived as far as I know thanks to his fathers diligence.  
   
The following links connect to a story about a Dr Ssessanga who in 2008 was the only doctor in Bundibugyo even after the Ebola outbreak in 2007. In Feb 2011, it was reported that "Dr Steven Ssesanga, the lone doctor, who also serves as the medical superintendent, lost his father last week and left behind hordes of patients writhing in pain, some needing emergency care."  
   
Please note the sanctimonious tone of the article like it was Dr Ssessanga's fault that he was the only person willing to work in Bundibudgyo. In another article in April Dr Ssessanga states, "I am alone and I cannot attend to everyone at the same time,"  
   
"Sesanga, also the hospital superintendent, is the only doctor in the district. Apart from treating patients, he has to carry out administrative work.  
   
"I have very little time to rest. If I do, people will die," he says.  
   
Sesanga says Bundibugyo Hospital is the district's referral health facility, serving over 280,000 people from as far as the eastern Democratic Republic of Congo.  
   
However, the hospital is understaffed, operating at slightly above 50% of the required human resource.  
Ronald Mutegeki, the administrator, says of the 126 staff employed at the hospital, only 71 are qualified."  
   
Further in the same article it becomes obvious the government is not doing its job. "The hospital receives sh276m annually from the primary health care fund under the Ministry of Health. He says the hospital needs about sh5b annually to meet at least half of its costs. "  
   
I think that doctors like Ssessanga need a standing ovation as do many doctors who chose to work in Uganda despite the abuse, the poor remuneration, the poor facilites and job satisfaction.  
   
Now could anyone tell me why the number of councillors and overpaid political appointees in Bundibgyo shouldnt be halved to make way for more doctors and better pay for Ssessanga?  
   
Lastly this whole problem starts right from the top. In the early years of the NRM, Museveni stated that doctors will be paid a living wage when they become productive. He stated that he preferred to pay layers and revenue collection agents a living wage rather than doctors because "they were productive". I remember thinking at the time that the president didn't understand even basic high school commerce. My high school commerce taught me that the basic pillars of the productivity were land, labour and capital. My understanding is that a healthy workforce needs healthcare. if the president was not willing to pay the people who guaranteed the health of his workforce, how did he hope to boost productivity?  
   
More than twenty years later, he still doesnt get it! And all of the choir singers in the NRM like Apollo do not want to contradict him because that would be "airing the government dirty linen in the wrong forum"!!!

P.S. You can find more of my thoughts on Ugandan health services on my blog.

  


http://ddembe.wordpress.com/category/health/
