# If you guys are going to talk about patriotism, you need to start putting your money where your mouth is!^[https://www.facebook.com/note.php?created&&note_id=10150255236207681]
 
Monday, July 25, 2011 at 6:13pm


Dear Nina,  
   
Ha, nga ombuzeeko! Now that the Bakiga bank has borne the fruits of our NSSF money, you want to run away from me!!! Shiah, I shall not be very easy to shake off. I have got to eat some of that money too! Poor Jamwa, he shll continue to eat the dust as you and I drive off in our V8! I have started to shop around for gulfstreams! Do you know if Uncle Kaguta is selling his old one? I think that would be a good start for flying home every weekend to count the cows! Those poor workers who have been shouting themselves with nugu can continue to cry themselves to sleep!  
   
Talking about NSSF, I hear its up for a fire sale. All assets to the highest bidder. Who is going to speak on behalf of the workers? Kambogerere ko katono nange! What exactly do Lyomoki and the other so called workers MP's who have been in parliament for two and a half decades do? They are busy in bed sleeping with the NRM and getting fat while the people they are meant to speak for get robbed! One of these days the workers of this country need to wake up and remind them by booting them back to their villages who they are actually meant to be representing in the house! On the other hand, you and I can buy up plenty of assets with all of that new money brought in by the Arabs to the Bakiga bank! Am sure daddy will spring for a large soft loan now that he is all cashed up! Don't tell him I wrote bad things about Temangalo! And that sleepy house full of thieves called parliament will do nothing to stop us! They are too busy grabbing a piece of the loot for themselves.  
   
As it is its a free for all with everyone grabbing themselves a piece! Do you guys know something we don't? Is the country going to burn down? This is starting to look like a real fire sale kabissa! Mututemyeeko naffe! Kasiita me I have you on my side! When the peasants and great unwashed are crying foul, we shall just roll up the windows of our airconditioned SUV's! Better still why share the roads or what passes for roads with them -we shall just fly over their heads! Am asking the architect to add a helipad to the roof of our new house!  
   
When I saw the headline -NSSF up fr sale, I remembered NIC and the workers of Makerere University! Their insurance company was sold with no provision for their savings and now years later they do not know who to go to for their money! I can bet that this decision is going to come back to bite the workers of this country! I thought liberalisation meant the sector was bringing in new players rather than selling off NSSF! That civil servants would continue saving with NSSF while others would be allowed to save with private funds or that workers would have a choice of which fund to place their savings in. Now you guys are playing Russian roulette with the biggest caboodle of cash in this country!  
   
Uganda each day reminds one of the last days of the USSR where all of the biggest KGB guys got themselves a piece of the pie and overnight became multi-billionaires essentially by selling the state to themselves! These new Russian billionaires were in bed with the mafia and in most cases where the mafia. Is it any wonder that in Uganda we talk of a mafia that appears to control everything? But you know, I will not tire of warning you these paesants are going to wake up one morning and burn you in your beds! There is so much anger on the streets at the impunity displayed by this government!  
   
I hear that ka Namusisi girl was starting to get full of herself! After evicting that light weight seya, she is now spoiling for a fight with General Tinye! Has she never had of the Bahima boys? The 27 who fought thousands of Obote's evil hordees with their bare hands while she was hiding under the bed? Doesnt she know that she is supposed to tremble and kneel down before Tinye? How dare she evevn dream of dreaming of evicting him? Doesn't she know that the pigs are entitled to the best apples? I have to lend her my copy of the "Animal Farm" for she seems to have missed it in her education! What ka school did she go to? Simanyi she went to a UPE school! Someone needs to remind her that the pigs are the brain workers and are entitled to the apples while they work very hard sacrificing in luxury so that the rest of us can enjoy our sleep in abject poverty! Afande Tinye very quickly put her in her place and told her he would arrest her if she dared go to evict him! What is a mere title deed in the face of such patriotism?  
   
I think president Kaguta is challenged in mathematics! Mbu he told the teachers that an increment of 60,000 or 30% is "subversive to national development"! Oh, the fancy words that the bourgoeisie leaders of this country use to hoodwink the workers! There are 132,000 teachers. The 20 million shillings to 400 MP's as a bribe to pass the 650 billion shillings for the presidents election slush fund and the "Kabaka muzzling bill" alone is enough to pay 133,333 Ush's each! Being they are all so sleepy to have worked this long eating patriotism and air while the pigs roll in gold dust, am sure they could be convinced to accept less! But instead of negotiating with the teachers, the junior Education Minister Dr Kamanda Bataringaya said what the President said is final and the teachers should get back to work. "If they don't want to work it is up to them. No one will tie them to work. I am sure not all teachers will strike. We all know that". We all know that pigs are arrogant, but even this takes the cake! It beats Afande Kayihura's pronouncements before W2W! See how humilated he ended up! Can I predict that Dr Bataringaya will be the tinder that sets off another conflagration! People tell you that 200,000 cannot feed them for a month something very obvious to you and all you have for them is arrogance!  
   
Now for Uncle Kaguta, he is really on a roll with this "subversive" business. So if increasing the teachers pay by a meagre 60,000 is subversive for the economy does that mean that teachers taking industrial action are all going to be charged with economic crimes, a non bailable offence and jailed for six months in Kaguta's Uganda? Marchiavelli said it well -men willingly change their rulers not knowing that they are merely exchanging one tyrant for another! Have you seen the state house budget?  
   
   
* Special meals and drinks -- Shs1.3 billion * Donations -- Shs6.1 billion  
* Buying Medals -- Shs8.6 billion * Maintaining State House Entebbe Shs6.2b  
* Welfare and Entertainment -- Shs3.1 billion * Allowances -- Shs10.3 billion  
* Travel abroad -- Shs3.8 billion * Printing and photocopying -- Shs239.6m  
* Newspapers -- Shs89 million * Buying new vehicles -- Shs5.2 billion  
* Workshops and Seminars -- Shs70 million * President's inland travel -- Shs14.8 billion  
* Vehicle maintenance -- Shs3.5 billion * Classified expenditures -- Shs6.3 billion  
* Hosting Cabinet meetings Shs2.3 billion * Patriotism clubs -- Shs3.5 billion  
* Media/mobilisation/RDCs -- Shs3.9 billion * Supply of goods and services Shs3 billion  
* New furniture and fixes -- Shs200 million * National Patriotism Secretariat -- Shs4b  
* IT based economic monitoring -- Shs1.5b * Consultative meetings -- Shs800 million  
* RDCs, CAOs & LC5s meetings -- Shs500m  
   
Now before we even analyse these items, we have to be clear that this budget does not include the budgets of the Presidents office which is separate from that of State house. It also does not include the Ministry for the presidency or the Minister for Information and National Guidance (patriotism) as well as the minister for Finance! Isnt there a Minster for Cabinet affairs too?  
   
The reason I bring up these ministries is the degree of duplication in the State house budget for issues that should be already provided for in other areas. Who exactly makes up these budgets? Did they too attend a UPE school? WHy is economic monitoring in presidents office and not in Finance? Patriotism clubs and Medals between them almost 17 billion! Thats a salary increment of 30% for all of Uganda's teachers for 3 years! If medals cost 8.6 billion, they should instead use the money to pay teachers. Me I will print out a certificate for each medalist for them to hang on their wall at my own cost! Why is special meals and drinks 1.3 billion separate from welfare and entertainment? Just serve the guests mwenge bigere and tell them thats the finest in the land and they will be just as happy and go home with a new experience too! You can thrown in muramba and kwete if you want to be politically correct and practice regional balancing! MAintaining state house alone costs 6.2 billion enough to pay another year of teachers salaries! Donations 6.1 billion can pay another year of teachers salaries as can classified exepnditure whatever that is! You get the point! Just cutting on the state house budget alone in this one year can give the teachers their 30% salary increment for the next 5 years! How then can Kaguta say it is impossible. That does not include the 6.5 billion already used to bribe MP's in the 8th parliament or the other 6.5 billion used to bribe LC's prior to the last election which can each pay a year of salaries! Not to mention the obscene amounts paid to the MP's in the 9th parliament or the amounst to be paid like 192 million each for a vehicle! Why faced with such figures should teachers really continue to listen to the bulshit fed to them?  
   
Now those Americans have been eavesdropping on our love letters! Mbu they just found out that Museveni's succession is a threat to stability! And that Museveni needs to manage his retirement! That there is a project Muhoozi and that your daddy stands in his way! In addition that Uncle Kuteesa also has ideas of succeeding! I need to send them a bill for my services as all of that was clearly stolen from my letters without attribution! Did they ever hear about a little word called plagiarism?  
   
If you guys are going to talk about patriotism, you need to start putting your money where your mouth is! I warned you that your victory would be a pyrrhic one and so far, I can claim to have been a seer for everything I prophesied has come to pass!
