# Nina -why can't Amama lead the NRM and this country?

Saturday, May 7, 2011 at 11:55pm


Dear Nina,  
   
Its been a few days since my last letter. You know unlike some of you who were born into the movement, some of us have to work for our keep. Big contracts do not fall our way, you know. I know you have been ignoring my letters. Is it because I was not nice to daddy dear? I hope I did not bruise him too much when I brought up Temangalo. You know Temangalo was a blot on a man who had hitherto kept his nose out of scandal. That of course does not mean that nothing was happening behind closed doors but as you know image is everything. I even got your sister Rachel distressed and have had my friend Patu unhappy with me for a while now.  
   
I had promised I wouldn't mention daddy dear today, but I could not restrain myself. Actually haven't in a while. I do sometimes wonder what he thinks of his very selfish friend who has refused to share the chair with him. Binaisa said that "entebbe ewooma". I must say that I admire him for his blind loyalty. I cannot imagine maintaining loyalty to a man who only wishes to eat alone. Didn't he use to be considered to be second in the queue? By the time Kaguta is through and hands over to his son, I wonder where the Mbabazi's will be in the queue. When you guys claim Museveni is the only man with a vision, do you actually believe yourselves? Do you frankly see any reason why your father Temangalo aside, cannot lead the NRM or this country? You know a true revolution is like a relay -the baton has got to be handed on for the revolution to survive.  
   
You know your dad is not the only man who has found himself in this position. Gordon Brown over in the UK had to jostle in an unseemly manner and expose the party dirty linen when his pal Tony Blair got too intoxicated with being in the limelight. Ultimately the party faithful decided Tony had eaten enough things and needed to go. Nowadays he occupies himself advising strongmen like Kagame and now deposed dictators like Mubarak.  
   
John Howard, the third member of the "War against Terror" trio who posed as the 'leaders of the free world' against Saddam and terrorism also had a lady in waiting who got tired after 13 years. Can you imagine a paltry 13 years. So Peter Costello, that was his name, -he too rocked the boat and challenged Mr Howard. The party faithful fearful of losing power if John Howard did not lead them, failed Mr Costello but the people decided that Mr Howard was being greedy and terminated him. You have watched those shows on TV where they terminate players. Interestingly Australia has no term limits and neither does the UK yet no one stays in power for 25 years. Do they know something that Ugandans do not or are Ugandan figures being massaged? Or is it just ignorance at work in Uganda? No truly democratic nation even without term limits has got one leader in power for 25 years going on thirty.  
   
   
You know the above two men Gordon Brown and Peter Costello in the UK and Australia respectively alleged that there was a queue and Tony Blair and John Howard were refusing to leave the queue so others could join in and share the cake too. They both even said that there was a gentlemans agreement that the incumbent was now reneging on. The constitution says that bukenya is second in line yet the party says your daddy is second in line. The whole country knows that the real second in line is Col. Muhoozi. So tell me, how does it work? I hear the NRM had a queue. As a matter of fact I remember your father accusing Besigye of violating the code and trying to jump the queue where presumably he too was in line. At the time I thought he was protecting his own position in the queue. But as time goes by, it becomes more and more obvious that Kaguta has no intention of following the queue. Instead there is a good chance they may even skip the queue like in Eyadema land and annoint the son, Muhoozi. I hope you are on good terms having gone to Nottingham like him and being brought up in the family business. But thats not the reason why I brought this up. I have asked you before what the mechanism for retiring Museveni in the publics best interest is.  
   
   
You see the man is tired but he does not seem to be able to see it. Plus this personalising of the state is quite irksome. The whole clan is in the government -is this some sort of family business? Now I hear that you too are being asked funny questions about whether you work for the family firm. It must be that Stephen. He has been trying to compete with me. He doesn't like the fact that my letters have been so persuasive. Naye am getting lost -my real question is what is the mechanism for challenging Museveni? The only man who ever tried has been harrassed, charged with having HIV which I didnt know was a crime, charged with having committed rape with a consenting adult -that sounds like an oxymoron, been run off to exile, and been beaten and humiliated puting him ino hospital for a week! Am starting to think thats why your father is afraid of challenging Kaguta for surely he does not plan to be a lady in waiting all of his life. I hear you were counting your chickens before they hatched and the wikileaks idiots leaked the news. I would be very careful if I were you and make sure I have on some leggings underneath. You never know these people might decide to bundle you onto the back of a pick up and worse still shove you under the seat for plotting treason. The other day they were trying to undress Ingrid Turinawe in front of parliament! You see how they treated Besigye the man they spent five years with in the bush fighting mosquitos. Actually he was the one saving them from the mosquitoes with his busawo obutendeke! How do you think they would treat those of you who in their opinion were in Nairobi and Sweden eating sausages while they were suffering? You could see real nugu and kamanyiro in their actions. I think President Museveni calls it "bukyayi"!  
   
Now there is that woman Janet Kataha. First she annoys the Rubindi's, almost causing that woman Alice to go on strike, then she fails to show compassion to the nation and now she is questioning Besigye's leadership skills. The things that Alice was saying after the elections were treasonous -I hope you reported her to the security boss. But I forget, you too were saying funny things at the time. What was it with Hope's losing? Was she created in office that she was not allowed to lose? Is she one of these people who think that they were born in cabinet or parliament? I got the impression that there was some family linen being laundered in public. I have actually heard that there maybe some interesting family linen there to do with a menage a trois in cabinet but am not one to repeat rumours! You must tell me more about that some day. Surely its no longer a menage a trois when there are four people involved -thats a menage a quatre!  
   
But I must get back to this Kataha woman and her claim that Besigye had no leadership skills. People really have very short memories and do not know how far they have come. Baganda say, that "akivaamu yakiyita ekyato". He who has finished the crossing is the only one who can afford to call it a crap ferry. Has she really forgotten how her husband looked in 1986. In ill fitting long sleeved shirts under a kaunda suit, watch on the right hand and gum boots? He sure didn't look presidential at all. Only those of us who were young and idealistic, some would say naive actually believed in him while the grown ups were busy fighting him! All that government by trial and error like batter trade? All the getting ripped off by petty businessmen from the streets of Mumbai and jumped up "nouveau riche" goatherds without due diligence. Even she herself was claimed to have been coached through university, with claims of her dissertation having been written by a "mu cuba". Her getting a leg up in the family business through nepotism -isn't that what the NRM used to call it when one in power employed all of his relatives in government? I hear Kaguta said she was the only one patriotic enough to want to go to Karamoja. Me I would be quite happy with the pajero nebigenderako considering I wouldn't even have to live there! The problem with people who get to where they are because of family "know who" is they start to delude themselves that their positions are by virtue of their superior intelligence, acumen and leadership skills. So someone gets elevated from being a housewife to being a minster simply because she is married to a president and she suddenly can see who has and who does not have leadership skills?  
   
Did you see those dishonourable ministers in parliament? I wonder what happened to Minister Kasaija? Such a nice man. When I watched him presenting that doctored video, I was reminded of another nice man presenting a doctored video full of lies to the UN security council, Gen Collin Powell. The poor man has since gone underground and can no longer hold his head up because he failed to resist orders from above and show leadership. This business of following orders from above is going to destroy a lot of good people. I notice you tried to spin things a different way and blame junior IT boys who doctored a video and briefed their bosses including the president falsely. But the problem with this autocratic behaviour is that people start to tell you what they think you want to hear -you know that old story about the emperor and his cloths! So you guys want to hear that Besigye is desperate because he received lots of money from abroad and has to account for it. And that he had hooligans camped in his home whom he brought out to terrorise the people. I even read the spy chief Tinyefunza repeating this! So much for security in this country! How can you depend on people who are delusional? Even President Museveni dismissed their assertions as crap! Do you guys really believe yourselves? How about all of those billions Museveni spent on getting re elected from the tax payers pocket? Is he going to account for it? At least whoever gave Besigye money knew that he could lose while Ugandans money was taken without their permission.  
   
Now I have been following this debate of where you lie. Apparently people are not convinced you are really setting yourself up as the conscience of the NRM. They think that you are the SG's daughter through and through and on assignment here. They cite a big corner office and a big car as evidence. I told you you were going to have to do a Buddha to attain true salvation. People cannot trust you when you have a big corner office and a big land cruiser. Jesus said it too -it is harder for a rich man to enter the kingdom of heaven than for a camel to pass through the eye of a needle. To my simple mind he actually said it was impossible! We know all of the people who have those things -the big cars and the big corner offices and military guards are not friends of Ugandans. They all belong to la famiglia. I cannot blame you anyway as in Uganda, all of the cake is owned and eaten by one family and their house staff -the butlers, the maids, the cleaners and the enforcers etc. I do wonder sometimes, if Bukenya is the butler, where do the others fall -I won't mention any names.  
   
I told you before, if you had ignored Uncle Besi and company, there would have been no chaos. Your people can assert all they like but the onus is upon them to prove that their prediction was right and until then Besigye and anyone else have the right to walk anywhere even if people are bound to follow them. I hear the other day Col. Muhoozi went into a nightclub. Now that is bound to cause some commotion but does it mean you are going to curtail his movements? Instead your people sent all of these rioting soldiers and policmen to ravage the towns and everyone in it. They committed economic sabotage. I wonder how much the government lost in taxes. Remember Lukyamuzi played hide and seek and got to his office without the world coming to an end, Otunnu walked to work with Afande Mutabazi's help and nothing happened -except Afande Kayihura sacked him, then redeployed him! Now I hear afande Muntu walked to his office and even got saluted by a policeman and Kampala is still standing while Mafabi too walked without a permit and again nothing happened. You should get a discount on all of those idle anti people machines you equipped the police with. Kayihura should really be charged with trying to bring down the government. At the very least charges of causing dissaffection among the public, "bukyayi" as president Museveni calls it, should be preferred. Am sure there is ample evidence.  
   
In the interests of time I will end my letter here. I will of course be awaiting your response. Please do not trust that Stephen chap.
