# A golden oldie; do you guys have any analysts?

Wednesday, May 11, 2011 at 7:29pm  


Dear Nina,  
   
A friend reminded me of this letter I sent to you after the elections. In it I predicted the exact scenario that would lead to protests in kampala. At the time you returned it to me return to sender.  
   
At the time I said, quote;  
   
"The question has been asked as to whether Uganda is ripe for the Jasmine revolution. I personally don't believe it is yet but I have no doubt that it will be! Uganda has all of the hallmarks but at the moment does not have equipoise! These elections are unlikely to be the trigger! https://www.facebook.com/note.php?note_id=10150092832897681 .  
   
Something else say Somalia spilling over into Uganda, another attack on the Kabaka or Omukama, A MISJUDGED HEAVY HANDED TREATMENT OF A PEACEFUL DEMONSTRATION or just about anything could trigger one. Certainly Otunnu cannot trigger one even though am sure he would love to! Only Museveni can prevent a Jasmine revolution by learning from Egypt and Tunisia and pre emptying it by making clear and activating his retirement plan!"  
   
http://www.facebook.com/notes/drew-ddembe/2011-elections-quick-thoughts/10150101608607681?notif_t=note_comment  
   
Do you guys really have any analysts? Because as it is I seem to be doing better than all of your overpaid hacks.  
   
You know that I do really have a soft spot for you. So I really hate to tell you I told you so. Butas usual you and your government always ignore good advice.  
   
While I am saying i told you so, I will remind you that I predicted riots once Kayihura announced his strategy for combatting those who sought to walk to work -and like robots programmed to fail, the NRM machinery proceeded to self destruct.  
   
http://www.facebook.com/notes/drew-ddembe/igps-press-conference-kayihura-needs-a-refresher-course-on-crowd-psychology-and-/10150150846997681
