# Paesants in suits should not be allowed to sign away Ugandans future!

Sunday, September 4, 2011 at 10:23am


Dear Nina,

Things are moving really fast! I knew your guys were way out of your depth and things would spiral out of control! These days, every new day brings a new surprise! I wonder whether Uncle Kaguta sleeps at all these days as it seems like everyone is on strike against him! And the only response is the old bush responses -we shall crush them!

I told you that daddy dear was handed a poisoned chalice! How he gets out of this one will determine whether daddy has a political future or not! I am sure that he too would like to sit in the chair but all evidence suggests that by the time Uncle Kaguta is through with him, he will be made to look incompetent like Nsibambi and Bukenya before him! That is if his loyalty is not rewarded by being dragged through the courts on corruption charges in order to insure that he never makes any political comeback! You know these too have now become a political tool to be used selectively against those that the president wishes to destroy or no longer finds useful! I hope daddy has got eyes in the back of his head!

I wonder how daddy dear is getting on with those Tullow people who 'reported' him to the American embassy and sought to have sanctions imposed against him for according to them being corrupt! You know Wikileaks outed the sneaky Tullow weasels who sought to manipulate the American embassy and American foreign policy in their favour by claiming that daddy had been bribed by another company against their interests! One wonders is American embassy policy in Kampala run by the interests of corporate interests? Is this not a form of corruption?

Of course the corruption and hypocrisy of Tullow is revealed in the fact that they used this piece of information for blackmail and leverage in their bid to gain an advantage against another company they claimed had bribed the prime minister! If they were really genuine, they should have turned over this information to our IGG for further investigation and charges! It is a pity that your incompetent NRM government continue to be pawns manipulated by these foreign companies and embassies for their gain at the expense of Ugandans!!!

The Bunyoro oficials are squabbling over a few peanuts thrown to them by Tullow! Shouldn't Tullow and Heritage be paying taxes instead of demeaning our people with peanuts as "charity"? Shouldnt they be paying suitable royalties when they start exploiting our oil? http://www.monitor.co.ug/News/National/-/688334/1229858/-/bjrxj4z/-/index.html

Shouldn't Ugandans be rising up against these predatory foreign businesses here to fleece off Ugandans?

How can a foreign company after making billions off Ugandan resources decline to pay capital gain tax?

Is there any country in the world where they would be llowed to operate without paying taxes? Did they bring any oil to Uganda?

Now our poor brethren in Bunyoro are squabbling over peanuts while the thieves in Tullow and Heritage bask in the reflected glow of being "donors"!!!

The poor Omukama was recently in London hat in hand seeking audience with Tullow officials. Shouldnt it be the other way round?

While the shareholders of Tullow and Heritage are already cashing in on Uganda's oil, Ugandans are yet to see a cent! And between them and out thieving and incompetent government, which has already spent the expected windfall on baubles and modern beads and mirrors aka fighter jets, Ugandans will never see a cent!

How does our government get away allowing foreigners to fleece Ugandans on its watch? How does Mehta get away without paying tax for 26 years while receiving government subsidy and is even offered more of our natural resources for his benefit? How did Umeme get away with the clauses in its contract that guarantee it earnings regardless of its performance while making it virtually impossible for the government to demand its compliance with the terms of its contract or terminate it of it failed to deliver as it has?

How does Tullow and Heritage even dare to suggest that they can make a profit of billions of dollars for their foreign shareholders but Ugandans whose oil and environmental health they are selling are not entitled to a cent?

And how does our government get away with allowing foreigners to get away with contracts that favour them even in something so clear as capital gains tax? Where is the ethics, the morality, the social justice in western companies coming to steal from third world people? For this type of corporate behaviour has got to be called what it is -robbery!

How will Africa ever develop when western companies continue to steal their resources in modern white collar crime?

Whoever signed up Uganda to these contracts with Tullow and Heritage that allow them to even argue over an issue like paying tax on their windfall really need to be sacked! Better still they should be sued for negligence and corruption! Politically, someone should pay for this glaring omission! Who allowed these companies to get away with including a clause that demanded that disputes would be arbitrated in London on Ugandan resources?

How do we continue to claim sovereignity when we cannot even demand taxes from foreigners exploiting us?

These kind of skewed relationships allow Europeans and Americans to continue posing as donors while failing to mention that if they did not put their corporate interests first and paid fair price for African resources as well as stopped propping up dictators who allowed them to get away with daylight robbery, Africans would be able to enjoy more benefit from their resources and depend less on their "charity"!

Tullow should continue to contribute to the Kingdom of Bunyoro as a part of its corporate and community responsibility! But their charity should be rejected if its at the price of not paying tax on capital gains made by exploiting Ugandan resources.

Ugandans need to take these issues seriously and demand that the government reveal the details of the oil contracts with these exploitative foreign raiders out to rob Ugandans. Ugandans should take a greater interest in how many foreign companies are not paying tax and name and shame them as well as sanction them!

This government has once again proven itself to be incompetent in allowing Ugandan interests to be overidden and be made subservient to those of foreigners!!!

As for the foreign western press that is itself an extension of western imperial and corporate interests, who are always warning Africans against dealing with China because it supposedly has lower ethical standards, where are they when such stories of exploitation by western companies break? Would a chinese company really be allowed to get away with refusing to pay capital gains to the tune of hundreds of millions of dollars (almost 500 million dollars) without it becoming a newsworthy item on BBC, FOX news or CNN?

Experience has shown that Ugandans cannot leave it to the peasants in suits in the NRM government to sign away our future in exploitative contracts to foreign companies!

Oil contracts need to be made public!
