# Random answers on health in UG.

Monday, January 10, 2011 at 7:26pm


> Nina says,  
   
_"I think Mugerwa was getting into this. I know for a fact that in California, US. All doctor's sit exams for their licenses each year before it is renewed. Do we do the same here? Who is responsible for that? I know docto...rs put in some pro bono hours a year and it serves as community service. Do we do the same here? I know doctors are easily sued for negligence abroad, is that the case here? What about medical arbitration? Inspection of hospital facilities? Investigation of medical misconduct? monitoring of drug distribution? Reporting systems to the police on certain patients that are treated? Are these all not part of the solution that Mugerwa is offering except he is calling them pressure groups? What do you want us to call such overseeing bodies that keep Ugandan doctors that work abroad in check? Should Museveni lead this or should we ask him to set it up if it is not there, hence educate him?"_

I will attempt to answer some of these questions for the sake of other participants even though I believe they were irrelevant.  
   
Recertification is not universal even in the US. Very few other places in the world practice recertification.  
   
Most rely on good training in medical schools, formal and structured postgraduate service and specialty/subspecialty training as well as good post spcialisation continuous education which is structured with GP's and specialists being required to submit evidence of continuing education including attending workshops, conferences, journal clubs and formal post graduate/graduate courses in relevant subjects.  
   
There are arguments as to which system is the best but the rest of the world is not rushing to emulate California. Uganda has no system for recertification.  
   
Pro bono is a legal term more specific to law than to medicine. There is no requirement for voluntary work but many doctors do so. Some will offer treatment to disadvantaged populations others will go off to third world destinations to offer their services.  
   
In Uganda the relevant paediatrics, surgical and physicians professional associations do organise upcountry 'clinics'. These are collegial activities where colleagues go along for the fun and also render a service to a community such as free surgery or free checkups and treatment.  
   
Quite frankly virtually every doctor in Uganda working in a public hospital or clinic who does not demand money from his patients illegally is subsidising the public health system as they are poorly remunerated, put in unpaid overtime all of the time and sometimes even contribute financially to the care of a patient or fuelling their cars or private phones used for official work.  
   
There is nothing barring doctors getting sued in uganda save a relatively ignorant population that does not know its own rights as well as what constitutes quality care. Even those who believe they know probably have no clue what they are talking about. For example your example of prostate cancer in your grandpa that was allegedly missed until five years later when it was seen in retrospect may not be as clear cut as you think it is.  
   
I doubt that many of our lawyers are competent at pursuing medical negligence lawsuits and neither can their patients afford them. Quite frankly our lawyers are too confortable making ten percent off drawing up easy papers. However the advent of mango tree universities churning out lawyers by the hundreds may change that as many will end up redundant and have to find new niches. There are however no amulances to chase so we will have to find another name for 'ambulance chasers" as these lawyers are called.  
   
If you ask me Ugandan patients should sue. But I would advise them to go for the hospitals and the government. these are government hospitals. If a patient dies, the doctor and the system have to be sued. if the doctor failed to provide care due to the negligence of his employer, then the hospital has to pay. There is a case for numerous class action suits by Ugandan patients against the government hospitals and the government. And trust me the dotors if this were tested in court will get out of it as many of the so called negligence is really a systemic problem due to them not being facilitated to practice their profession fully.  
   
As for medical arbitration I beleive this is a completely undeveloped area. Patient liaison and support may be easier to set up. Specifically someone needs to speak for all those patients on Mulago's floor. Someone with enough knowledge to advocate for them for many really have no idea that they are being shafted. I doubt that some of the managers know that either!!!  
   
Medical facilities are inspected and "certified" as compliant with specific set out criteria. So a hospital can be certified as fit to take on interns for training if they have a certain number of consultants in place to supervise them, have certain facilities of a preset standard, have a certain staffing level at predetermined grades, does a certain number of procedures, provides a certain level of training etc. There is no such formal certification system in Uganda. The closest is the project christine worked in.  
   
Medical misconduct can be pursued in uganda. All doctors are licences by the Uganda Medical Board. Having a medical degree is not a license to practice medicine.  
   
It is possible for you to look up cases brought by the board against the proprietor of Case clinic for example a few years ago. in your circles every second or third person probably has been to Case clinic or know the proprietor and may have heard about this case. the board can withdraw licenses, suspend doctors from practice or limit their practice or demand practice under supervision. It can also recommend criminal charges for criminal negligence. The offices are in Wandegeya the last time I checked.See More  
   
Criminal charges can also be brought if the problem falls under criminal law say abortion, sexual assault, homicide etc.  
   
Monitoring of drug distribution is the job of the Ministry of Health and the government medical stores. If you google them, you wiii find that they have spent obscene amount of money on computerised warehousing software for the National Medical Stores. The deal for upgrading a software system that was working well and was less than five years old a few years ago cost a ridiculous amount of money. Personally I thought that there was a problem with the whole deal.  
   
Local drug distribution, and dispensing within a hospital is controlled by the pharmacy. Nurses administer against a prescription signed by a doctor and have to maintain records for the pharmacy to ensure accountability. Doctors have no contact at all with drugs within this system except to prescribe them. In a tertiary hospital like Mulago that is the case. In upcountry stations it is a little bit more complicated as many times the only doctor is also the medical superintendant who has to travel all of the way to entebbe to do inane things like sign for drugs and transport them from Entebbe to kotido in the only 'ambulance' the hospital owns!  
   
In the British system, doctors report deaths to a coroner if there is a problem or evidence of malpractice. Mandatory reporting of certain cases following preset guidelines has to be put in place. All other straight forward cases where the cause of death is clear receive a death certficate by a member of the team that looked after the patient. if the case is unclear then a post mortem is done particularly if there is suspicion of foul play.  
   
Where systems work all cases where a patient dies within a certain number of days after a major operation or procedure is considered as reportable and the doctor cannot issue a death certificate without discussing the case with the coroner first. I think the equivalent in Uganda is the police surgeon!  
   
Unfortunately in Uganda upcountry the local medical officer also acts as the police surgeon when required to so am not sure how you are going to get him to review himself when he is the only doctor in the county.  
   
The police only gets involved in cases that fall under criminal law. Cases of malpractice, professional misconduct and negligence unless they cause bodily harm or death are cases for civil litigation or referral to the medical board.  
   
Doctors abroad are not kept in check by "pressure groups". Primarily the first check is training and specialist certfication in certfied units that are well supervised and perform a minimum number and range of procedures. Hospitals have their code of conduct and Health authorities have their codes too. Ethics is a part of medical training specifically medical ethics and professional conduct. licesnsing Boards oversea licensing and hear professional misconduct. hospitals have patient liaison and patient advocates who hear patient grievances and liaise with the teams. And insurance companies organise additional training in risk management to their client (doctors) to avoid law suits. Most of all the system in which doctors work has got to provide a framework in which they can practice safe medicine else the instituion gets sued. Certfication boards will not certify a hospital unless it comlies with minimum regulations else it will be shut down. Patient advocacy groups may advocate but they are an additional layer not the primary controllers of quality. Most of all hospitals know they will get sued if their doctors kill a patient and it is found that the system contibuted to the death. The primary role of setting up and supervising these syetms is the government and it cannot pass on this responsibility to anyone else.  
   
In any functioning organisation or government the buck stops with the boss. thats how they justify their huge pay and bonuses. it all means that when things go wrong, again they take the fall!  
   
Thats why in many democracies an investigation revealing excess deaths in a government hospital due to systemic failures and the negligence calls for the resignation of the Health Minister for failing in their dupervisory roles.  
   
Now if people tell me that we have such a big problem and we cannot and should not place the blame on the people who have been running the government not for one but for 25 years, then i remain flabbergasted!  
   
Even after a catalogue of incompetence and corruption in the GAVI scandals and numerous other flawed deals let alone all of the excess mortality and shortages!  
   
If a president believes that giving each MP 20 million for the nebulous and ill defined 'NDAADS" activities is better than making a grant to say Uganda Cancer Institute then we really are in trouble!!! Now the president is frantically making plans to offer new markets to upcountry areas as a part of his campaign donations!!!  
   
The people to educate Museveni have always been there but he believes in teaching them! Many years ago museveni said doctors will get a living wage when they become "productive". That he preferred to pay lawyers and tax collectors because they were productive!!! So junior lawyers and junior tax collectors made and syill make more than a medical consultant with more than a decade of training and several decades of experience! That said it all. If an economist cannot see a link between an unhealthy workforce and production one wonders. Who guarantees your workforce?  
   
And if they believe the solution is to jail a few doctors as "an example" and place ignorant cadres with half their IQ's to "supervise them" (read bully them), then I pity poor Ugandans!  
   
Its time for politicians to grow ears and listen to the people who guarantee their "success"! No solution to health that bypasses doctors is going to work! And certainly one that bullies them will fail!  
   
God save this country!
