# Those who cannot learn from history, are doomed to repeat it!

Thursday, May 19, 2011 at 12:17pm


Dear Nina,  
   
Now you are about to be declared my muse.  
   
Todays letter has been inspired by two quotes from your FB page. One is about an event in Uganda's history and a [letter written in 1967](https://www.facebook.com/notes/nina-mbabazi/history-most-certainly-is-repeating-itself-transition-magazine-1967/10150203096154449) about events that perfectly mirror Uganda today. Given that those events led to chaos and disaster as well as hundreds of thousands of deaths and we are yet to recover, it behooves everyone to read that letter and the events carefully. 
   
The 1967 constitution was illegal. It was written by two people in what Binaisa boasts was one night. It was introduced to a compromised (an illegal parliament) that was detained till they passed it. It was called the famous "pigeon hole" constitution!  
   
The KY-UPC post independence government was a constituted as a coalition in the Westminster tradition. When differences emerged in 1966, it should have been resolved and the parties should have returned to the electorate to get fresh mandate for their new ideas and a new government.  
   
Instead, Obote staged a parliamentary coup, deposed and exiled  the head of state, unilaterally declared a republic without seeking fresh mandate to do so and declared a state of emergency. He subsequently abrogated the constitution and imposed the pigeon hole constitution. He then arrested and detained dissenting citizens and politicians. In the events of 1966 when sections of the country specifically in Buganda rose up gainst him in unarmed protests, he ordered them beaten and shot. As you are ware, Museveni has already repeated these events despite declaring when he came to power that Obote was wrong in all of his brutal actions in 1966 despite provocation.  
   
This in effect made Obote Uganda's first dictator. He went on to rule without seeking fresh mandate until he was deposed by his pet bulldog Idi Amin in 1971.  
   
The main highlight of the 1967 constitution was consolidation of power into one mans hands. The lead up to that event was the destruction of other power centres the biggest of whom was the social giant, the Kabaka of Buganda. Other power centres like the opposition were detained and imprisoned. Of note is that Museveni passed the "Kabaka muzzling bill" in a rushed and incompetent process soon after bribing members of parliament, recalling them after recess for elections and rushing through the debates and extending the session into the late evening until it was passed -all in one day. This bill was primarily targetd at another social giant, the present Kabaka who happens to be the son of the previous "social giant" Obote's actions were targeted at.  
   
The powers of the presidency were made more absolute. All checks and balances on the power of the presidency were effectively removed. This needs to be remedied to begin with by returning term limits.  
   
The 1995 constitution retained the same principle of an over arching overiding presidency with little or no checks on his power. In the presence of a toothless parliament not immune to financial and political coercion and the winner take all politics that can doom one politician to a life of political exile from the eating table and the exercise of power for life in what are virtually one party states in all but name maintained by political patronage using the power of the states significant resources put at the disposal of one man and his interests, its no wonder that its virtually impossible to dislodge a sitting president through the ballot. Virtually all politicians are too busy jumping over their mothers to get to the table while the rest who maintain a principled stand are humiliated and beaten up when they are not busy fighting state harrassment through the courts using repressive laws like sedition laws and other laws targeting political activism.  
   
Now the bar is being set even lower to cover nebulous economic crimes, vague definitions of rioting and terrorism and even more vague definitions of treason! Basic freedoms like the right to protest or the simple rights to habeas corpus or the right to bail as well as the right to the presumption of innocence are being attacked.  
   
There is a need to cut down on the powers of the presidency and bring the president back to heel in the service of the people. Like Mbeki, the people and the party should have a mechanism in which a president who becomes a serious liability to the state can be relieved of his duties. Museveni has become a liability to both the NRM as well as this country.  
   
In the case of Mbeki, his long running legal battles with Jacob Zuma were interpreted as continuing harrassment and misuse of the states resources and the powers of the presidency. He was forced to walk the plank and had to resign after a national ANC meeting. The numbers were against him so he had to comply. He is now a private citizen.  
   
In Australia when Prime Minister Kevin Rudd threatened the future electoral chances of his party through his high handedness and alienation of their voters in their local constituencies, a hastily called meeting of the party caucus saw his deputy challenge him behind closed doors. After showing him she had the numbers to deliver him a devastating defeat in the party caucus, he resigned the same day and she resumed power, then called an election within a few months. Kevin Rudd had defeated the powerfull and long running John Howard.  
   
In the UK, when Tony Blair grew too big for his boots, he was forced to a showdown and had to step down. He now advises third world dictators for a living but the recent overthrow of Mubarak should teach him some lessons.  
   
The point is that these countries that do not even have term limits have got mechanisms for controlling their leaders. In our case short of a major stroke, our leaders will continue abusing our patience until we have to go through a destructive war to remove them or their children from the centre of our politics. We keep leaders long enough for their children and sometimes even grandchildren to get a foot hold and even a stranglehold on political power creating political dynasties of parasites.  
   
In this letter to Nina a few days ago I suggested that Besigye, Mao or Otunnu as presidents in a system without a functioning opposition as well as other semi autonomous and independent institutions of government and civil bodies would be a dictator too. https://www.facebook.com/note.php?note_id=10150194162237681 They would be able to rule virtually unchallenged for decades, would have the states military and police at the beck and call to beat up opposition, and virtually be able to order the central bank governor to print money so they can buy votes to maintain the semblance of elections that are just window dressing to keep their handlers in the west happy. Using the states considerable resources in a state in a system of patronage that ensures that ones fortunes depend on their allegiance to the state as well as creating a class of cronies and relatives through nepotism reliant on the state ensures that there will be enough vested interests as well as enough fear of change due to the fear of prosecution or losing the lucrative contracts to a new set of political cronies ensures tht there will be people virtually willing to commit murder to maintain the staus quo.  
   
But there is a point when the disenfranchised achieve the numbers and enough awakening of conscience and awareness to demand their rights.  
   
What we are seeing right now is that awakening in some way ironically stimulated by the states barbaric behaviour in the last few weeks.  
   
What this letter shows is that we have learnt very little from the events of 1966/67 that led us to the chaos and wars that have characterised Uganda todateAs for Museveni, he is very much a product of those times. Museveni was trained by Obote. In many ways he has now converged with his teacher. This letter was written around the time that Museveni was working with UPC/GSU/Presidents office.  
   
   
The second quote from your FB page is of words attributed to Napoleon Bonaparte. He apparently said that, "Never interrupt your enemy while he's making a mistake. That's bad manners."  
   
I will continue to exercise bad manners and interrupt you and your uncles while you are all making a mistake. the mistake of continuing to allow one man to continue deluding himself that he is indispensable to the stability and future of Uganda despite increasing evidence that he risks taking our country back four decades!  
   
Sir Winston Churchil paraphrased George Santayana, a spanish philosopher, when he said, "Those who cannot learn from history are doomed to repeat it!". George Santayana's original quote was, "Those who cannot remember the past are condemned to repeat it."
