# Opposition politics, think tanks and national conferences.

Sunday, June 12, 2011 at 11:25am


Dear Nina,  
   
Todays letter was developed from my responses to an chat online with a concerned Ugandan Nate Muwonge who engaged me in a debate. As a member of Ugana's younger demographic he wished to get my opinions on a number of issues regarding Ugandan politics. i explained to him that I am not a politician and are more interested in social issues. That my comments on politics come from the fact that social issues are largely determined by the prevailing politics as well as the priorities of the ruling politicians. Uganda's social services are in a very poor state which pretty much summarises the quality of our current political leadership specifically the NRM! that if Ugandans can be more aware of the link between political leadership and social services, they will be able to vote more widely.  
   
The discussion of course included the quality of our current political opposition! Their willingness to sacrifice their electorates hopes on the alter of self interest and allowances while Ugandans are crying about expensive government has pretty much put a spotlight on them!  
   
Uganda's opposition politicians come from the same stock as the ruling politicians they are just jostling for power so they too can eat or transfer the eating to their own village.  
   
The current party's in their present form including the NRM, all need to be shaken up from the grassroots.  
   
The current party's in their present form all need to be shaken up from the grassroots. New realignments and new political formations will need to be discussed and old politicians who are not flexible will need to be thrown out. this should be similar to what happened in the late 50′s resulting in the formation of UPC and the other dominant, now not so dominant political parties.  
   
A whole generation is passing by with the NRM dominated by old politicians who have failed to deliver and who are not trained to deliver in a modern world hogging the limelight. This is demonstrated quite clearly in the lack of vision displayed by Museveni in appointing his new cabinet. That he proposed people like Sebagala and Kakooza Mutaale is the height of arrogance and contempt for Ugandans. That people withour requisite basic qualifications for the posts of minister were even proposed and appeared before the vetting committee demonstrates a lack of due diligence that is amazing! One wonders what the presidents office does with all of that money spent on it. That he failed to respond to Ugandans concerns about public expenditure and still appointed a bloated executive with redundancies and duplications pandering to personal interests is an insult to Ugandans as is appointing people with tainted histories. How about appointing as Min of Justice a man with a history of contempt for the law? Museveni is out of touch and prolonged incumbency have made him more and more arrogant and careless. it has also demonstrated his short comings and lack of preparation for leadership in a progressive and forward looking Uganda. No wonder he spends so much time trying to keep us looking at the past rather than forward to the future.  
   
Mao's generation of politicians risk completely missing out on leadership as Museveni persists with his plans for life presidency! When I say Mao's generation, I include the NRM's younger generation of politicians heading for mid life including yourself.  
   
Mao will have to make decisions regarding his future and whether DP is the right vehicle for his political aspirations. DP appears to be destroying itself from within as is UPC. Otunnu has to go back to basics and connect with the masses or apply for another UN job. While his CV may get him another UN job, it is not going to help him connect with the masses unless he tells them what they want to hear -that he represents the change they want to see!  
   
We are saddled with political dinosaurs who like Kajura and Kategaya demonstrate in public meetings are always sleeping at the wheel! Why would someone return Moses ali? Surely is it not an insult to West Nile that no one younger and more skilled was considered worthy of replacing him even if we all subscribed to theis regional balancing crap? Ditto the ministry of Karamoja which should not exist in my opinion that the best person for the job is the presidents wife from Nyabushoozi who does not have the slightest clue what their needs and culture is? i think that ministries like Ethics, Karamoja, national guidance, Kampala, Luwero and bunyoro should have been scrapped and demoted to departments! Ministers of state should have been scrapped and Permanent secretaries and undersecretaries strengthened with suitably trained technocrats while obvious duplications of minstries such as securit and internal affairs or defence should have been amalgamated and the number of political sycophants in these posts slashed together with the budget spent on them!  
   
Besigye has been consistent even when he has suffered personal injury in standing up to his former boss. In many ways his anger reminds me of Gbabo who for more than a decade suffered persecution, beatings and imprisonment but when he finally got into power, acted just the same as his predecessors due to his personal enmosity for Ouatara who was a part of his predecessors government! Thats why I believe that he too would misuse power if he came into a country like ours where the president has unlimited powers and terms.  
   
While Besigye's quest may be too personal for some, his potential successors within the FDC like Muntu have failed to step into Besigye's boots to take the initiative and leadership. Anne Mugisha wants the FDC slot in 2016 but all signs are that she will not get it. Things appear to have been good until she hit the ground and waded into FDC internal politics! I remembered her article castigating Betty Kamya for addressing party issues "in the wrong forum" when she too was crying "foul" in the wrong forum after getting rigged out of Nakakwa by her own party. She subsequently lost in Mbarara and admitted that her party simply was not prepared enough, something I had suggested to her before but she dismissed! Am afraid that this as well as the fact that she took on her party leadership and challenged them in a country and party that prefered behind the scenes arrangements may jeopardise her bid for party presidency in 2016. In many ways, one can see her going out like Kamya, sacrificed on the alter of self interests and a 'twalwana' mentality that appears to be shared by FDC and NRM. That because they have been in the trenches against Museveni, some individuals within the FDC feel "entitled". This bars them from forming new alliances. Can you imagine where the democrats would be if they had failed to recognise the potential within Obama an outsider?  
   
As a female politician there is again a "glass ceiling" effect and too many battles on too many fronts within the FDC and W2W may have given Nandala a boost. At the end of the day, tribal politics will unravel it all. Is it possible that Nandala may emerge ahead of Besigye, Mugisha and Muntu in 2016? Latigo ended up being a dud so Nandala is not there yet and will have to work very hard building consensus in the next few years!  
   
Museveni has outlived his usefulness even to the NRM. While most of his men are tainted with scandal and corruption amking the succession question a hard choice. His succession plans for Muhoozi will need to be shelved unless he wishes for his son to spend all of his time fighting destructive wars. The NRM have been in power for 25 years and failed to deliver so it makes no sense to retain them. If the NRM is to survive, it will need to reorganise itself seriously over the next five years but again the recent cabinet appointments suggest that it is going to be business as usual!  
   
They would have to achieve the feat of reorganising themselves into a new organisation with grassroot support and public confidence. This includes putting their obsolete old men out to pasture. I assume that you will be positioning yourself so you need to decide whether you are going to follow muzeyi down his slippery slope, daddy until they shaft him like they did Bukenya, or chose your own political destiny!  
   
The problem of the opposition is that the NRM may beat them to it if they can skip Museveni's succession plans and reorganise the NRM party while they are too busy fighting for positions. Kamya was an effective mobiliser for RA. Actually for most of the RA she was virtually the face of Reform Agenda! That she was betrayed the way she was explains her recent decisions, statements about Besigye as well as refusal to have any part in the W2W.  
   
I think the FDC shafted her but the decisions she has made since have pretty much killed her political future. She will have to do with a posting as an ambassador for Museveni. Unfortunately Museveni uses ambassadorships as political rewards, just like he uses districts and ministeries! I think she was sacrificed at the alter of FDC's 'regional balancing' politics which is much the same as that of the NRM that has sacrificed merit at the alter of short term gains and a disguised life presidency plan. n some ways one wonders just how the opposition differs from the NRM!  
   
She does not have a political platform she made sense to people but people want to know that their vote is going to contribute to change not get wasted. Mao would have to talk to her if he wants to use her. Question is whether she will work with/under someone else. The politics of parties is that each now believes they "deserve" posts/positions because they "struggled" a very similar mentality to the NRM's twalwana a sense of entitlement.  
   
In many ways FDC is as much a personality cult as the NRM is as is UPC. As has been shown recently, if you remove Besigye, they appear to lose momentum. UPC is still very much beholden to Obote's ghost despite their attempt at murdering his ghost when they removed his widow and son from the centre of their politics. They did try to build up Otunnu into a cult figure too which is why his most important asset is his CV. Unfortunately Museveni has devalued professors and highly educated men and women and reduced them to lackeys in his government so the public is no longer in awe of paper qualifications. His assocition with both Obote as well as the Okello regime as well still does not go down well in some quarters with very long collective memories! CP is dead -may they rest in peace and all of the other parties like Bibandi's and Bwanika's only exist in the figments of their founders imaginations! Suubi is a powerful lobby group that may be an asset depending on how it is handled.  
   
People may have to look outside the parties and those politicians who see the light will join them rather than continuing to look at politicians for solutions they are incapable of doing. This means that men and women of goodwill who do not see a future in the current parties will have to decide if they wish to continue abusing their own intelligence and that of Ugandans or follow their conscience.  
   
Moi lasted as long as he did by playing the divide and rule game. A fractured and directionless political opposition contributed as much to his last ten years in power as did his police. I notice that of late, Moi has become Museveni's best friend. Could he perhaps be offering free lessons in how to hang onto power when you are finished? I would hope that he instead imparted lessons on how to retire in your own country after you have contributed to divisions and wars in your bid to stay in power for Museveni is going to need these lessons! Ugandans have long memories as Obote and UPC know very well by now!   
   
We have the same problem with our political opposition. Museveni wins because he bribes and rigs the playing field with gerrymandering, a captive electoral commission, and politics of patronage and vote buying, but also because they are greedy and fractious and cannot seem to focus on what needs to be done!  
   
I support the oppositions walk to work and hope that they continue it. But I also want to see them engage meaningfully in educating Ugandans. I am therefore waiting to see their policy documents starting with a response to Maria Kiwanuka's recent budget. How the opposition manages their differences and the ego's of their leaders will determine whether they succeed in their quest to become more relevant to Ugandans.  
   
Lastly you have always asked before what Ugandans can do to help the country progress. As you have found out, Ugandans can articulate their problems -its just that their political leadership have no ears and do not listen.  
   
Buganda had a national conference on the future of Buganda. South Africa and many democracies have think tank and national conferences inviting people from all strata of their society to comment upon and propose ways forward. I would suggest that Ugandans consider a national conference or series of national coferences with various themes. Health is one that would benefit from a national conference. This would draw people from various sectors of the society who are all shareholders not just medical and academic communities. this should not be a platform for political posturing and its resolutions have got to have commitment by the government to consider in their plans for the next decade or so. In other countries, development cycles are based on community needs and are planned upto 25 years ahead. We need to identify resource people in our community and set up think tanks whose resolutions do more than gather dust on shelves. Invlove Ugandans in their governance. Special interest groups are ahead of the government and are doing this yet the government thinks that a grade III teacher like Kakooza the junior Minister in Health can add value and people more qualified than he is should just obey him because he is a "leader".

I could mention several others of your minsters who quite frankly are not cut out for their jobs but will leave it at that.
