# Of scholarships kept under the bed and distributed on the bed!


Dear Nina,  
   
Since wading into the murky waters of the tribal debate, I have had lots of inboxes. One of them will be the subject of my letter today. Its about the issue of "personalised scholarships" that appear to favour students from one region. The most famous of these of course is the presidential scholarships that have no known public criteria and nobody appears to know where the queue is!  
   
Among my inboxes was this from a lady who is an insider and well connected to your government. You may even know her but I will withold her name given she did not allow me to use it.  
   
Essentially she said of one lady, a cabinet member that, "the scholarships to India were given to her by Indian government when she visited once. They gave her scholarships of 4 girls a year so that is her program."  This reference was to a minster receiving 4 scholarships from a foreign government and handing them out as personal property in this case to a daughter in law. The son was a beneficiary of a previous scholarship. No wonder there are so many kids from western Ugandan studying India, China and Malaysia. I always thought they were paying for themselves kumbe they are using their public offices for personal gain! as you can see the implication here is that a serving cabinet member or government official can receive scholarships from a foreign government and treat them as personal property to be dished out at his or her personal whim without conflict of interest. You know I have said in the past that this government would not recognise a conflict of interest if it fell on their heads. I always thought the Ministry for Ethics was useless but now I have got even more proof.  
   
This lady went on to inform me that "I also do scholarships but because I went out and looked for them. As a matter of fact, because of working with China a lot, they first suggested to me that they would give me a scholarship and I asked if my brother would take it, then I asked for more and they gave me 5 a year which my mum took over and totally threw me out. ......Those are individually sourced. I am talking about government sourcing scholarships on their own and putting in a pool."  
   
Now am starting to get relly worried! Seriously don't you see a conlict of interest here? That some one who like you is very well connected to one of the most powerful men in the land receives scholarships as personal gifts from a foreign government we are well aware is very interested in influencing powerful people in Africa? Does the NRM have a code of conduct for public officials? Doesnt the leadership code cover gifts to serving officials of government?I will of course relate this to the recent debate about nepotism and tribalism in Uganda. I know that debate is on fire but we shall stay away from the more controversial elements and deal with this issue.  
   
This revelation explains a lot. All those young Bahima and other kids from the west who appear to have an inexhaustible supply of scholarships that no one else has ever had of or knows where to queue for! Do we really live in the same country?  
   
Imagine one group has the opportunity to use their offices to solicit favours and benefits from foreign governments which they can then channel to their relatives as they wish! Multiply that by 25 years and you can see where the inbalances come from. Extend that to skewed and flawed recruitment practices fraught with graft and nepotism and you will understand why we now have such a big problem with all of the resentment against westerners and Bahima. Jobs that are not advertised and scholarships that are not advertised or available to all. Can you imagine some girl from Buwekula (don;t even know where that is but it sounds interesting) ever accessing such state patronage? For some of us who had to pay for our degrees both undergrad and post grad because we didnt know where the queue was, it is galling and annoying! No wonder there is so much resentment among Ugandans. And then I wonder where some of you in this government get the chutzpah to claim that some of us are not "patriotic" when it is obvious you guys are eating alone -for 25 years!  
   
Below is my detaieled response to her;  
   
Ee are going to have to discuss the issue of scholarships further. I think that its innappropriate for a foreign government to "give" scholarships to an individual. It is also innappropriate for the individual working in an official capacity representing their employer to "receive" personal gifts from a foreign government. It is a well recognised form of corruption where foreign governments and companies attempt to influence government officials. Obviously this government does not train its officials regarding corruption and how to deal with foreign governments! This is one form of corruption.  
   
An example of say a government operative who is likely to influence decisions involving a foreign government or foreign company accepting gifts from the foreign government or company of a material nature does influence their integrity. This can only happen in a third world country.  
   
I can tell you that where I work, all gifts that come to one during their employ, belong to the employer and have to be declared. So I cannot receive a gift from a client or a company particularly if it supplies goods to my employer or if I am in a position to influence the decisions of my employer in procurement. This is a blanket rule!  
   
A colleague of mine received a lottery ticket from a client. It won 3 million dollars. He could not claim it and had to turn it over to the hospital. Both the clients family and his own family were of course unhappy!  
   
Internal codes of conduct if they do exist need to be reviewed with regards to these scholarships. Cretainly the leadership code needs to be re examined if it says noting about this issue for its a matter of national security as well as important in the fight against corruption.  
   
These "gifts" are not innocious and are given out with ulterior motives to officials in a position to influence strategic and business dealings with a foreign government or company. In your case your closeness to the seat of power, your future potential makes you a target of foreign governments. I can bet that the Chinese have got a dossier on you and are actively interested in influencing you now and in the future.  
   
The correct way to do so would be to "receive" the scholarships on behalf of government and hand them over to the central scholarships committee to be advertised and distributed on merit.  
   
That law should be within the leadership code. I have never read it in full but if it was well drafted there should be some limitation or control on what kind of relationship government officials can have with foreign governments.  
   
We have a whole ministry for ethics that again should have already dealt with this as should have the government itself given that it has for 25 years claimed to have a war against corruption.  
   
While you can give the scholarships to your youth group again that is not in the spirit of equitable access. Its in part why we are having this debate about the national cake and how its distributed.  
   
If we accept the conventional wisdom that western Uganda has got the bulk of government positions and managers in key government companies and organisations, then that means that western Uganda has the largest number of people with access to these kinds of unconventional gifts.   
   
If like yourself they give them to their mothers who advertise within their clan and send all of the kids who have failed their high school, abroad on these scholarships, you can see how the rest of the country can see a pattern. Multiply that by 25 years and you will then understand why others will be fighting to dislodge you from power. Because after 25 years priviledge starts to make the government look like your family. I know what my mother would do with such a scholarship if I gave them to her. If your mother is anything like my mother who has educated tens to hundreds of her relatives with her own money, you can bet they will have all won the lottery. She looks out for her nieces and nephews as well as many in her community. I doubt that she will be inviting those in Arua unrelated to her to partake. After all she is not the government.  
   
Extend this argument further and say these governments or companies come into the country to do business which is the Chinese and Indians primary motive. They understand graft very well these chinese and Indians. They will offer you directorships, shares as well as ask you to "assist" them find suitable employees. They know you are going to bring your relatives but that is a cost they have already factored into their maths. They want you to favour them. To use your influence and connections in their favour. To get access to contracts and resources or simply leverage to be used at some future date.  
   
In 25 years, all business public and private starts to look like an extension of your clan and village!  
   
These are the things that westerners are accused of but because they all consider such "gifts" given to them as personal gifts, they shrug it off.  
   
These are not personal gifts as long as they are given to one in office or because they are close to someone in office. In many countries that take these things seriously, the employee of a lottery company or their close relatives cannot be allowed to cash in on a lottery. Everyone with any sort of potential to influence the outcome has got to distance themselves from any form of dealing that could be construed or misconstrued to heve been influenced by these gifts. And government officials cannot accept material gifts from officials of foreign governments particularly if they are in a position to influence policy and decisions!  
   
The other problem of course with these gifts is that they threaten national security. Government officials pass on official secrets and insider information when they have extensive and close potentially exploitable relationships with foreign governments or businesses.  
   
I hope that you will bring this issue to the powers who have declared that useless war against corruption. They actually need to read their laws and enforce them or close loopholes where they exist. Surely 25 years is enough to do that!  
   
P.S I too have some young relatives who would benefit from some free scholarships! Could you direct me to the queue?
