# Of paying homage to mediocrity and the lack of vision!^[https://www.facebook.com/notes/drew-ddembe/letter-to-nina-of-paying-homage-to-mediocrity-and-the-lack-of-vision/10150872788152681]

Thursday, June 21, 2012 at 12:47am ·


Dearest Nina,

Its has been a while since I last wrote to you.

I really hate it when I have to say, I told you so! All indicators suggest that i am a prophet! your party dear, is falling apart. These days mzee Kaguta is querulous and quarelling with everybody! His favourite punching bags are the men of god -those ingrates who spat on him after accepting his gifts and bribes! They remind me of a Dr Tamale once Headboy of St Mary's college Kisubi, the only school in Uganda who campaigned for power in the usual manner including handing cigarettes out and then proceeded to stamp the habit out once he got the power. Having not been in Kisubi during that election, it was one of the legends we heard about him when we joined the school!

The tragedy in Uganda is that such people who would have mad good leaders of tomorrow have been forced to vote with their feet rather than pay homage to mediocrity masquerading as vision!

Watching the NRM these days, one has a sense of panic and confusion!

As for daddy dear, I always told you that he was handed a poisoned chalice! Mbabazi was given the kiss of death by the Capo di tutti capi when he annointed him PM. This is classic "The Godfather".

Watching the NRM now gives one the impression that we are watching the last five years of KANU and Moi.

Watching the recent events in Egypt suggest the Generals need to be watched very carefully.

Surely Muhoozi was not trained and promoted on steroids just so he could sit back and watch. Thats another corner that needs to be watched.

Janet did not decide to come out of the kitchen just so that she could be sent back to the kitchen. that poll listing her as a possible presidential candidate was surely a plant! Why would anyone even be interested in asking the question! aren't there any suitably qualified Ugandans that another Museveni? whoever ever convinced herr that she wa sa politician, needs to get lined up against a wall and shot, and then his body should be caned and cremated!

And what exactly is commander Saleh upto these days? Last he appeared in public was to claim he had been deployed to mobilise youth a farmers. where is the cooperatives and youth money?

Bukenya is coming out of his depression and just flexed some muscle by hosting the Buganda caucus meeting. Its an old trick of his -pulling a hat trick out of his behind whenever the one with a vision threatens to drop him.

The GAVI trio have just had a reprieve. Given they are all CEC members not quite friendly with the PM. What exactly is cooking in the NRM? Is one looking at a showdown with AM? Wings getting clipped? And what does one make of the 45 he was awarded in the poll?

And that fiasco in Arusha? Why am I even bothering? Never correct your enemy when they are making a mistake! May the NRM show us more Arusha's. Maybe the sleepy ugandans will wake up and give them the boot!

And that new mini NRM of Sekikuubo? KANU-Orange anyone?

As for all the Somali terrorists suddenly all heading for Kampala? Methinks it was a figment of Kayihura's imagination designed to get a slice of the budget cake! the timing is just a tad too perfect!

I can say for a fact that we are heading for interesting times. Certainly the end days are nigh! i for one bought myself a popcorn machine and iced coke machine -you know being a teatotaller like mzee Kaguta and all!

As for the poor opposition, those ones are even more confused than the NRM I would think. Mao's recent misguided missiles and uncoordinated troop movements were appalling. nevertheless even in their confusion, they have managed to trounce the NRM inside court or at the polls in every contested seat and by election since the so called win by the NRM in 2011!

As usual, I will be quite happy to hide you under my bed when the chicken dung hits the fan and the paesants come for their loot! You will of course have to bring my ten percent but as you know these things, tujja kuteesa!

As usual, I write this with all my love!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/), [Uganda](http://ddembe.wordpress.com/category/uganda/) Tagged: [Letter to Nina](http://ddembe.wordpress.com/tag/letter-to-nina/)
