# Lots of things!^[https://www.facebook.com/note.php?note_id=10150095929027681]

Tuesday, February 8, 2011 at 11:49pm
 

Amos and Stephen, thanks.
 
 It is possible that Museveni did really believe what he said at the beginning. But as Binaisa said, _"Entebbe ewooma"_ or in English, power corrupts and absolute power corrupts absolutely!
 
 When he stated in 1986 that the problem of Africa was leaders who overstayed in power, it was easy to believe him. Along with other statements such as the role of politics is to provide services in reference to the poor infrastructure. He ridiculed the potholed roads and said that a woman could give birth just sitting in a car going over those potholes! His roads are no better and in many places a lot worse! Furthermore when he said that there was no need for a government to kill its people if there is a disagreement between the people and itself in reference to the 1966 Kasubi incident, it was easy to hope that at last we had a government that was going to make the bad old days history!
 
 Fast forward 24 years and we have had a second Kasubi, his soldiers repeatedly fire upon with live bullets and kill people in almost all major demonstrations since Makerere University in the days when Mao was Guild president!
 
 At the time it was hope that made people believe him. I myself had hope that our country was going to get better and you could not have convinced me then that 24 years later we would have roads and hospitals in their current state while corruption and nepotism run the country!
 
 Museveni has always played the reluctant president but anyone who has watched him the last 24 years as well as read his history prior to that back to the 60 would have no doubt that he loves being in power! Its now obvious that he has no intention of ever leaving power except to his son and this whole pretence of party nomination is a sham! When Besigye tried to stand against him in the NRM, citing individual merit and his right to stand for party bearer, you and i know what happened. He was hounded from the party, harassed with threats of court martial accused of having HIV with a sitting president going to court to be cross examined on the question of whether there is such a thing as a community diagnosis of HIV which really was an extreme thing for a president to do!
 
 He subsequently again charged Besigye with rape after keeping the main witness in state house for a year almost a decade after the purported crime was committed! one wonders whether it was for blackmail reasons! What is not obvious and should have been obvious to his strategists then is that the false charges against Besigye were more publicity than money could buy and if Besigye became a formidable opponent instead of fizzling out its because he presented him with an opportunity to be a martyr!
 
 The first admission that he never ever had an intention of leaving power was during some Jamahiriya celebrations where he stated that "if he believed that his revolution would not last 50 years, he would not have started it". Soon after that the constitution was changed.
 
 Multipartism was forced upon Museveni. In the beginning, the only contract with the people of Uganda was to 'suspend" party activities. There was never any contract to create a one party system. When the time came for them to go, he created the unnecessary subterfuge of a referendum that had the poor turnout of 51% but served to remove the multiparty ban. By that time it had been obvious for many years that the movement really did operate like a party and that there was no opportunity for individuals to progress if they nurtured their own ambitions!
 
 It is true that there were lots of fighting groups that had to be pacified with or without war. However the main one the LRA last raided a village in 2002 but the villages were not disbanded till 2006 again after pressure and having been sent a clear message in the elections when the whole northern region affected by war voted against his government. To me this was the first time that Ugandans ever voted for an issue -the north for the peace they had been denied for years even if it meant allying with a westerner, and the rest of the country to maintain the relative peace they had what is derisively referred to as 'twebaka ku tulo"! In my estimation it was an act of negligence for the camps to remain for as long as they did particularly given the well documented excess mortality associated with them!! this was clearly demonstrated in a research paper by Dr Kobusingye Dr Besigye's sister in a paper published in an epidemiology journal in Canada.
 
 It is obvious that Museveni is becoming more and more autocratic. Incidents like the war against the Kabaka, the stupid sedition law that the courts removed from our statutes, the use of the military to control the police services, the stranglehold on FM stations -the Nambooze incident, the CBS affair, the shoot to kill orders on unarmed demonstrators, the recent anti Kabaka bill etc. In this week alone in unrelated incidents, activists have been arrested and charged with stupid charges like inciting violence and attempting to incite treason because of passing around pamphlets against the 20 million paid to MP's in what was an obvious gaffe! statements such as I will only hand over to the right people suggest he does not respect elections and will only accept their results if they give him the answer he wishes to hear!
 
 The Nairobi Peace jokes were a waste of time! I have no doubt that if he had joined them in a coalition government he would have ended up dead. To me, I have no regrets at all that he refused to respect them. That particular bunch of idiots simply had to be got out of our politics!
 
 For the first ten years there was concerted efforts at improvements. We all understood we had to tighten our belts. It was no different from many peasant general revolutions. Slogans, politicisation but most of all an air and feeling of inclusion in the political process. every man and woman in every village felt that they were a part of the revolution. There was a honesty engendered in having to stand behind a man -no secret ballot. if the whole village didn't like you, everyone including you knew it. There was hope -hope for a better infrastructure, better governance and pride in our country! All of this is no more as it gets more and more clear that this is just about one man!
 
 the time for resistance councils was gone by the early 90′s. Many people by that time had lost enthusiasm for them. They had been left to unemployed people around the villages and suburbs by then. People would rather pay a fine than attend meetings. it had also become obvious by then that the cadres themselves were corrupt. Fortunes were being made by people who were goat herds just a few years before and had no businesses and manufactured nothing if they were connected to the right people or came from the right village!
 
 There comes a time when peasant generals are no longer useful as a society modernises. A point where there has got to be a shift from loyalty to expertise. Museveni still values loyalty over expertise. He keeps the same deadwood in his cabinet for decades despite years of incompetence and non performance! He only trusts that which he can control. So his wife has got to join parliament. And she has got to be a minister for Karamoja because no one else could do it. His office cannot run unless his daughter works there. And neither can the army be professional without Muhoozi his son in the army. His bodyguard can only be entrusted to his son! His extended family have so many tentacles embedded in this government its more like a family thing than a national government!
 
 Oil is going to create its own problems. Museveni already created problems with his sectarian bafuruki letter. All this of course was meant to appease the Banyoro while their oil is being stolen right under their eyes. As a matter of fact the anti Kabaka bill will probably claim as its first victims the royal family of Bunyoro for when the oil starts to flow and they realise they have been sold air, they may revolt. that's when the Ogoni solution maybe invoked covered of course by this unconstitutional bill!
 
 My sister was in the first batch of students required to report to Kyankwanzi. All students admitted to Makerere were that year required to go for 3 months. This was in the early 90′s. She asked Museveni during the pass out why his cadres were so corrupt! he glossed over the question and countered by suggesting her parents had to be _'petit bourgeois'_ and that's why she was asking such a question!! By the second batch, many students refuse to report to Kyankwanzi. I believe they substituted with a few weeks of training in Makerere. My father was in a batch of civil servants who went to Kyankwanzi for 3 months. it was a waste of time as the sloganeering by high school drop outs was amateurish! All he did manage to do was lose a few kilos!
 
 The first and second parliaments were good. Most people were there on individual merit. They had a connection to the masses. it was largely independent of the executive. when Wapa left the CA to join the NRM secretariat, I personally thought that that was a big mistake!
 
 Museveni will have to adapt to the new Uganda. Even if he wins the elections, that will be the beginning of his troubles. If he is not ready to put up with more demanding and aggressive Ugandans he should resign now. Unfortunately unlike the jungle, fighting your own unarmed people is fraught with a lot of problems. its easier when there is a frontline.
 
 Ugandans want services. And they need jobs. And they need an end to nepotism which is so obvious starting with the presidents own family who are all employed by this government. We need an end to cronyism. Everyone whether they live in Uganda or not wants the best because they have family and investments in Uganda. Plus most Ugandans in the diaspora wish to retire at home. unfortunately simple things like traffic and roads, poor quality housing and practically non existent health care services keep older people abroad!
 
 When the time comes for the Jasmine express to dock, Museveni will have to go whether he wants to or not!
