# MTN, FDC, cyber freedoms and politics in Uganda

Thursday, March 31, 2011 at 9:21pm


‎http://www.facebook.com/muhiire.nathan/posts/199665066723289  
   
Nina Mbabazi, Bainomugisha has some good arguments that cannot just be thrown out because he does not have evidentiary proof.  
   
There is such a thing as circumstantial evidence and the circumstantial evidence against MTN is fairly strong.  
   
-The FDC was raided.  
-Soon after the raid, their power went off.  
-Prior to the elections, they were harrassed and intimidated about having their own independent tallying centre which is exactly the same thing that you had and any newspaper or serious media outlet could have within their own offices.  
-While your arguments regarding contigency planning maybe valid, I doubt that the FDC could activate such plans if they had them when their centre was under occupation  
   
MTN is not a Ugandan voter. it is a welcome guest in Uganda as long as they play by the rules which includes not getting involved in local politics.  
   
If they got involved on one side beyond acquiescing to a legal order signed by a duly qualified authority quoting relevant laws (which order they should have a copy of and should be able to show the press in exoneration of themselves), then they should get what was coming to them!  
   
The politics of foreign investors believing that their financial interests overide those of millions of victims is the very same politics playing itself out in the middle east and north Africa. Its the same politics that draws out all sorts of players and their governments to try and justify bombing whole societies back to the stone age for their interests while using the trojan horses of democracy and freedom. Its the same politics that saw your father accused by an invested investor who requested his government the USA to impose sanctions and travel bans on him instead of turning over what alleged evidence of corruption and bribery they may have had to the Ugandan authorities for investigation!  
   
Your father presented and promoted and even probably drafted the bill that seeks to control certain internet and communications freedoms under which any action against FDC would have fallen. This includes phone tapping, internet eavesdropping and censorship as well as controlling providers of internet and telecommunications services. I gather that the powers were eavesdropping on Ugandans and looking for certain words!  
   
BUT MTN would be duty bound due to a duty of care to its customers to only respond to a legally valid order and they have got the lawyers to enforce that. Instead its possible they simply folded to intimidation or even colluded with an order they knew to be illegal! if they did, they crossed a line for which they should be penalised. If it can be proven that MTN cut off service to the FDC without a legally valid order, am afraid FDC has a case for punitive damages against them. Needless to say, the current on going publicity while it may not be enough to lose MTN its customers loses it a lot of credibility as it was believed that in the past they have always withstood pressure from the government to control them!  
   
The temporal relationship between a raid on the FDC centre and commandeering their IT equipment as well as the cut off of Internet and cellphone services is suspect i must admit!  
   
People like Museveni and probably most of our leaders have never lived in a democratic nation during an election. There are all sorts of independent tallying centres. While its true and i have defended this before that only a legally constituted EC has got the right to declare the winner, virtually every party as well as every media outlet has got its own independent tally.  
   
The NRM exercised this right but they interfered with the FDC's right to exercise the same right as well and I wonder why!  
   
And the MTN may have been the NRM's accomplices which opens them to civil action both in the courts as well as on the streets!  
   
Companies like MTN need to understand that if they get involved in local politics they will get burned. They dont get a vote and should stop trying to buy one!
