# Mulago and the disaster it has become^[https://ddembe.wordpress.com/2012/09/23/mulago-and-the-disaster-it-has-become/]

One can write about Mulago and the disaster it is till the cows come home.

Its just as well that doctors in general don't and either just bend down and make the most of a bad situation or walk away!

When one has been in the emergency department admitting people in acute asthmatic attacks and heart failure and giving them prescriptions to go and buy emergency medications, then one learns that the
ir role in the system is superflous for they are not really being of use to anyone least of all the patient who maybe dead before morning comes and his or her relatives summon the resources to go out and buy the medications.

When you are on duty all night after being on the ward all day and all you have is a trolley filled with mebendazole (a deworming agent) and panadol, then you start to understand why mob justice makes sense to some people.

When you have got to do a ward round on patients lying on the floor in their filth and practice blind medicine because the lab results when they come will be 24 to 72 hours behind, one becomes resourceful but also resentful!

When you do a 72 hour on call covering labour suite and gynaecological annexe and have to do a vacuum with a metal cup that has to be sterilised while you wait while sister in charge (the man with the key as per Ian Clarke's novel) locked up all of the brand new plastic cups that are meant to be more gentle on the little babs brains, then you feel like murdering someone.

When you have to use your own money to donate to the patient in the corner who has received no treatment because he and his family cannot afford a cheap antibiotic and you cannot discharge them till their better while the alternative is to watch them die, then you become cynical everytime a politician talks about services in mulago being free!

When you have to watch a colleague die from cryptococcal meningitis because she could not afford the medications nor antiretrovirals something inside dies.

When you have to watch little kids die from potentially curable cancers because their parents are poor or cannot afford to bring them back for their next chemotherapy but the social worker tells you the only funding to his department is his salary and there are no funds to help such patients with transport to and from hospital to the only cancer treatment centre in the country ...!

And when you have to substitute drugs or drop others from regimens knowing fully well that it compromises the outcomes, then walking starts to make sense.

When an allied health staff takes down blood from a patient you are transfusing because the patient did not pay him, blood you walked down to blood bank and paid for ... then a homicidal rage fills your mind!

And when some suit in calf skins arrogantly tells you you are not entitled to a living wage, while he is leeching off the best the land has to offer including your own salary that is now 8 months behind, walking away makes sense.

And when a bureaucrat tells you that you should spend years of your life volunteering in an area they clearly cannot staff adequately, what does one do?

When you watch someone practice malpractice and cause the preventable death of a precious baby ....

All of the above stories are true!

I have only respect for those who stay behind to hold the fort.

My father had to go to Mulago after his cardiologist failed to answer his phone. He was having a heart attack, and was in heart failure. On looking at his surroundings, he demanded to be taken home because in his opinion, if one is sick and taken to mulago, those surroundings alone were enough to convince one that they were in a place of death and one could not walk out of there alive. He was not strong enough to impose his will though as my brother wouldnt take him home. On my arrival a day later, as soon as i called from the airport, he discharged himself and said we would meet at home. Needless to say, a lot of important diagnoses were missed!

My own personal experience is already documented here so i will not repeat it.!

While we try to gloss over these issues because of our injured pride, people are dying everyday! this is not about how much potential ugandan doctors have and how good they can be in the right environment or even in the wrong one -ie a poorly resourced environment. of course they can be good -Makerere has got a pedigree and selects a hundred of the best students in the country. they will thrive in whatever environment you put them in. but they can also flounder in the wrong system!

Their brilliance and personal motivation simply cannot make up for the political deficits and lack of will to improve health conditions in the country! And thats why many walk away, from the depressing clinical setting to other fields including non medical fields or even from the country!

Of course it has got to be clear where to place the blame. The NRM has been a disaster for medical services and does not have any clue at all how to deliver health to the people. Neither are they trying. they just continue to posture and trot out false figures!

If Ugandan doctors were to really tell their stories of working in Ugandan hospitals, this governments claims about its record on health would be exposed for the lies they are!

But how does one deal with a government that is not accountable for its actions?

One that instead of making sure there is affordable helthcare for all prefers to squander hundreds of millions of dollars every year on the care of a few hundreds of politicians and their families while the rest of the countries 34 million people die early from preventable illnesses!
