# Museveni has never had a vision for the provision of adequate healthcare services to ugandans!^[https://www.facebook.com/notes/drew-ddembe/museveni-has-never-had-a-vision-for-the-provision-of-adequate-healthcare-service/10151017055372681]

Sunday, September 2, 2012 at 7:40pm

Nina says,

> [_"Dear Drew - Transforming agriculture into a cash economy. Universal taxation policies to improve healthcare services"_](https://www.facebook.com/notes/nina-mbabazi/dear-drew-transforming-agriculture-into-a-cash-economy-universal-taxation-polici/10151141393464449)


We have got to begin by understanding the structure of our population. 

Ugandans are essentially land rich, asset and cash poor agro based and largely formally unemployed illiterate and semi -literate and superstitious people whose main economic activities are subsistent and are largely carried out outside the formal economy whose policy and planning is carried out by a largely corrupt and incompetent government!.

Health services are retarded and have large gaps in healthcare service delivery including primary care, public health, emergency services, and specialised and subspecialty care. 

Without formal employment, many people would have trouble affording managed care. While we always talk about health insurance, this is virtually impossible to manage on a large scale in a population such as Uganda's! Managed healthcare on the other hand particularly in primary healthcare maybe feasible while formal health insurance maybe reserved for the high end. 

There are institutions in Uganda that already have the infrastructure in place for managed healthcare services. These are missionary hospitals particularly Roman Catholic and Anglican church missionary hospitals. Many of these have experience in providing healthcare services in resource poor environments going back almost 100 years and are motivated by more than making a profit.If you are going to sign PPP's to provide healthcare services to ugandans, you would have to start with the institutions that have got a track record and experience.I can however bet that if the NRM were to sign PPP's to provide healthcare services, goatherds will be running and owning hospitals!  

A medicare style system where rebates are paid per capita to these healthcare providers for services rendered with or without a gap can be implemented. right now the government just gives a lumpsum that is inadequate and not tied to performance or number of patients seen or services provided. 

Managed Healthcare service Organisations are largely driven by profit. Doctors working for them are incentivised to minimise expenses and their bonuses and income maybe tied to them "saving money" which usually means witholding investigations or minimising and rationing healthcare. 

Because these managed healthcare services depend on regular payments by the users, those without formal employment fall under the safety net and are left without cover in a country where the government is allowed to get away with shirking its responsibilities. 

The main incentive for the construction of heath centres was the money made from awarding construction contracts. There was no plan for staffing and no funding either. Even those hospitals that are staffed are dependent on a demoralised and underpaid healthcare staff who are not even afforded the basic minimum in protective gear! A hospital is not a building even when it has state of the art technology. it has got to be staffed by adequate, well trained, motivated and incentivised medical and nursing staff as well as allied healthcare workers who are well resourced.

 

PPP's require supervision because of the competing interests involved. The manager of the contract is there to make a profit. The patient or client wants the best helthcare that is available ie money is not an issue as long as they are not paying anymore than their standard premium or taxes. The government is both a client and a supervisor.

 

In Uganda we all know we have major governance issues including corruption, unethical conduct and incompetence. Awarding and supervising a PPP is well beyond the capacity of the current NRM government. 26 years of history with the NRM in power is more than enough evidence that given the powers to award contracts for PPP's will mean that in another ten years even the current existing government hospitals and the land they sit on will have been sold to well connected insiders and corporate raiders and the consumer will continue to be raped in broad daylight!

 

We have a political elite who see themselves as not subject to the same rules as everyone else. They therefore have no problem with spendin enough money to build and run several hospitals every year on a few hundred elite while the rest of the country rely on herbs and coffin makers!

 

There is an emphaiss on fundraising for individual patients that has been promoted by the New Vision in particular and followed by other media organisations which I think is flawed. I have no problem with those who can afford it getting healthcare for themselves and their loved ones overseas -I have done it myself! 

 

But fundraising for every sad case that comes along results in the haemorrhaging of large amounts of cash while not adding to the local expertise and ability to manage other cases that come along.

 

It is said that one who teaches you how to fish does you a much better service thatn one who gives you a fish.

 

For many years, it was said that the Heart institute could not perform cardiac surgery. In came a doo gooder outfit for 2 weeks and open heart surgery was done in mulago without new infrastructure. The same feat was repeated by IHK which while being OK is not a world standard high tech facility! The real trick is how to transfer this knowledge and technology instead of just clapping and saying wow everytime a blond crew jets in for 2 weeks and a lifetime achievement award for having braved Kampala for a few days and saved a handful of lives.

 

Uganda Cancer Institute has been opearting since 1968 and despite understaffing and multiple deficits in skills and resources has always provided a service to cancer patients. it has never once closed its doors in those over 40 years.

 

But these institutions are shunned by the same elite that should be ensuring that they are world class facilities they can trust with their lives and that of their children as well as other Ugandans.

 

Every once in a while a well connected politician dies from one of these nasty diseases and they then for a minute or two cry crocodile tears ...but follow on by ensuring that their own pay and access to overseas healthcare is guaranteed!

 

We need a committed government, one that is committed to ensuring that no child is left behind. We are leaving too many children behind, too many of our citizens!

 

Uganda was once the pearl and a pioneer in providing good healthcare services with a strong primary healthcare, public health, academic and training infrastructure that led the region. Students and researchers came from all over the world to study and work at Mulago. 

 

Now its reduced to a health centre where everyone can walk in from off the street as the last resort from the dearth of healthcare services in the rest of the country!

 

But then what does one expect when Uganda is a country whose president thought it reasonable that he fly his daughter to Germany for a normal delivery at a cost of 90,000 USd for fuel alone!

 

And yet there are those who would dance and sing for him and claim he has a vision! What is in no doubt is that he has a vision for himself, his family (see where his brothers, wife, sisters, daughters and their husbands and son have come under his vision)  but anyone who has had a close and personal experience with the absence of services in uganda knows that that mans vision does not include providing healthcare services to Ugandans!

 

If Ugandans really voted on issues, and healthcare were turned into a voting issue, this government wouldnt last a day!

 

Ugandans need to turn healthcare services into a voting issue and the government should not be given a free get out of jail card by pawning off providing adequate healthcare to NGO's the community and the churches! 

 

And they should start by withdrawing the priviledges of their ruling political elite including overseas healthcare!

 

 

******* 

 

https://www.facebook.com/drew.ddembe/posts/375138775887850?notif_t=share_comment

  
Filed under: [Health](http://ddembe.wordpress.com/category/health/)
