# Museveni's children -taking our country back!^[https://www.facebook.com/profile.php?id=620617398]


Monday, March 7, 2011 at 1:24pm


http://www.facebook.com/note.php?note_id=196331557052152

And I hate to admit that you were right!

My mother admitted when I finally asked that "We voted him. Ate what could we do!" But she was at the same time fearful of what the future held under Museveni! my brother -he will never vote again for as long as there is a Museveni on the ballot ticket!

You see we are a very apolitical family and never even discussed our political opinions and voting plans before the election.

My parents know nothing about my activities on Facebook! If they did, am sure they would be horrified and dissuade me from expressing myself!

You see they became adults in the 60′s and lived under Idi Amin and Obote II! To them this is as good as it gets! They have lived under repression for so long that a gilded cage represents home and freedom is scary! They are not the only ones going by the recent elections!

The uninspiring opposition does not help much either! And neither does the aggressive rhetoric for it reminds this generation of war!! Unfortunately the impression and opinion that the guys in opposition are just another bunch of politicians who are making noise just so that they may get closer to the national cake and divvy it up among their kith and kin, just does not give them an appetite for change.

My parents need to see change they can believe in! they need an Obama. Someone who comes along and somehow makes people believe that there is a good reason to change! you see having watched mad monkeys tear the country apart, they are afraid of letting monkeys mess them up again just for the sake of change. But they are old, and one can forgive them. Unfortunately there is no amount of stalling that's going to allow us to get past the fact that Museveni is now the single largest roadblock to democracy as well as stability in Uganda! for the longer he stays in power, the more likely it is that we shall have to fight a war to dislodge him or his son from our politics!

Today I read a story by Nina Mbabazi of her family's experiences in Obote II. http://www.facebook.com/notes/nina-mbabazi/my-experience-of-house-arrest-under-president-obote/10150124597924449. I am not her Facebook friend and am sure not her offline friend either given I recently aimed a few choice barbs written a long time ago in the direction of a dearly beloved one in her family! But that does not matter! Point is I couldn't leave my opinion behind! Her family left Uganda in the early 80′s and she describes life in exile in Kenya and Sweden. Quite frankly hers is quite tame in comparison to those of us whose parents stayed behind!

I think more people need to write these stories including those within the NRM! I say this even though i believe that Nina's story is tame in comparison to those of us whose parents stayed behind! But I will not detract from her story because it is an important part of the narrative of our chequered history of conflict! Nina was born in the 70′s just like all of us other "children of Museveni born in the 70′s 80′s, 90′s as well as this millennium! She has for so long been an insider that her view of the narrative has become warped! But now like all of us having tired of parties she is starting to open her eyes and starting to see and hopefully question the veracity of the narrative in which she has been brought up! But Nina's story is useful in demonstrating that even within the NRM there is more than one story -that of one man!

You see like the proverbial blind men, we Ugandans all have our own idea of what Uganda is and what it means to be a Ugandan! So those who touch the trunk describe it as thick and long, while those who touch the ears describe it as flat and wide -like a leaf! those who grab the tail have their own version-thin and long, while those who grab a leg think its like a tree trunk! While we did not have to fight for our independence, we have spent the last 50 years fighting each other! Its the only thing that remains constant! Conflict and pain rotates from one region to another -as does the cake. the ideas of who the oppressors are also change!

But I digress. I was talking about Nina and her new found awakening. Her most recent postings remind me of another NRM chick before she took the big jump. You see, Nina and her friends have for so long been buried in the NRM narrative that they ignore the most obvious truth. That we have all, Museveni's children excepting those in the IDP camps and those in Sweden, been NRM children passively or actively! Even when we had zero interest in politics and getting laid or going to a club was the foremost thing on our minds, we in some way contributed to the NRM narrative through our apathy! 

We did not vote, we did not make any political statements but just let the grown ups to do all of the talking and play big peoples politics -abusing one another and framing each other for rape! We didn't care as long as no one was shooting at us! That other NRM chick who for a while confused everyone with the question of whether she was coming or going was the very brainy and beautiful Byanyima now wife to Besigye the leader of the opposition! Interestingly while she was an active and vocal opposer from within, she strangely went silent once she was on the outside and allowed her hubby to hog the limelight!

There is such a thing as the enemy within. What Frantz Fanon called the "comprador Bourgeoisie"! The well educated, middle classes that in one way or other are confortable with the status quo. They are politically inactive even when they see things happen to others. They see the poverty. They see the corruption. They see the miscarriages of justice! But they do nothing. they even buy into the narrative of the dominant powers -that anyone who opposes them or their stranglehold on power is a dissident, an enemy to be crushed, an anarchist, a 'kipinga' just like those idiots in the LRA and more recently a terrorist -just like those idiots in Al Shabaab! Being in the opposition becomes a dirty word -synonymous with all of the above! the idea that a government needs an opposition as a check and balance to keep them honest just does not have any traction with them! So anyone who fails to toe the line is an enemy! Nina is about to find out that she is an enemy unless she runs back to daddy and uncle Kaguta! That the nice uncles and granddads can turn nasty and vicious!

You see our country has become hijacked by one man and his family. All of those in the NRM are working for him, or pawns in his personal narrative. In his version of events, everyone else was just a support person! That real people died and suffered for his dream is immaterial -he actually forgot those people! That many of those people who died for him to win his war would not approve of the way things have turned out, again eludes him! Like many people who are placed on a pedestal, megalomaniacs start to believe in themselves to the point of delusion! You can see this in Libya where Col. Gadhafi seems to believe that when he says he has no title we should all believe him! 

The extreme narcissism that makes one man declare himself to be the one and only man with a vision in a country with 33 million people is mind boggling! That one man could be so arrogant is amazing! That other intelligent people could let him get away with it is even more amazing! But to a narcissist its only natural that he be the only one with a vision. That everyone else is there only and only for their own self gratification! There is no doubt that narcissists can be very driven and become very successful people but they are also shallow and vain as well as potentially very nasty if other people do not recognise their prowess and success! Museveni is a narcissist! And all of his men are patsies there only for his own glorification!

It is time that Ugandans decided if they can afford Museveni any longer. It is time that all intelligent men and women evaluated whether he adds value to the future of the NRM and the country or whether its time to put him out to pasture. Its obvious that the opposition is not upto the job yet. For as Museveni has pointed out, they are incompetent by virtue of the fact that they do not have access to the national coffers to bribe the voters and legislators, but they also do not have willing patsies in the army willing to kill to keep one man in power! for unlike those professional Generals in Egypt who refused to go out and shoot their own people, our own personal army still has the mark of Museveni and is yet to become a national army. Certainly one cannot trust our Generals to stand down when ordered to shoot upon Ugandans! for again theirs is the narrative that anyone who opposes Museveni is an enemy of the state -to be killed if necessary and their body labelled as terrorists in retrospect as were those of civilians shot and killed in the so called Buganda riots of Sept 2009!

Museveni and Gadhafi have for so long been the only men with a vision that (everyone else in their governments is dumb) they believe that everybody else owe them. Their children and the children of those in the 'kintu" have for so long lived in the official narrative that they believe that a government was taken over after five years of fighting by one man and 27 accomplices!

Buddha did not become great until he left the palace gardens and walked among the people on the street! The children of those in the 'kintu' will have to come out and join their hands with real people if they wish to have any relevance in the future of Uganda! the idea that like Gadhafi's sons they are entitled to a good life because their fathers fought is one they need to disabuse themselves of!

We all fought for and paid for their victory and have all worked hard for the last 25 years to achieve whatever victories they may claim for themselves!

Even when as children we cowered under the bed with bullets raining on the roof everyday, or while soldiers ransacked our homes looking for our fathers, we were making our contribution -in childhoods lost! When we jumped over dead bodies as children ,we lost our innocence!

The NRM like Uganda is ours, whether we are card carrying members or not, for we paid the price for it! It does not belong to one man and neither does it belong to his family! He is not a king and therefore should not be allowed to rule forever! And neither should his son who was safe in Sweden when we were being terrorised be succeeding him!

Every right thinking member of Uganda whether pro NRM or anti NRM has got to be thinking -no resetting the clock, no further extensions, and no succession! And having now learnt the lesson that one man can never be trusted to decide for how long he is allowed to dominate our politics, let term limits be written back into the constitution!

This work is licensed under a [Creative Commons Attribution Non-commercial license.](http://creativecommons.org/licenses/by-nc/3.0/)
