# What does it profit a man, to gain the world, and lose his soul?^[https://www.facebook.com/notes/drew-ddembe/what-does-it-profit-a-man-to-gain-the-world-and-lose-his-soul/10150130091282681]

Tuesday, March 29, 2011 at 6:36pm ·

Nina Mbabazi -What does it profit a man, to gain the world, and lose his soul?

It profits a man very little to gain the world but lose his soul.


  * It profits Museveni very little to rule forever but lose his credibility
  * It profits the NRM very little to lead a revolution and be buried in the narrative of one man
  * A man is only as good as his word, without which he is doomed
  * A politician whose word is meaningless can never claim to be a statesman
  * For each time that Museveni goes back on his word, and moves the goal posts yet again ahead, he will forever be stuck in the soulless limbo of political purgatory
  * Of what benefit is it to build a country and watch it destroyed before your eyes -like Ghadaffi
  * Of what benefit is it to raise your sons to follow in your steps and have them be killed before your eyes -like Saddam
  * Of what benefit is it to be declared a hero yet become a villain in your lifetime -like Mugabe
  * Of what use is it to attain the lofty limits of wealth and power, yet have it all come crashing down -like Mobutu, Obote, Amin
  * Why is it so hard for a man to retire and hand over intact to future generations his lifes work and bask in the glory of being a statesman -like Mandela


<http://www.facebook.com/permalink.php?story_fbid=10150174637456259&id=712431258¬if_t=like>

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Letter to Nina](http://ddembe.wordpress.com/tag/letter-to-nina/)
