# Of illusions -post 2011 election^[https://www.facebook.com/note.php?note_id=10150102793922681]


Monday, February 21, 2011 at 10:39am


I had no illusions at all that Museveni was going to 'win' this election. I agree with the commonwealth report and have already pointed out the same points in [my own note yesterday](https://www.facebook.com/note.php?note_id=10150101608607681&id=620617398).

In my post yesterday, I pointed out the heavy use of incumbence, state patronage and state resources and that this will need to be examined further if necessary in the constitutional court. The laws regarding party funding will need to be examined as this is a loophole Museveni has used. The use of money in this election will need serious debate.

Again in my post election post I mentioned the payment of LC's as a major factor in this election. I posted a note I wrote in 2004 regarding [Museveni's grassroot campaign machine](https://www.facebook.com/note.php?note_id=499939492680&id=620617398) (LC's). No other party can duplicate this structure. I personally think that the opposition should have pushed for he dissolution of LC's an NRM party structure, when the NRM one party government ended and multiparty politics started in 2006, but Museveni is quite good at diverting them for months on useless debates like the anti homosexuality bill that am sure he never intended to pass in the first place but kept parliament from debating issues that affect Ugandans!

Unequal access to the media -I believe something like 9 FM stations in the north denied access to opposition politicians. This should be illegal and needs to be addressed! there should be laws guaranteeing access to all political parties during campaigns.

The use of technology. While FB has emerged as a factor that has put the NRM on their toes and the effects of this forum on this election and future debate and elections will need to be analysed for sometime, the opposition failed to use it for leverage. In this respect, Museveni was ahead of them. As you can see they at least sent their agents provocateurs like Nina, Ochola, Okello, Maria, Jimmex and Mugerwa to monitor and at times attempt to disrupt and derail debate in these forums! The opposition spokesmen failed to engage in these debates or use technology as leverage.

The opposition still remains weak and immature, even though it has made great strides since 2006. Their main campaign strategy is still based around antipathy to Museveni the man but [many fail to articulate a clear position](https://www.facebook.com/note.php?note_id=293997787680) on what they have to offer Ugandans that is different to what the NRM and Museveni have to offer! The presence of old guards who themselves are tainted either by association with previous governments or by association with the NRM does not help either! FDC has taken on more of the character of a political party rather than a coalition of desperados with personal grudges against the incubent. Thay also managed to field more candidates this time in most constituents. DP has thrown off the old guard while UPC has thrown off the Obote family that controlled and virtually owned the party for 49 years but is still controlled by old reflexes! The beginnings of single issue lobby groups and parties campaigning on a single issue such as Kamya and Ssuubi have emerged.

KB is going to have to move aside for either Muntu or his wife or whoever else his party choses to elect as their leader. Mao is still immature and it is not clear whether he will be able to build DP back into a strong party with a young base and a national representation or whether he will go for short term gains and jump ship. One hopes that he will be ready for 2016. Otunnu was still born and his petulance and childishness in this election has exposed him as just another egoistic politician seeking power for himself. He hoped that ugandans would view him as a saviour and that their hate of Museveni would act in his favour. Unfortunately like many politicians from previous governments who have lived outside the country for a long time he continues in the delusion that Ugandans hate Museveni. Its true some do but many don't. To many he was a necessary evil -against people like Otunnu and his previous friends many of whom remain his current friends. While many are tired of Museveni and would like to see him go, in a direct contest between otunnu and Museveni, Otunnu Museveni would win hands down! the only way that Otunnu will be able to change that is actually getting down on the ground and doing 'kakuyege' -do the hearts and minds thing and not the 'shock and awe' thing which obviously does not seem to have traction with the masses! He needs to actually build a base if he wishes to have a future as a Ugandan politician else he should just return to New York and look for a job! Intellectuals maybe impressed by his resume but paesants don't care -and paesants have the power here! Paesants are more interested in "twebaka ku tulo" and their next meal and he needs to articulate how he is going to guarantee that!

The NRM was more mature in not giving him free publicity by making him a martyr which is what he wanted. Am sure he was itching to be arrested! Like Awori, such people fade away when ignored but like Besigye gain traction when persecuted.

The heavy deployment of the army in this election needs to be discussed. Policing is the job of the police and not the army. During an election, emphasis should be on the use of police which should be resourced and trained to maintain the peace. Instead resources were diverted to the army! I just received a message from my mother while writing this. I will quote her sms verbatim; "Museveni again! We pray that there will be peace. We are OK, but still in houses! Greetings and God bless.

My parents are not aware of my writings or activities on this forum as I do not discuss them with them. For years they supported and in some way helped maintain the NRM in the early days. They were very active in civil education campaigns of the CA and early LC's but lost interest when it became clear Museveni had no intention of stepping down and corruption was not going anywhere. I am very sure that they do not feel the same way about Museveni since about 1999-2006 and am sure they are not the only ones. If they voted any other party, it would be a protest vote. Again I have never asked them who they voted but I wouldnt be surprised if they voted against Museveni. Traditionally they were DP, by I would be surprised if they voted DP either. I suspect that their vote would go to one of the smaller new candidates like Kamya even though they would be well aware she had no chance. On the other hand I would not be surprised if they chose to vote for "stability" and voted for Museveni!

It is interesting that in many places, people decided to vote out Museveni's minsters but voted to keep him! This probably boils down to 'stability' and twebaka ku tulo' as Museveni and his Generals have made it very clear that they will shoot anyone who threatens their hold on power and they are not about to salute anyone else! Surely it is not because they think that they are doing a wonderful job otherwise why sack a performing team? And we know that on corruption, on poverty, on infrastructure etc, the NRM and Museveni score a big zero!

The fact that 3 days after the election, they still haven't ventured outside their homes is telling and explains why there really hasn't been much celebration even if the NRM should be celebrating! The intimidating presence of the army given the circumstances and our history may therefore have played a role in peoples choices. It is the same ridiculous choice that Egyptians had to make in entrusting the stability and security of their country to the frailty of an 80-something year old man until they got the courage to overcome their fear!! All this military presence is designed to heighten anxiety and stampede people into voting for stability just like Tony Blair stampeded his parliament into rubber stamping his war in Iraq by stationing tanks at Heathrow even though there is no conceivable role for tanks in a fight against a suicide bomber with a backpack or even stolen plane! This is psychological manipulation of the population as is all the talk of terrorism and intimidation of anyone who talks about demonstrating against the NRM by labelling them a war monger or terrorist!

The opposition is going to have to become more sophisticated. The funding of the NRM in this campaign has got to be questioned including in courts. If there are laws that require parties to declare their funding, they should be used to force the NRM to declare their funding sources. If they used state resources as we all know they did, then that should become subject to legal and constitutional interpretation. The use of state funds will need to be explored and queried including the supplementary budgets passed during campaigns and the funds given to the presidency as well as MP's. The passing of the unconstitutional "Traditional Leaders Bill" should be reversed and discussed and redrafted properly if it is really deemed to be necessary! One hopes that the new strength of opposition politicians in parliament will be used to force debate on all of these issues including cutting the powers of the presidency as well as bringing back term limits!

If there has been oil company money in this election, this needs to be declared. The WikiLeaks documents clearly demonstrate that Tullow oil sought to exert influence through possibly blackmail on our politicians. If they have made any major payments to the NRM or any other party, this should be explored including using the US governments laws on private companies payments to and links to foreign governments!

Lastly one has got to mention the obvious incompetence of the electoral commission under Kiggundu. The credibility of the EC really needs to be improved. Certainly Kiggundu needs to take one for the team and go back to whatever it is he used to do before! https://www.facebook.com/note.php?note_id=10150095148497681

I pointed out to Nina in this forum before that there is such a thing as a pyrrhic victory. Like for Ben Ali and Mubarak, this may turn out to be one.

The Jasmine train is not yet derailed. This debate must continue!
