# Of ticks and fatted bulls!^[https://www.facebook.com/note.php?note_id=10150107437652681] 

Monday, February 28, 2011 at 8:01am


Mbabazi,

Nice try (Mbabazi thinks I should join the NRM and change from within). I promised myself many years ago never to work in an organisation where I became a part of the problem -if I cannot hire and fire, count me out! Everyone who joins the NRM becomes poisoned! in so much as you all continue to allow Museveni to continue to live his dreams at the expense of the country, you are all now a part of the dream!

You know that am not coming over. Your chalice is poisoned! Everyone in your yellow bus is a pawn! Its a wonder you don't feel soiled!

It is obvious to everyone by now that Museveni's wish to stay in power has got nothing to do with this country! Its got a lot more to do with his ego, and his fear of becoming irrelevant!

And having fattened on the best that our country has got to offer for 25 years, the fatted cow has attracted a lot of ticks! And those ticks have vested interests in keeping the cow around!

But what those ticks do not know is that they are all dispensable and disposable! if one of those ticks so much as becomes annoying, they will be swatted away like the nuisance they are! We all know these ticks -Mbabazi, Nsibambi, bukenya, the tinyefunza's, Muhwezi, Mukula etc! Like Ben Ali and mubarak sacrificed their cabinets before them, they will be the first ones to be thrown in front of the mob when it comes for retribution! As you can see he has already been sending around a whispering campaign -he is clean -blame the ticks around him!

That the tick imagines that they for one instance have some sort of influence on the bull on which they feed is laughable! The bull laughs at them! The indulges and tolerates them! You see with Uganda at his mercy, he has a lot of blood at his disposal -more than the ticks can drain! His immune system is adapted to their presence. They cannot kill him but he can kill them or just swat them off to starve -like he did Kategaya!

There was however one tick, Besigye that became really annoying and got swatted off. He continues to survive even when separated from the host. But thats only because there was some anaemic and thin cow called opposition onto which he managed to cling and continues to hold onto literally by his teeth! A couple of weeks ago, opposition lost a few more liters of blood to big fat bull!

What Mr Big Fat Bull does not reckon on is the resilience of the downtrodden Uganda on which he has fed for all of these years. You see, Uganda has seen other Greedy Fat Bulls before. They all thought they would be around forever -Amin, Obote etc!At the end Uganda had the last laugh! The more of Uganda's blood they drain the more erratic and mad they get! you see thats one property of Uganda's blood they did not know -it has the power to make them run mad and destroy themselves!

In one swoop, Uganda will rise and Mr Big Fat Bull and all of his ticks will be gone!
