# Poking a beehive -to see what comes out!

Saturday, March 12, 2011 at 7:46pm


http://www.facebook.com/muhiire.nathan/posts/10150159027961259?ref=notif¬if_t=like  
   
He he.  
   
Nathan, you want something from Nina? This looks like poking a stick down a hole in an ant hill to see what comes out! In politics, no comment maybe your answer. I notice that Nina very quickly withdrew herself from making comment! I personally would be interested in Nina's comments, so I am going to be provocative.  
   
There is no doubt that Nina has put herself out there. She reminds me of a few other women on Uganda's political scene -Byanyima, Anne Mugisha. Both of them incidentally jumped out of the NRM.  
   
Winnie Byanyima went quiet probably because as a UN employee, she is constrained in her ability to make political statements on domestic politics. Anne Mugisha soon found out that politics is very much still a mans world and the boys don't take too kindly to girls who are too ambitious!  
   
Before Byanyima jumped from the NRM, she went through a period where it was difficult to know whether she was coming or going! She did however contribute to some of the most exciting days in parliament! Things are more staid and boring theses days with no ministers being censored since she left!!! Between her and Basoga Nsadhu -before he was emasculated with an eating position in cabinet, corruption seemed to be on the agenda in parliament. These days the honourables just ask the party SG which way to vote, sleep through the debates and wake up to vote and collect their allowances and bribes!  
 

Sleepy MP's  
   
Byanyima went through a similar thing to what Nina appears to be going through right now -breaking ranks and sharing bread with other people across the divide when they say the emperor has no cloths and his buttocks are peeping! But being conflicted, she also takes the time to assert that she is NRM, through and through!  
   
Anne Mugisha landed in Kampala 5 months before the elections. Prior to landing, she sung the official FDC anthem and disagreed vehemently with any comments that appeared to suggest that FDC had internal problems and was as yet not quite ready for prime time! Since landing and being faced with internal intrigue, am sure she now understands the realities of being on the ground better. I disagreed with her on a few things which she must have interpreted as me attacking the FDC, but she was gracious enough to inbox me and say she liked what I was saying and hoped I would continue writing! Am sure she agrees more with my comments now that she has spent some time on the ground.  
   
There is no doubt that Nina is building her own constituency, "consulting" "branding" herself and projecting her persona. The question remains to be answered -is she her own woman? Or is she daddy's girl? Or is she Museveni's girl? Only Nina will be able to answer this question!  
   
Buddha only became his own person (and a saint) when he stepped out of his confort zone in the palace gardens and walked with real people. Jesus had to come all the way down to earth from heaven -to connect with real people! Moses had to mix with slaves and commit a crime, before he could become one of the Jews -and their leader.  
   
Is this thing that Nina is doing about Nina, about daddy, or about party and president? Nina is going to have to be clear on where she stands before she can be trusted. She will need to decide whether she wants to stand with the people of Uganda or whether she wishes to stand for the vested interests of individuals in the ruling party including her own father as well as Museveni and his family.  
   
Is Nina satisfied with being a priviledged girl brought up in the movement addressing all of the most powerful party figures as aunty and uncle, using the influence of daddy to launch her own career, or will she step outside the rarefied atmosphere of being an NRM young Turk brought up in the party and headed for big things i.e take some risks?  
   
Will she be able to resist and head off other powerful interests within the party that are hell bent on leading us to self destruction -including dynastic rule? Or will she like Otunnu end up dissappointing the followers who will have put all of their faith in her?  
   
The NRM is headed for deep waters. Only those who love the party and are strong enough to do the needful will be able to save it. This includes standing up to president Museveni and telling him where to get off -Kisozi or Rwakitura (Kigali, Jo'burg or Jeddah are other options if he is uncooperative but why should it come to that)?  
   
Me I have added her to my list of people to watch -as they soar or crash!
