---
output:
  pdf_document: default
  html_document: default
---
# Sexually transmitted leadership!

12 July 2011

Stephen Twinoburyo, LOL!

Arrogant ignorance and blissful ignorance are the terms that describe sweetheart Nina Mbabazi who like many in the NRM mix up priviledge with acumen and ability!

The NRM having been in power for 26 years after five years of a destructive war that saw many people killed directly or as an indirect result of their greed for power let loose the animal called corruption on Ugandans!

Now in a display of dishonesty, she wishes to give the impression that having "learnt" from their trial and error and mistakes which we all know were really just willful ignorance and corruption, they are now qualified to lecture us on the solutions if only everybody else takes a back seat, does not criticise them and allows them to continue bumbling along till they find the solution!

In this willful ignorance and arrogance, she lso assumes that we are supposed to sit still like idiots waiting for them in this case the children of the "twarwaana" group to tell us the solutions!

Of course she ignores the fact that these children including herself have no special skills nor acumen to see things any better than the rest of us who have watched them and their daddies bungle and murk along at our expense for so long!

Having been brought up in tax payer funded luxury and tax payer funded education, they now believe themselves to be more qualified than everybody else!

Unfortunately the vast majority of them have no more qualifications to leadership nor to proffer any solutions or opinions than their relationship to the NRM bigwigs who have taken this country to hell in a basket a fact of which they continue to express willful ignorance!

Apart from sharing a name with the dad and feeding off the carcass of the animal called Uganda speared by their dads and held in eternal captivity like personal property, I see no reason to take her opinion over anyone else's. Certainly having found many of her opinions wanting including the one above, I am not about to applaud!

But of course there are and will always be sycophants willing to tell the emperor their are wearing the finest of silk when their buttocks are waving in the wind!