# Someone is reshuffling the succession queue!^[https://www.facebook.com/notes/drew-ddembe/someone-is-reshuffling-the-succession-queue/10150324205912681]

Friday, October 7, 2011 at 9:27am ·


Someone is reshuffling the queue!

Muhoozi takes a sudden interest in soccer. He donates 5000 USD to the Cranes.

Mbabazi also takes a sudden interest in soccer. He too donates to the Cranes -10,000 USD!

Neither man is known for their interest in soccer!

Bukenya is removed from the succession queue -in a rather abrupt and nasty manner. He is dragged off in chains to luzira!

The power centres around the succession queue are the Museveni's (Janet Kataaha Museveni, Ainerugaba Muhoozi Museveni, and Akandanwaho Salim Saleh), Sam Kutesa an inlaw to the Museveni's, and Amama Mbabazi who first declared the existence of a queue many years ago when Besigye tried to jump it!

The Museveni's are at the head of the Bahororo brigade, Kutesa at the head of the Bahima/Banyarwanda brigade and Mbabazi heads the Bakiga brigade! Bukenya previously headed the progressive brigade as well as the catholic and Buganda brigades but he squandered all of his capital and remained with the Wakiso paesant brigade! It is questionable just how much more command he retains there!

Bukenya is sacked and in jail. Kutesa with Nasasira and Rukutana are also threatened with jail. Museveni is sending mixed messages feebly saying Bukenya is innocent!

But one man seemingly remains outside all of this despite he too having been mentioned in CHOGM as well as Temangalo. Recently there have been several rulings both political and legal declaring Mr "clean" Amama Mbabazi to be clean of both CHOGM and Temangalo!

Why all of a sudden this whitewshing exercise and why is the queue getting shorter? Why is there remaining only one candidate? Could it be perchance that that candidate or his boss are pulling the ropes and pruning the succession queue?

And then one looks at the instrument -IGG Baku. And one asks to who does the instrument of execution belong?

Does the fact that the instrument of execution belong to Mr "Clean" Amama Mbabazi now become relevant?

Is there a palace coup going on or is Museveni pruning his succession queue! Does any of this really have anything to do with corruption or is it plain old power politics? And which way will the Bahima Generals jump or the newly minted ethnically unbalanced Muhoozi compatriots given new ranks of najor, Colonel and Brigadier?

If I were any of the above men, I would grow eyes in the back of my head!!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Mbabazi](http://ddembe.wordpress.com/tag/mbabazi/), [Succession](http://ddembe.wordpress.com/tag/succession/)
