# Stories of war^[https://www.facebook.com/notes/drew-ddembe/stories-of-war/10150113338617681]

Tuesday, March 8, 2011 at 9:10pm ·


http://www.facebook.com/note.php?note_id=10150124597924449&comments

I like the fact that people are writing about their personal experiences. So I have to thank Nina for her story.

Like Philip, my personal experiences of Obote II justify even in retrospect any war to oust him! Nothing that happened after will make me change that opinion! The Obote II government was a bad government full stop!

As to whether or not Nina's dad and others were justified in going to war, the jury is still out. But the response of the Obote government and army turned what may have initially been an illegitimate war into a legitimate war! unfortunately the NRM does not seem to have internalised the lessons of that war -for every man, woman, or child killed, tortured, maimed or raped by Obote's goons, more recruits fixed in their resolve to see it end volunteered!

it is important to recognise that nina's is only one perspective -and story. Everyone else here has a story.

Nina talks about children of the revolution. Am not sure if she refers to herself and fellow children of the 27 who were lucky enough to be put under house arrest in Nairobi or flown off to Sweden for I can guarantee that if there are any children of the revolution, its those children who stayed behind. Whose parents did not run away. whether they were fighter or not, the children suffered the effects of war.

I and Philip are such children. Killings, massacres, rapes, tortures -name it we saw or heard of it however much our parents tried to protect us. We saw things that children should never see! My uncles were involved in the war -as fighters and before that at least one in UPM. My father bought drugs for the fighters in the bush at the request of my uncle who was a fighter since 1981. He had taken his 15 year old brother with him and they practically grew up in the army. Those people are never mentioned, never received any medals, and neither did they 'benefit" financially. At least one paid the final sacrifice -on a land mine in Gulu! Another paid the final sacrifice -in a destroyed family and finances. But none of them would ever regret having fought Obote!

They did not get to 'eat"! But this is not their story! Point is that their perspective on the narrative of the war as to who sacrificed and who didnt am sure would be very different from that of Nina or myself!

For so long we have been fed the narrative of 27 men fighting a war while the rest of us were hiding under the bed! No the rest of us were not hiding under the bed! We were out there surviving, dying, sacrificing so that Museveni and his 27 men could share the spoils of the hunt while the rest of us get to watch them!

This war belongs to all of us. It represents the childhood that we lost! The innocence that we lost! the country that we lost! Before this war, everyone in my school did not have a tribe! During and after this war, suddenly everyone had a tribe -and there were good tribes and bad tribes, eating tribes and non eating tribes, killing tribes and victimised tribes! today we think local -in tribes! from kingdoms to small non viable tribal districtlets to balancing the eaters in cabinet to tribe in just about everything!

The narrative of this war has got to be changed. And this will only be when everyone tells their story! the reason that the heroes proclaimed at kololo mean nothing to the rest of ugandans is that this story does not have a narrative the rest of us can relate to! Its a story of 27 men who went out one day to hunt, chased down their animal and killed it and will not share the spoils because according to them, they brought down the animal alone! So they do not have to share!

Until most Ugandans can identify in some way personally with this war, it cannot be compared with the european wars or the fervopur with which Europeans respect and worship their war dead a century later!

If this war is every to be considered as a liberation war, so that we can give our dead all around the country the respect that they should have, its got to be more than the stories of one man and his family and his cronies! Then the medals stuck on peoples chests in a selective fashion Kabalega but not Mwanga, Mugisha Muntu but not Besigye) will mean something! Until then its those in the kintu congratulating themselves on having hunted and killed the animal alone -thus eating alone or deciding who gets to eat!

Let everybody tell their story. And for Nina, trust me, those who got away were the lucky ones!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Nina](http://ddembe.wordpress.com/tag/nina/), [War](http://ddembe.wordpress.com/tag/war/)
