# The teachers of this country are very angry!^[https://www.facebook.com/notes/drew-ddembe/the-teachers-of-this-country-are-very-angry/10150289549557681]

September 6, 2011 at 11:42pm ·


https://www.facebook.com/permalink.php?story_fbid=10150358357086259&id=712431258¬if_t=feed_comment_reply

I agree Nina Mbabazi. 

Salary increases shouldnt be for a specific group at the exclusion of everyone else. That would be logical to everyone except of course the NRM.

More than 20 years ago, the starting salary of a junior lawyer in the MoJ was a million shillings. Museveni later claimed that this was because of "misinformation" he received presumably from the late Abu Mayanja who was then Attorney General and Minister of Justice.

Asked at the time why he did not increase the pay for Medical Consultants, his response was that doctors were unproductive and that he would pay doctors a living wage when they became "productive" whatever that means! 25 years later a doctor with 15 years post graduate experience is lucky to make a million shillings!

When URA was started, it was rumoured that some people went to their villages and collected all of their boys and girls for jobs. the salary of many high school drop outs in URA top those of a doctor and that of Kagina would make many well paid professionals in the diaspora drool as they wouldn't even have to leave home! Doctors are still waiting for the promised living wage!

Teachers are even worse paid albeit their numbers are significantly more than doctors and they are easier and cheaper to train and replace. At 200,000 a month, the 20 million shilling bribe paid to MP's to pass the Kabaka muzzling bill can pay 100 of them for a month or one of them for 8 years! and four months.

As for those ba sirukale in uniform, his government has treated them like basiru ddala ddala! The 160,000 they earn before PAYE, was given in lumpsum to each MP for the equivalent of 12 years and 5 months salary. For that they are required to abuse their fellow citizens so as to keep those who are exploiting them in power!

Now when we start adding up people who are allowed to chose their own salaries of 43 million, others making tens of millions each month, MP's and ministers with perks costing billions, LC's at all levels, RDC's, presidential advisors and all manner of political appointees who Tamale has clearly stated were given jobs as welfare just so they could get a share of the gravy train the rest of Ugandans are locked out of, the billions and trillions wasted on fanciful re elections and expensive toys as well as the billions wasted in corruption with the most high profile cases in the last few years being GAVI, NSSF/Temangalo, CHOGM, Greenland Bank/UCB, AGOA, various public properties and companies sold to well connected politicians and individuals, you have a right mess!

Couple that with the fact that nothing appear s to work. Umeme is a disappointment, roads are crap and expensive to build, mortgages are expensive, people are jobless, and you are really in trouble with a really angry population. Spray them with coloured water and teargas as well as bullets and you have a revolution waiting to happen!

This government has never had a coherent policy on the provision of services including providing a living wage to workers such as teachers.

And all of these nice arguments are not going to make sense to them as they have 25 years of proof that you really do not care about them!

So its teachers today but wait till the others all join in! Tell daddy that ordering angry hungry people around really pisses them off and is likely to backfire! Much better to talk to them!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Letters to Nina](http://ddembe.wordpress.com/tag/letters-to-nina/), [Nina](http://ddembe.wordpress.com/tag/nina/)
