# Will the children of NRM politicians help Ugandans escort their fathers back to their villages?^[https://www.facebook.com/notes/drew-ddembe/will-the-children-of-nrm-politicians-help-ugandans-escort-their-fathers-back-to-/10150890186847681]

Friday, June 29, 2012 at 8:51pm ·
‎

@Muhiire says,

- Robert Kabushenga
 
- Kwame Rugunda

- Rugaba Hussein Kashillingi

- Eva Rukikaire Mwine

- Annette Mirembe Kategaya

- Nina Mbabazi

Give them more mash and add concentrates, Mukene, Spinach, & cabbages and let the fattened birds remain in their deep slumber for the rest of their useful time. A brilliant Idea! Talk of fattened, castrated bulls! well kept in an electric enclosure. no worries about tomorrow as long as there is enough grass and piped water in their paddocks and you can even rap and get away with it as you prolong their slumber!

TALK OF WASTED INTELLECT!

Give the broilers ten years in the same state, they will be as good as local crude waragi drinkers in terms of 'nationalism' achievements. 'mbu' they also have five sense! The old generation in power today, might be on a mission to render the young generation useless. The broilers are enemies of themselves! There is a big diffence between a man & manhood. I can see a wasted generation in making!"

https://www.facebook.com/photo.php?fbid=433728849983575&set=a.100120663344397.48.100000393901179&type=1&ref=notif¬if_t=photo_comment_tagged

Barbra Natifu,

I believe these six were chosen because they are the children of prominent politicians who have at some point or other had some prominence or involvement in public life -or not.

I believe the targeting presupposes that being born into priviledge and recipients of the benefits of being the children of politicians who have benefited financially and otherwise from the longevity of the NRM, they are somehow obliged to make a contribution to society.

In fact the post insinuates that they are disappointments for having taken the 'wrong side" in or not taking any side at all!

To some extent its true despite protestations to the contrary that all of the above have been priviledged whether they acknowledge it or not. It is normal for all of us to assume that we have our headstart in life because we are uniquely talented and those less fortunate souls who fall off the treadmill of life or live close to the bottom are just plain lazy!

Reality however is that our backgrounds are very much dictated by the station in life that our parents hold and if those parents have greater access to public goods which they can leverage to get us a better education and lifestyle, seats on company boards, contracts from foreign companies that are simply interested in the real or imagined patronage that our family name brings to them even when we bring little in the way of real skills we have to be really stupid to fail. So the above people can protest all they like but reality is that they were given a head start regardless of whether they acknowledge it or not.

Those of us who have been priviledged could be said to have some sort of obligation to return something to the society that has been so kind to us. But is this really an obligation or a personal choice?

The NRM and Museveni as well as his wife have made it obligatory for Ugandans to "be patriotic". As a matter of fact some of the above have tried to use the patriotic argument to counter any accusations by those who believe that their fathers have mismanaged our country and economy. If we all have to be patriotic then one would have to demand that those who have had most priviledge be the first ones to put their words where their mouths are! Certainly if these people who are clearly benfiting from the animal their fathers killed are not ready to step up and defend it, what business do I have defending it for them?

But again one has got to ask -do these people have an obligation to fight for and defend what their fathers fought and killed for?

That presupposes that they are happy that our society is well managed and their fathers and mothers are doing a very good job and should not be retired in the publics best interest!

I happen to believe that the countries top managers, the parents of the above six have done their job and have reached the limits of their own skills and need to hand over.

However I believe in merit and not inheritance. The above six even if they viewed public life as their obligation have no more right than any other suitably qualified person to take on as leaders of the next generation.

In my humble opinion if they wish to take part in future leadership, it should not be from a position of priviledge and right of inheritance but because they actually have got something to donate back to society. They have to chose the side of the people. This is true whether they chose to stay in the run down and increasingly decadent NRM or chose to break with their parents.

The NRM is in need of reform to come back in line with peoples aspirations. In its current form and leadership, it is going to die whether the owners accept it or not! It is where KANU and UPC were in the past! Whether these young people want to die with it or not is upto them!

As an aside, I note the comments of Hussein and Nina with regard to their childhood sacrifices.

There is a tendency for some children of NRM bigwigs to play the poor little rich me card ie the Marie Antoinette card. Poor me had to live in a flat in Sweden on sausages kind and endure house arrest kind of thing.

With all due respect, there are many Ugandans who lost more in a war that was not theirs. Unlike Kabushenga and Hussein, the rest here did not lose their parents and they went on to become the most priviledged members of our society for more than half of Ugandan's post independence life. Parents pass on their priviledges to their children and while one can fail even with a priviledged background, one is less likely to if they have priviledge. Do not take the difference with which people treat you for granted -it does confer certain priviledges and advantages.

Reality is that there are those of us whose grandparents and parents were well on their way to comfort and priviledge who have been direct or indirect victims of the chaos and wars the parents of the above were involved in. Its always assumed that the grass is not important but in reality it is. Actually it should always be about the grass! but is it ever? The people who ride to power and stay in power on the blood and livelihoods of others somehow always believe that its their right rather than a priviledge that confers greater responsibility upon them!

Lives were lost and dreams destroyed and were it not for the wars, those families that were already ahead by the 60′s would have been much farther ahead if their fathers were not killed, their property looted, their mothers raped or their childhood traumatised. And unlike those who were connected they did not have access to state house scholarships to help them out even if they were bright enough and neither have they completed masters degrees abroad on state scholarship ahead of their brighter peers nor got accelerated promotions or choice appointments as a result of their connections.

I have the advantage of having relatives who gave up everything to join the NRM and UPM but got nothing out of it but death, jail, lost dreams and destroyed livelihoods so those who believe they "sacrificed' need to have more humility!

So I would submit that while the comments above may not apply individually, humility is important. I also submit that the use of the word broiler is unwarranted and kind of stiffles the debate as to whether the above men and women who may have something to give to the country need to step up and take a more active role and use their priviledge and good education as well as financial 'biens' to advance our society.

And this will of course include shaping the future of this country and will more than likely include taking the side of Ugandans in escorting their parents back home to their villages and ranches and asking them to learn other skills like rocking grandchildren and counting cows and goats!

  
Filed under: [Nina](http://ddembe.wordpress.com/category/nina/) Tagged: [Nina](http://ddembe.wordpress.com/tag/nina/)
